### PR TITLE
Save the help card visibility in a Set

### LINKED ISSUE #2356: help info box disappears after changing answer
**Describe the bug**
The help info box disappears after user changes the answer to any questionnaire item.

**Component**
SDC library

**To Reproduce**
1. Open the catalog app
2. Go to the help component
3. Tap the info icon
4. Tap the answer of the widget below it

**Expected behavior**
The help info box should still be shown, and should only disappear if the user taps the help info icon again.

**Demo**

[Screen_recording_20231107_162945.webm](https://github.com/onaio/fhir-resources/assets/62053304/c1704cba-f607-46e8-b562-d22a540b27f6)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2356

**Description**
1. Create a Set that keeps the Questionnaire Item of the help card, if the Questionnaire Item of that help card exists in the state flow, then that help card will be visible when the screen got re-rendered i.e. when changing answer
2. Create a callback to save the help card visibility to the Set

**Alternative(s) considered**
N/A

**Type**
Bug fix

**Screenshots (if applicable)**

[Screen_recording_20231207_160124.webm](https://github.com/google/android-fhir/assets/62053304/00baca2c-d5f7-4ad9-9ed9-c5ac5031b4ab)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 1]
```diff
@@ -251,6 +252,19 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
   /** Toggles review mode. */
   private val isInReviewModeFlow = MutableStateFlow(shouldShowReviewPageFirst)
 
+  /** Tracks which help card has been opened. */
+  private val openedHelpCardSet: MutableStateFlow<MutableSet<String>> =
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: link ids don't actually uniquely identify (questionnaire item, questionnaire response item) pairs, see https://build.fhir.org/questionnaireresponse.html#link.

i think this set should probably be of type questionnaire response.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 1 above)
Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: @jingtang10 yeah that works too

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: or, the set could be of type questionnaire item, since the help code is tied to it.

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt]: updated to questionnaire item type

**Comment by FikriMilano** [comment]
@jingtang10 this is ready for review again.
Also, please have a nice holiday :D

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 2]
```diff
@@ -253,17 +253,18 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
   private val isInReviewModeFlow = MutableStateFlow(shouldShowReviewPageFirst)
 
   /** Tracks which help card has been opened. */
-  private val openedHelpCardSet: MutableStateFlow<MutableSet<String>> =
+  private val openedHelpCardSet: MutableStateFlow<MutableSet<QuestionnaireItemComponent>> =
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: this should be questionnaire response item component instead.

in the case of repeated groups, or repeated nested items, you would end up with multiple questions corresponding to the same questionnaire item. in these cases it would not make sense to show/hide help card for all of them at once.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 3]
```diff
@@ -253,17 +253,18 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
...
     MutableStateFlow(mutableSetOf())
 
   /** Callback to save the help card state. */
-  private val helpCardStateChangedCallback: (Boolean, String) -> Unit = { shouldBeVisible, linkId ->
-    if (shouldBeVisible) {
-      openedHelpCardSet.update { it.apply { add(linkId) } }
-    } else {
-      openedHelpCardSet.update { it.apply { remove(linkId) } }
+  private val helpCardStateChangedCallback: (Boolean, QuestionnaireItemComponent) -> Unit =
+    { shouldBeVisible, linkId ->
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:261]:
```suggestion
    { shouldBeVisible, questionnaireResponseItem ->
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt [hunk 4]
```diff
@@ -58,25 +59,26 @@ fun initHelpViews(
...
       GONE
     }
+  val helpCardItem = questionnaireItem.item.firstOrNull { it.isHelpCode }
   helpButton.setOnClickListener {
+    if (helpCardItem == null) return@setOnClickListener
     helpCardView.visibility =
       when (helpCardView.visibility) {
         VISIBLE -> {
-          helpCardStateChangedCallback.invoke(false, helpCardItem!!.linkId)
+          helpCardStateChangedCallback.invoke(false, helpCardItem)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:77]:
```suggestion
          helpCardStateChangedCallback(false, helpCardItem)
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt [hunk 5]
```diff
@@ -58,25 +59,26 @@ fun initHelpViews(
...
           GONE
         }
         else -> {
-          helpCardStateChangedCallback.invoke(true, helpCardItem!!.linkId)
+          helpCardStateChangedCallback.invoke(true, helpCardItem)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:81]:
```suggestion
          helpCardStateChangedCallback(true, helpCardItem)
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 2 above)
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: does this actually need to be a mutable state flow? it's not really being listened to by the ui - it's simply used to populate the questionnaire view item right?

this can just be a private set.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 2 above)
Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: ah I see, okay

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: yeah, we can have it as a set

**Comment by FikriMilano** [comment]
@jingtang10 this PR is ready for review

**Review by jingtang10 — APPROVED** [review]
