### PR TITLE
Handle InputeditText request focus to fix the application force close exception.

### LINKED ISSUE #863: Reference/Gallery app get crashed when request focus get switched to bottom view.
**Describe the bug**
Reference/Gallery app get crashed when request focus get switched to bottom view.

**Component**
SDC library, reference app, or SDC gallery app

**To Reproduce**
1. Open reference app
2. Click on patient record, it opens patient details screen
3. Click on edit icon, it opens patient edit screen.
4. Click on city edittext box
5. Click on next request focus on soft keyboard.
6. Application get crashed.

Gallery App : 
1. Open Gallery App.
2. Click on Neonate record.
3. Click on city edittext box
4. Click on next request focus on soft keyboard.
5. app get crashed when focus reach at bottom view.

_**Need to debug the issue further to fix the issue.**_

logs : 
2021-10-25 17:56:42.629 30171-30171/com.google.android.fhir.reference E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.reference, PID: 30171
    java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
        at android.widget.TextView.onKeyUp(TextView.java:8618)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2866)
        at android.view.View.dispatchKeyEvent(View.java:14247)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5955)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5823)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5375)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5493)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5349)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5550)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5322)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5375)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5349)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5322)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8095)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8046)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8006)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5083)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-10-25 17:56:42.630 30171-30171/com.google.android.fhir.reference E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #863 

**Description**
Application was crashing as focus was given to the next inputEditText which is not visible as soft keyboard was shown.

Now, search the focusable inputEditText in down direction and request the focus only if it found. If focusable item is not visible then focus will not be given. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by joiskash — COMMENTED** [review]
This is a good fix! Another issue I have noticed is with the Date and time widget. Please have a look at the video that I have attached. I think you can add some similar check which will prevent this from happening. It happens with the drop down too. 

https://user-images.githubusercontent.com/48797364/145559102-660a992a-36d7-49f2-9ced-de6b570f59ad.mp4

.

**Comment by santosh-pingle** [comment]
@joiskash 
Actually, this change is to fix the force close exception as mentioned in the issue #863. 
But I do not see any application crash in the attached video.

Just wanted to know whether you are talking about the application crash or something else?

**Comment by joiskash** [comment]
There is no crash, but the date widget pops up every time the cursor is on the first widget and the page is changed. Its a bug. The date widget should not pop-up unless clicked on.

**Comment by santosh-pingle** [comment]
Can you please create separate issue/bug for this, thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt [hunk 1]
```diff
@@ -76,6 +79,13 @@ internal abstract class QuestionnaireItemEditTextViewHolderDelegate(
           .hideSoftInputFromWindow(view.windowToken, 0)
       }
     }
+
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:82]:
```suggestion

    // Override `setOnEditorActionListener` to avoid crash with `IllegalStateException` if it's not possible to move focus forward.
    // See https://stackoverflow.com/questions/13614101/fatal-crash-focus-search-returned-a-view-that-wasnt-able-to-take-focus/47991577
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt [hunk 2]
```diff
@@ -76,6 +79,13 @@ internal abstract class QuestionnaireItemEditTextViewHolderDelegate(
...
+    textInputEditText.setOnEditorActionListener { view, actionId, _ ->
+      if (actionId != EditorInfo.IME_ACTION_NEXT) {
+        false
+      }
+      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:87]: why are they different?

```suggestion
      view.focusSearch(FOCUS_FORWARD)?.requestFocus(FOCUS_FORWARD) ?: false
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:87]: 1. With change `view.focusSearch(FOCUS_FORWARD)?.requestFocus(FOCUS_FORWARD) ?: false`
- it shows warning, please see attached image.
warning
- Yes, focus was given to the focusable item.
   (https://user-images.githubusercontent.com/86107848/146324243-302c3cbe-e68c-4cd3-9c53-37dc23350cb1.mov).


2. With change `view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false`
-  There is no warning.
-  It scrolls page down.
   (https://user-images.githubusercontent.com/86107848/146324407-33e48607-04cf-44c8-859c-33e21f45c1d3.mov)

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt]: Updated suggested change.

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt]: Build fails
/Users/runner/work/android-fhir/android-fhir/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:89: Error: Must be one of: View.FOCUS_LEFT, View.FOCUS_UP, View.FOCUS_RIGHT, View.FOCUS_DOWN [WrongConstant]

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt]: Interesting, so I guess they: 

- https://newbedev.com/fatal-crash-focus-search-returned-a-view-that-wasn-t-able-to-take-focus
- https://stackoverflow.com/questions/13614101/fatal-crash-focus-search-returned-a-view-that-wasnt-able-to-take-focus/47991577

are probably using deprecated apis/constants.

have you tried using FOCUS_DOWN in both?

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt]: Updated change `view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_DOWN) ?: false`

**Review by jingtang10 — APPROVED** [review]
