### PR TITLE
Fix added for crashe on click of submit button after editing patient details

### LINKED ISSUE #1229: App crashes click on submit button after editing patient details
**Describe the bug**
As soon as the patient list populated select any patient from list. click on edit button though details page is empty and the click on submit button

**Component**
SDC library, reference app

**To Reproduce**
1. Launch App and let patient list populate
2. Click on any patient from list it open details page 
3. details page takes time to display data but don't wait for it
4. click on edit button on right top corner and then click on submit button
5. See error : App crashes with NPE

**Expected behavior**
Either Edit button should not be enabled/ clickable till the data is not displayed on detail screen Also till details are not edited submit button should not be enabled/clickable. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 11
 - Build number: 00WW_2_410_SP02

Device Logs
[EditSubmitNPE.txt](https://github.com/google/android-fhir/files/8230378/EditSubmitNPE.txt)

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1229

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Progressbar can be added till data gets loaded on screen

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt [hunk 1]
```diff
@@ -33,6 +33,7 @@ import com.google.android.fhir.datacapture.QuestionnaireFragment
 /** A fragment representing Edit Patient screen. This fragment is contained in a [MainActivity]. */
 class EditPatientFragment : Fragment(R.layout.add_patient_fragment) {
   private val viewModel: EditPatientViewModel by viewModels()
+  private var isBindingDone: Boolean = false
```
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt:36]: i'm not sure these things should be stored as private vars... that just introduces state into the ui classes. in android these should be coming from view model. @stevenckngaa @yigit do you agree?

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt [hunk 2]
```diff
@@ -47,7 +48,13 @@ class EditPatientFragment : Fragment(R.layout.add_patient_fragment) {
     requireArguments()
       .putString(QUESTIONNAIRE_FILE_PATH_KEY, "new-patient-registration-paginated.json")
 
-    viewModel.livePatientData.observe(viewLifecycleOwner) { addQuestionnaireFragment(it) }
+    viewModel.livePatientData.observe(viewLifecycleOwner) {
+      addQuestionnaireFragment(it)
+      if (it != null) {
+        isBindingDone = true
+        activity?.invalidateOptionsMenu()
+      }
```
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt:56]: can you just simply set the visibility to visible here?

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt [hunk 3]
```diff
@@ -63,6 +70,11 @@ class EditPatientFragment : Fragment(R.layout.add_patient_fragment) {
     inflater.inflate(R.menu.add_patient_fragment_menu, menu)
   }
 
+  override fun onPrepareOptionsMenu(menu: Menu) {
+    val menuItemEdit = menu.findItem(R.id.action_add_patient_submit)
+    menuItemEdit.setVisible(isBindingDone)
```
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt:75]: should the default visibility be invisible?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 1 above)
Comment (jingtang10) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt:36]: @kevinmost

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 2 above)
Comment (stevenckngaa) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt:56]: +1. I don't know if that's needed to store a variable.

From my understanding, `invalidateOptionsMenu` recreates the entire menu. This seems a bit an overkill for updating the visibility of a button.

On top of that, should we disable the button from the menu rather than making it invisible?

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 3 above)
Comment (stevenckngaa) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt:75]: +1. Probably put the default in action_add_patient_submit.xml and fix the issue across the board. Look like ScreenFragment is missing from the fix.

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 1 above)
Comment (PallaviGanorkar) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt]: Removed private variable. Now button is enabled and disabled on the basis of live data availability

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 3 above)
Comment (PallaviGanorkar) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt]: This issue is not present in ScreenerFragment. It works fine with max count of resources(in demo app patients) as well.

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 2 above)
Comment (PallaviGanorkar) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt]: On Android 3.0 and higher, on call to [invalidateOptionsMenu()](https://developer.android.com/reference/android/app/Activity#invalidateOptionsMenu()) intternally system calls [onPrepareOptionsMenu()](https://developer.android.com/reference/android/app/Activity#onPrepareOptionsMenu(android.view.Menu)).

File: demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt (hunk 3 above)
Comment (PallaviGanorkar) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt]: @jingtang10  As discussed removed onPrepareOptionsMenu() method and updated code

Comment (PallaviGanorkar) [reply demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt]: For disable state of edit button i have added "reticle_ripple" i.e. #9AFFFFFF. If required we can change it

File: datacapture/src/main/res/color/edit_menu_color.xml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+<?xml version="1.0" encoding="utf-8" ?>
```
[the remark this answers is not in the document]
Comment (PallaviGanorkar) [reply datacapture/src/main/res/color/edit_menu_color.xml:1]: Yes. I missed it. Done

File: demo/src/main/res/menu/details_options_menu.xml [hunk 5]
```diff
@@ -24,5 +24,6 @@
         app:showAsAction="always"
         android:icon="@drawable/baseline_edit_24"
         android:title="@string/menu_patient_edit"
+        android:enabled="false"
```
[the remark this answers is not in the document]
Comment (PallaviGanorkar) [reply demo/src/main/res/menu/details_options_menu.xml]: Done

File: demo/src/main/res/menu/add_patient_fragment_menu.xml [hunk 6]
```diff
@@ -3,10 +3,10 @@
...
 >
-<item
+    <item
         android:id="@+id/action_add_patient_submit"
+        android:enabled="false"
         android:title="@string/submit"
         app:showAsAction="always"
-    >
-</item>
+    />
```
[the remark this answers is not in the document]
Comment (PallaviGanorkar) [reply demo/src/main/res/menu/add_patient_fragment_menu.xml:11]: Done but there are no changes to this file.

File: demo/src/main/java/com/google/android/fhir/demo/AddPatientFragment.kt [hunk 7]
```diff
@@ -51,6 +51,7 @@ class AddPatientFragment : Fragment(R.layout.add_patient_fragment) {
   override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
     super.onCreateOptionsMenu(menu, inflater)
     inflater.inflate(R.menu.add_patient_fragment_menu, menu)
+    menu.findItem(R.id.action_add_patient_submit).setEnabled(true)
```
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/AddPatientFragment.kt:54]: please create separate menus for add patient and edit patient so you don't need to set this.

File: demo/src/main/res/color/edit_menu_color.xml [hunk 8]
```diff
@@ -0,0 +1,5 @@
+<?xml version="1.0" encoding="utf-8" ?>
+<selector xmlns:android="http://schemas.android.com/apk/res/android">
+    <item android:color="@color/white" android:state_enabled="true" />
+    <item android:color="@color/reticle_ripple" android:state_enabled="false" />
```
Comment (jingtang10) [inline demo/src/main/res/color/edit_menu_color.xml:4]: instead of using a specific color - can you use material colors: https://m3.material.io/libraries/mdc-android/color-theming

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: demo/src/main/res/color/edit_menu_color.xml (hunk 8 above)
Comment (PallaviGanorkar) [reply demo/src/main/res/color/edit_menu_color.xml]: Done
