### PR TITLE
Applying validation on bind to keep validation message relavant to current questionnaireItemViewItem

### LINKED ISSUE #673: Continously switching between pages validation refresh bug
**Describe the bug**
Continuously switching pages with an answer that is out of the validation limit i.e. a red **!** is  displayed on the text view and does not refresh.
 
**Component**
SDC library

**To Reproduce**
1. Use the questionnaire attached in this issue
2. Answer the questions backward. 
3. On page 5 type in a number greater than 5
3. Then press previous until you reach page 2
4. You will still see the validation message

**Expected behavior**
The validation message should be relevant to the question

**Smartphone (please complete the following information):**
 - Oneplus 7T Pro

Originally reported by Keith Hanna

### PR DESCRIPTION
**Pull request by joiskash**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #673 

**Description**
I am calling the `applyValidationResult` in the `QuestionnaireItemEditTextViewHolderFactory` onBind function. So that everytime we switch the page, the validation result relevant to the current questionnaireItemViewItem is displayed

**Alternative(s) considered**
Nope

**Type**
Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by jingtang10 — CHANGES_REQUESTED** [review]
Thanks @joiskash!

Thinking in the context of #374 and #577, I wonder if you can make `applyValidationResult` a method in the interface `QuestionnaireItemViewHolderDelegate`.

And then in `QuestionnaireItemViewHolder` you can make sure that the validation code is called upon bind for all widgets:

```
  open fun bind(questionnaireItemViewItem: QuestionnaireItemViewItem) {
    delegate.bind(questionnaireItemViewItem)
    delegate.validate(
      QuestionnaireResponseItemValidator.validate(
        questionnaireItemViewItem.questionnaireItem,
        questionnaireItemViewItem.questionnaireResponseItem,
        delegate.getContext()
      )
    )
  }
```

**Comment by joiskash** [comment]
Sure ! Im sorry i completely missed this. Will get on it today.

**Comment by joiskash** [comment]
@jingtang10 I have made the changes as requested by you. I also tried to pull in the setItemFocus change into the QuestionnaireItemViewHolderDelegate so that when the focus is lost, the validation is checked again.
This does not work for some widgets though, because the TextView on focus does not get triggered. For eg: In the Checkbox group

**Comment by joiskash** [comment]
@aditya-07 Can you please review this?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt [hunk 1]
```diff
@@ -163,6 +166,23 @@ internal object QuestionnaireItemAutoCompleteViewHolderFactory :
...
+      override fun validate(
+        questionnaireItemViewItem: QuestionnaireItemViewItem,
+        context: Context
+      ) {
+        val validationResult =
+          QuestionnaireResponseItemValidator.validate(
+            questionnaireItemViewItem.questionnaireItem,
+            questionnaireItemViewItem.questionnaireResponseItem,
+            context
+          )
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt:178]: this code is repeated in every widget. can you create a new function in the delegate that returns this?

if you do that, perhaps the delegate needs to be an abstract class rather than an interface.

additionally, maybe `questionnaireItemViewItem` needs to moved to the delegate as well (and potentially assigned in the bind function?)

**Review by jingtang10 — CHANGES_REQUESTED** [review]
thanks @joiskash!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt [hunk 2]
```diff
@@ -79,4 +83,7 @@ interface QuestionnaireItemViewHolderDelegate {
 
   /** Binds a [QuestionnaireItemViewItem] to the view. */
   fun bind(questionnaireItemViewItem: QuestionnaireItemViewItem)
+
+  /** Validates a [QuestionnaireItemViewItem] and displays validation messages on the view. */
+  fun validate(questionnaireItemViewItem: QuestionnaireItemViewItem, context: Context)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:88]:
```suggestion
  fun displayValidationResult(validationResult: ValidationResult)
```

**Comment by jingtang10** [comment]
you may also want to create a new function that is like a callback `onAnswerChanged` which calls the validation code and displays the result...

also i don't know if you can refactor the delegate... not sure if we can get rid of it

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt (hunk 1 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt]: done , I have changed it as per your feedback. Please have a look

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt (hunk 2 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt]: done

**Comment by joiskash** [comment]
> 
> 
> you may also want to create a new function that is like a callback `onAnswerChanged` which calls the validation code and displays the result...
> 
> also i don't know if you can refactor the delegate... not sure if we can get rid of it

done.. I did refactor the delegate a bit. Please have a look.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt [hunk 3]
```diff
@@ -58,6 +58,14 @@ internal object QuestionnaireItemCheckBoxGroupViewHolderFactory :
         }
       }
 
+      override fun displayValidationResult(validationResult: ValidationResult) {
+        val validationMessage =
+          validationResult.validationMessages.joinToString {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt:63]: can you creat an extension function to validation result to get the single string validation message?

**Review by jingtang10 — APPROVED** [review]
this is great. thanks @joiskash!

@kevinmost can you also take a look at this and see if the interface makes sense to you? thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt [hunk 4]
```diff
@@ -70,13 +75,37 @@ open class QuestionnaireItemViewHolder(
  * is a unique [QuestionnaireItemViewHolderDelegate] for each [QuestionnaireItemViewHolder]. This is
  * critical for the correctness of the recycler view.
  */
-interface QuestionnaireItemViewHolderDelegate {
+abstract class QuestionnaireItemViewHolderDelegate {
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:78]: Is it possible to keep this as an interface?

The two functions with bodies look like they could be extension functions.

```kotlin
fun QuestionnaireItemViewHolderDelegate.onAnswerChanged(context: Context) { ... }
fun QuestionnaireItemViewHolderDelegate.getValidationResult(context: Context): ValidationResult { ... }
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt [hunk 5]
```diff
@@ -163,6 +164,14 @@ internal object QuestionnaireItemAutoCompleteViewHolderFactory :
         presetValuesIfAny()
       }
 
+      override fun displayValidationResult(validationResult: ValidationResult) {
+        val validationMessage =
+          validationResult.validationMessages.joinToString {
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt:169]: Same comment for all of these, but could this be:

```
validationResult.validationMessages.joinToString(separator = "\n")
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt (hunk 4 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:78]: if we do this we wil also need `getQuestionnaireItemViewItem()` as a new API because we have a new member in this abstract class.

i'm happy with keeping this as interface. but what's the thinking behind this suggestion @kevinmost?

i also kinda want to merge the delegate with the view holder itself... but i've managed to do it myself. someone might have a clever way of simplifying this :)

Comment (kevinmost) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:78]: If we change this to an interface, wouldn't we just drop the word `abstract` from

```kotlin
abstract var questionnaireItemViewItem: QuestionnaireItemViewItem
```

? Am I missing something else we need to do?

I don't feel strongly about this; interfaces are just more flexible than abstract classes and it would be nice to keep things as flexible as possible.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt (hunk 5 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt (hunk 4 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt]: done, you are right, I did not have to do any changes. I just removed abstract class and put interface instead.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt (hunk 3 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt]: done

**Comment by joiskash** [comment]
@kevinmost Can you please take another look, I will merge once you are fine with the changes.

**Review by jingtang10 — APPROVED** [review]
👍🎉 great work! thanks!
