### PR TITLE
Synchronize sync workers

### LINKED ISSUE #2361: Concurrent Sync Worker execution can lead to data inconsistencies
**Describe the bug**
Recent changes in PR #2053 allow two sync workers to run concurrently.
This can lead to inconsistencies if a manual one-time sync and a periodic sync overlap.
The problem arises because both workers might attempt to upload resources in a conflicting order, potentially causing:
1. Upload of older resources before newer ones
2. Overwriting of data

**Component**
Fhir Engine Library

**To Reproduce**
Not sure how to reproduce as it requires concurrent running of the workers to sync resources that can cause inconsistency.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by MJ1998**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2361 

**Description**
We use the recommended way for mutual exclusion: [link](https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#mutual-exclusion)

Solution: Wrap the `FhirSynchronizer#synchronize` with `mutex.withLock`

mutex.withLock will suspend the successive invocations of `FhirSynchronizer#synchronize`, without blocking the thread, until the lock is released. Hence all work requests will be processed - and in FIFO order.

**Alternative(s) considered**
Alternative: One alternative involves using a ReentrantLock within a try-catch-finally block. This approach essentially replicates mutex-like behavior to manage concurrent access to shared resources. It would require maintaining a job queue to handle work requests sequentially. Without a queue, workers would need to return Result.retry, leading to repeated attempts every 30 seconds.

Another alternative was to wrap `FhirSyncWorker#doWork` with mutex.withLock but based on [this](https://github.com/google/android-fhir/pull/2385#discussion_r1471034556) comment and also for the fact that FhirSynchronizer#synchronize should run sequentially irrespective of whether FhirSyncWorker uses it or not.

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by aditya-07 — CHANGES_REQUESTED** [review]
Please add a test to check the change.

**Comment by MJ1998** [comment]
I am not sure if automation test for this is a good idea. Because it takes lot of execution time to be able to verify the synchronicity of any concurrent jobs.  See how concurrent behavior is verified [here](https://medium.com/mobile-app-development-publication/mutex-for-coroutines-5f4a4ca60763).

Such long execution time, however, is very likely in case of long sync time in an actual app

@aditya-07

File: engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt [hunk 1]
```diff
@@ -60,74 +62,76 @@ abstract class FhirSyncWorker(appContext: Context, workerParams: WorkerParameter
...
-            else -> {
-              setProgress(buildWorkData(syncJobStatus))
             }
           }
         }
-      }
 
-    val result = synchronizer.synchronize()
-    val output = buildWorkData(result)
+      val result = synchronizer.synchronize()
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt:117]: i actually think the mutex can be just inside the synchronizer's synchronize function instead. in general we want to keep the locked code path as minimum as possible. and i think it's unnecessary to lock the rest of this function.

**Review by jingtang10 — APPROVED** [review]
please feel free to merge once tested manually again.

**Review by aditya-07 — APPROVED** [review]

**Comment by MJ1998** [comment]
I figured how to test the mutex locking.
@aditya-07 @jingtang10

File: engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt (hunk 1 above)
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt]: Moved. Also added test.

File: engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt [hunk 2]
```diff
@@ -142,4 +146,36 @@ class FhirSynchronizerTest {
...
+              assertThat(e).isInstanceOf(IllegalStateException::class.java)
+              assertThat(e.localizedMessage).isNotNull()
+              assertThat(e.localizedMessage)
+                .isEqualTo("This mutex is already locked by the specified owner: $mutexOwner")
+            }
+          }
+        }
+      }
+
+      val result = fhirSynchronizer.synchronize()
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt:179]: The test should call `synchronize()` on 2 different `FhirSynchronizer` objects to simulate two workers getting started concurrently. 
Also, you should be able to provide Test downloader / uploader (with longer delay in first synchronizer) instead of mock to simulate a real scenario and use the `SyncJobStatus` maybe to assert that the second synchronize job doesn't start before the end of first synchronize job.

File: engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt [hunk 3]
```diff
@@ -142,4 +146,36 @@ class FhirSynchronizerTest {
...
+        fhirSynchronizer.syncState.collect {
+          if (it is SyncJobStatus.Started) {
+            try {
+              fhirSynchronizer.synchronize()
+            } catch (e: Exception) {
+              assertThat(e).isInstanceOf(IllegalStateException::class.java)
+              assertThat(e.localizedMessage).isNotNull()
+              assertThat(e.localizedMessage)
+                .isEqualTo("This mutex is already locked by the specified owner: $mutexOwner")
+            }
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt:174]: We shouldn't depend on the exception message as the verbiage may change in subsequent versions (which comes from kotlin framework) causing the test to fail.

**Review by aditya-07 — CHANGES_REQUESTED** [review]

File: engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt (hunk 2 above)
Comment (MJ1998) [reply engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt]: Done.

File: engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt (hunk 3 above)
Comment (MJ1998) [reply engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt]: Changed the test.

**Review by aditya-07 — APPROVED** [review]

File: engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt [hunk 4]
```diff
@@ -79,18 +81,20 @@ internal class FhirSynchronizer(
...
+        .let {
+          if (it.isEmpty()) {
+            setSyncState(SyncResult.Success())
+          } else {
+            setSyncState(SyncResult.Error(it))
+          }
         }
-      }
+    }
   }
```
Comment (aditya-07) [inline engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt:98]: @MJ1998 Forgot to add this earlier, but could you please add doc to the function explaining its locking.

Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt:98]: Added in #2417
