### PR TITLE
Return unique include and revInclude resources per search filter match.

### LINKED ISSUE #2512: Several records of resources with same resource Id returned leading to duplication
**Describe the bug**
When editing or updating resources in the db, severral resource with different last updated exist on the db. This lead to resources with the same id but different last updated time.  When searching for the resources on code at 
```kotlin 
fhirEngine.search<Resource>(search)
```
the query 
``` SQL 
SELECT * FROM (
SELECT  rie.index_name, rie.index_value, re.resourceId,  re.serializedResource
FROM ResourceEntity re
JOIN ReferenceIndexEntity rie
ON re.resourceUuid = rie.resourceUuid
LEFT JOIN DateIndexEntity b
ON re.resourceType = b.resourceType AND re.resourceUuid = b.resourceUuid AND b.index_name = '_lastUpdated'
LEFT JOIN DateTimeIndexEntity c
ON re.resourceType = c.resourceType AND re.resourceUuid = c.resourceUuid AND c.index_name = '_lastUpdated'
WHERE rie.resourceType = 'Encounter'  AND rie.index_name = 'subject'  AND rie.index_value IN ('Patient/607155f4-44a9-4dde-a429-5102a80b4420') AND re.resourceType = 'Encounter'
ORDER BY b.index_from DESC, c.index_from DESC
)
```

Result - Records 2 & 4 are similar

```

1 | subject | Patient/607155f4-44a9-4dde-a429-5102a80b4420 | c4c69f24-187a-4ce0-aa13-060b95d64297 | {"resourceType":"Encounter","id":"c4c69f24-187a-4ce0-aa13-060b95d64297","meta":{"lastUpdated":"2024-04-11T14:09:02.874+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"b11dd2d1-d2c4-4573-bdd1-5bbade37b886","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"1.1.0-diabetesCompassClinic","display":"Application Version"}]},"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"AMB"},"serviceType":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/service-type","code":"335"}]},"subject":{"reference":"Patient/607155f4-44a9-4dde-a429-5102a80b4420"},"participant":[{"individual":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}}],"serviceProvider":{"reference":"Organization/41eae946-bdc4-4179-b404-6503ff12f59c"},"partOf":{"reference":"Encounter/patient-visit-2024-04-11-607155f4-44a9-4dde-a429-5102a80b4420"}}
-- | -- | -- | -- | --
2 | subject | Patient/607155f4-44a9-4dde-a429-5102a80b4420 | patient-visit-2024-04-11-607155f4-44a9-4dde-a429-5102a80b4420 | {"resourceType":"Encounter","id":"patient-visit-2024-04-11-607155f4-44a9-4dde-a429-5102a80b4420","meta":{"lastUpdated":"2024-04-11T14:09:02.778+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"b11dd2d1-d2c4-4573-bdd1-5bbade37b886","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"1.1.0-diabetesCompassClinic","display":"Application Version"}]},"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"AMB"},"serviceType":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/service-type","code":"335"}]},"subject":{"reference":"Patient/607155f4-44a9-4dde-a429-5102a80b4420"},"participant":[{"individual":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}}],"period":{"start":"2024-04-11T00:00:00.00Z","end":"2024-04-11T00:00:00.00Z"},"serviceProvider":{"reference":"Organization/41eae946-bdc4-4179-b404-6503ff12f59c"}}
3 | subject | Patient/607155f4-44a9-4dde-a429-5102a80b4420 | b0ba8f6e-3cff-424d-b184-5dc6d796f4b9 | {"resourceType":"Encounter","id":"b0ba8f6e-3cff-424d-b184-5dc6d796f4b9","meta":{"lastUpdated":"2024-04-11T14:05:42.159+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"b11dd2d1-d2c4-4573-bdd1-5bbade37b886","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"1.1.0-diabetesCompassClinic","display":"Application Version"}]},"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"AMB"},"serviceType":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/service-type","code":"335"}]},"subject":{"reference":"Patient/607155f4-44a9-4dde-a429-5102a80b4420"},"participant":[{"individual":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}}],"serviceProvider":{"reference":"Organization/41eae946-bdc4-4179-b404-6503ff12f59c"},"partOf":{"reference":"Encounter/patient-visit-2024-04-11-607155f4-44a9-4dde-a429-5102a80b4420"}}
4 | subject | Patient/607155f4-44a9-4dde-a429-5102a80b4420 | patient-visit-2024-04-11-607155f4-44a9-4dde-a429-5102a80b4420 | {"resourceType":"Encounter","id":"patient-visit-2024-04-11-607155f4-44a9-4dde-a429-5102a80b4420","meta":{"lastUpdated":"2024-04-11T14:09:02.778+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"b11dd2d1-d2c4-4573-bdd1-5bbade37b886","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"1.1.0-diabetesCompassClinic","display":"Application Version"}]},"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"AMB"},"serviceType":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/service-type","code":"335"}]},"subject":{"reference":"Patient/607155f4-44a9-4dde-a429-5102a80b4420"},"participant":[{"individual":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}}],"period":{"start":"2024-04-11T00:00:00.00Z","end":"2024-04-11T00:00:00.00Z"},"serviceProvider":{"reference":"Organization/41eae946-bdc4-4179-b404-6503ff12f59c"}}
5 | subject | Patient/607155f4-44a9-4dde-a429-5102a80b4420 | af306880-090e-474a-ab16-46bd54a44525 | {"resourceType":"Encounter","id":"af306880-090e-474a-ab16-46bd54a44525","meta":{"lastUpdated":"2024-04-11T14:04:59.076+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"b11dd2d1-d2c4-4573-bdd1-5bbade37b886","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"1.1.0-diabetesCompassClinic","display":"Application Version"}]},"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"HH"},"type":[{"coding":[{"system":"http://snomed.info/sct","code":"184047000","display":"Patient registration"}],"text":"Patient registration"}],"priority":{"coding":[{"system":"http://snomed.info/sct","code":"17621005","display":"Normal"}],"text":"Normal"},"subject":{"reference":"Patient/607155f4-44a9-4dde-a429-5102a80b4420"},"participant":[{"individual":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}}],"period":{"start":"2024-04-11T14:04:59+03:00","end":"2024-04-11T14:04:59+03:00"},"reasonCode":[{"coding":[{"system":"http://smartregsiter.org/","code":"client_registration","display":"Client Registration"}],"text":"Client Registration"}],"location":[{"status":"completed","period":{"start":"2024-04-11T14:04:59+03:00","end":"2024-04-11T14:04:59+03:00"}}],"serviceProvider":{"reference":"Organization/41eae946-bdc4-4179-b404-6503ff12f59c"}}

```

**Component**
```kotlin 
fhirEngine.search<Resource>(search)
```

**To Reproduce**
Update any resource, save it in the app SQlite DB then try querying them. Several records will be returned depending on how many times you have made changes on the resources

**Expected behavior**
A single record of any resources should be returned when we make any changes to a resource. 

**Screenshots**
An example is when updating a patient active status to false. Patients` Adrew Kife` returns two resources with same details.

image

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2512 #2567 

**Description**
1. Return distinct included and revIncluded resource per searchIndex.
2. When user updates a resource, if the resource has an `meta.lastUpdated`, use that for index value.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 
**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt [hunk 1]
```diff
@@ -71,6 +71,7 @@ internal abstract class ResourceDao {
         it.copy(
           serializedResource = iParser.encodeResourceToString(resource),
           lastUpdatedLocal = timeOfLocalChange,
+          lastUpdatedRemote = resource.meta.lastUpdated?.toInstant() ?: it.lastUpdatedRemote,
```
Comment (MJ1998) [inline engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:74]: Is this something we missed in some previous PR? 
@santosh-pingle FYI.

Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:74]: We didn't essentially miss it, never took to consideration that the application may change `resource.meta.lastUpdated` since it is a server assigned value.

Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:74]: Since this is not relevant to the current PR can we do this in some other PR ? and raise an issue for it also ?

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt [hunk 2]
```diff
@@ -76,13 +76,15 @@ internal suspend fun <R : Resource> Search.execute(database: Database): List<Sea
         includedResources
           ?.asSequence()
           ?.filter { it.baseResourceUUID == uuid }
+          ?.distinctBy { Pair(it.searchIndex, it.resource.id) }
```
Comment (MJ1998) [inline engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:79]: Should we rather add `SELECT DISTINCT..` to where the query is being created - `Search.getIncludedQuery` and `Search.getRevIncludedQuery` ?

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt [hunk 3]
```diff
@@ -4086,6 +4087,101 @@ class DatabaseImplTest {
     assertThat(searchedObservations[0].logicalId).isEqualTo(locallyCreatedObservationResourceId)
   }
 
+  @Test
+  fun included_and_revIncluded_results_should_have_distinct_resources() = runBlocking {
+    // A person has multiple first names and encounter has multiple location
+    // Searching a group including Patient and revIncluding encounter with results sorted by
+    // Patient.GIVEN and Encounter.LOCATION_PERIOD should return single copies of the resources.
```
Comment (MJ1998) [inline engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:4094]: Can there be a case when duplicate records are returned when only include is used (ie, revInclude is not used) ?

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt (hunk 1 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:74]: This change is one of the ways to fix the [duplicate issue](https://github.com/google/android-fhir/issues/2512). That's why I have added it in this PR itself.

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt (hunk 3 above)
Comment (aditya-07) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:4094]: The issue tests for both at the same time, but under the hood, search api treats include and revInclude as separate functions and their individual results don't interfere with each other. 
Nevertheless, I guess its a good idea to separate the tests out so that we can rely on the tests even when search api internal functionality changes in future.

Comment (MJ1998) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:4207]: Tests look good now! thanks.

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt [hunk 4]
```diff
@@ -128,11 +129,6 @@ internal abstract class ResourceDao {
               createLocalLastUpdatedIndex(resource.resourceType, InstantType(Date.from(instant))),
             )
           }
-          entity.lastUpdatedRemote?.let { instant ->
```
Comment (MJ1998) [inline engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:131]: But lastUpdatedRemote can still be null right ?

**Review by MJ1998 — APPROVED** [review]
LGTM. NIT comment.

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt (hunk 4 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:132]: Yes and it could be null only during the On Device create or update.

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt [hunk 5]
```diff
@@ -2369,7 +2369,7 @@ class SearchTest {
       .isEqualTo(
         """
           SELECT * FROM (
-          SELECT  rie.index_name, rie.resourceUuid, re.serializedResource
+          SELECT DISTINCT rie.index_name, rie.resourceUuid, re.serializedResource
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:2372]: discussed with aditya - i'm worried about what it means to be sorting by a field that is repeated.... for example if you have a patient with two given names aaron and charlie, and another one with two given names barry and david, then what order should this query actually produce, if it's deterministic at all?

do we know that the ordering here is perserved somehow (i.e. we take the first value)?

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt [hunk 6]
```diff
@@ -4086,6 +4087,214 @@ class DatabaseImplTest {
     assertThat(searchedObservations[0].logicalId).isEqualTo(locallyCreatedObservationResourceId)
   }
 
+  @Test
+  fun included_results_should_have_distinct_resources() = runBlocking {
+    // A person has multiple first names. Searching a group including Patient  sorted by
+    // Patient.GIVEN should return single copy of of the Patient resource.
```
Comment (jingtang10) [inline engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:4093]: can you explain a little bit more that the dupliatees of record are generated by the join sql statement for the sorting. and probably link to the issue as well.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt (hunk 5 above)
Comment (aditya-07) [reply engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:2372]: I have added the comments in sort api to describe the nature of repeated fields. 

SQLite finds DISTINCT values first and then ORDERS them (based on explain query plan and my own tests).
So, what I have concluded is that the ordering is done on the first repeating value in each resource ( which translates to first entry in StringIndexEntity table for that resource for that particular index_name) .

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt (hunk 6 above)
Comment (aditya-07) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt]: Done

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt [hunk 7]
```diff
@@ -4086,6 +4087,223 @@ class DatabaseImplTest {
...
+     * A person has multiple first names. Searching a group including Patient sorted by
+     * Patient.GIVEN should return single copy of of the Patient resource.
+     *
+     * In order to sort Patients by given name, engine joins ResourceEntity table with
+     * StringIndexEntity table which may result in multiple rows for a single Patient if the person
+     * has more than one given name.
+     *
+     * So the expectation is that the search result should only include distinct Patients and not
+     * repeated Patients (one for each given name).
+     */
```
Comment (jingtang10) [inline engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:4102]:
```suggestion
    /**
     * This tests that the search query does not return duplicated resources as a result of sorting by a field that has multiple index values. For example, searching a group of patients sorted by
     * Patient.GIVEN should return a single copy of each patient even if some of them might have mulitple given names indexed.
     *
     * Whilst sorting, the resource table and the relevant index table are joined, which could result in multiple rows for a single resource if there are multiple index values for the particular index used in the sorting criteria. This is prevented by adding the `DISTINCT` keyword in the generated SQL query.
     */
```

**Review by jingtang10 — APPROVED** [review]
pls add your findings using the query plan, and performance tests.

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt [hunk 8]
```diff
@@ -4086,6 +4087,223 @@ class DatabaseImplTest {
     assertThat(searchedObservations[0].logicalId).isEqualTo(locallyCreatedObservationResourceId)
   }
 
+  @Test
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt]: done

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt (hunk 7 above)
Comment (aditya-07) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt]: Done

Comment (jingtang10) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt]: need updating again

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt [hunk 9]
```diff
@@ -4086,6 +4207,505 @@ class DatabaseImplTest {
...
+
+    val descendingResult =
+      Search(ResourceType.Group)
+        .apply { include<Patient>(Group.MEMBER) { sort(Patient.GIVEN, Order.DESCENDING) } }
+        .execute<Patient>(database)
+
+    assertThat(descendingResult)
+      .comparingElementsUsing(SearchResultCorrespondence)
+      .displayingDiffsPairedBy { it.resource.logicalId }
+      .contains(SearchResult(group, mapOf(Group.MEMBER.paramName to listOf(p2, p1)), null))
```
Comment (jingtang10) [inline engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:4272]: better to split

File: engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt [hunk 10]
```diff
@@ -90,9 +92,65 @@ interface BaseSearch {
...
+   * the first name (i.e **3** and **2**).
+   */
   fun sort(parameter: StringClientParam, order: Order)
 
+  /**
+   * When sorting is applied on a field with repeated values, the order is defined by the order of
+   * for repeated values in the resource.
+   *
+   * @see sort(parameter: StringClientParam, order: Order) for more details.
+   */
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt:146]: update

File: engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt [hunk 11]
```diff
@@ -90,9 +92,65 @@ interface BaseSearch {
...
   fun sort(parameter: NumberClientParam, order: Order)
 
+  /**
+   * When sorting is applied on a field with repeated values, the order is defined by the order of
+   * for repeated values in the resource.
+   *
+   * @see sort(parameter: StringClientParam, order: Order) for more details.
+   */
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt:154]: update

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt [hunk 12]
```diff
@@ -48,6 +48,9 @@ import timber.log.Timber
  */
 private const val APPROXIMATION_COEFFICIENT = 0.1
 
+private const val MIN_VALUE = "-9223372036854775808"
+private const val MAX_VALUE = "9223372036854775808"
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:52]: add reference to sqlite doc

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt [hunk 13]
```diff
@@ -1719,7 +1719,9 @@ class SearchTest {
         LEFT JOIN StringIndexEntity b
         ON a.resourceUuid = b.resourceUuid AND b.index_name = ?
         WHERE a.resourceType = ?
-        ORDER BY b.index_value ASC
+        GROUP BY a.resourceUuid
+        HAVING MIN(IFNULL(b.index_value,0)) >= -9223372036854775808
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:1723]: can you 1) add test cases where not having this would result in included/revincluded resource not showing up, and 2) add comments in the code to explain this behavior - i imagine where you use min / max values to fill null fields

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt [hunk 14]
```diff
@@ -255,16 +261,32 @@ private fun Search.getSortOrder(
...
+        is StringClientParam,
+        is NumberClientParam, -> "IFNULL(b.index_value,0)"
+        is DateClientParam -> "IFNULL(b.index_from,0) + IFNULL(c.index_from,0)"
+        else -> throw NotImplementedError("Unhandled sort parameter of type ${sort::class}: $sort")
+      }
+
+    sortOrderStatement +=
+      """
+      GROUP BY $otherTable.resourceUuid ${if (groupByColumn.isNotEmpty()) ", $groupByColumn" else "" }
+      HAVING ${if (order == Order.ASCENDING) "MIN($havingColumn) >= $MIN_VALUE" else "MAX($havingColumn) >= $MIN_VALUE"}
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:275]: explain why using min max values here

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt (hunk 13 above)
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:1723]: can you explain why this comparison needs to happen inside `HAVING`? i can understand the use of `IFNULL` but cannot understand the use of `>= -9223372036854775808`

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt [hunk 15]
```diff
@@ -2677,11 +2697,13 @@ class SearchTest {
           SELECT resourceUuid FROM TokenIndexEntity
           WHERE resourceType = ? AND index_name = ? AND (index_value = ? AND IFNULL(index_system,'') = ?)
           )
-          ORDER BY b.index_from DESC, c.index_from DESC
+          GROUP BY re.resourceUuid , rie.index_value
+          HAVING MAX(IFNULL(b.index_from,0) + IFNULL(c.index_from,0)) >= -9223372036854775808
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:2701]: add a comment on why the + is needed

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt (hunk 7 above)
Comment (aditya-07) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt]: Done

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt (hunk 9 above)
Comment (aditya-07) [reply engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt]: Done. Have split all the new tests .

File: engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt (hunk 10 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt]: Done

File: engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt (hunk 11 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt]: Done

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt (hunk 12 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:58]: Done.

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt (hunk 13 above)
Comment (aditya-07) [reply engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:1723]: Extracted the code into a function and added notes about the values , null and comparison.

Added a test where result would not include a null value if `HAVING` clause comparison is not done.

Comment (aditya-07) [reply engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:1723]: Done, added the reason in place where the query is generated.

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt (hunk 15 above)
Comment (aditya-07) [reply engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:2701]: Done, added comment where query is generated.

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt (hunk 14 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:327]: Done

**Review by jingtang10 — APPROVED** [review]
