### PR TITLE
Deduplicate patients record.

### LINKED ISSUE #563: Patient duplication in reference app
**Describe the bug**
Duplicate patients in the reference app

**Component**
Reference app

**To Reproduce**
1. Open the reference app

**Expected behavior**
No patient duplication

**Screenshots**
(Screenshot (21 Jun 2021 09_18_46))

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 11
 - Build number: RQ3A.210605.005

**Additional context**
HAPI test server: http://hapi.fhir.org/search?serverId=home_r4&pretty=true&_summary=&resource=Patient&param.0.qualifier=&param.0.0=NAIROBI&param.0.name=address-city&param.0.type=string&sort_by=&sort_direction=&resource-search-limit=

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #563 

**Description**
Deduplicate resource record by resource id after search query execution.

**Alternative(s) considered**
No

**Type**
Choose one: (Bug fix)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by jingtang10 — CHANGES_REQUESTED** [review]
please add tests

**Comment by santosh-pingle** [comment]
@jingtang10 please review once!

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 1]
```diff
@@ -72,6 +73,7 @@ internal object ResourceIndexer {
       .filter { it.path.isNotEmpty() }
       .map { it to fhirPathEngine.evaluate(resource, it.path) }
       .flatMap { pair -> pair.second.map { pair.first to it } }
+      .distinctBy { pair -> indexValues(pair) }
       .forEach { pair ->
         val (searchParam, value) = pair
         when (SearchParamType.fromCode(pair.first.type)) {
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:79]:
```suggestion
        when (SearchParamType.fromCode(searchParam.type)) {
```

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 2]
```diff
@@ -286,6 +288,61 @@ internal object ResourceIndexer {
...
+      SearchParamType.QUANTITY -> quantityIndexValues(searchParam, value)
+      SearchParamType.URI -> uriIndexValues(searchParam, value)
+      SearchParamType.SPECIAL -> specialIndexValues(searchParam, value)
+      else -> null
+    }
+  }
+
+  private fun numberIndexValues(searchParam: SearchParamDefinition, value: Base): Serializable? {
+    var n: NumberIndex? = numberIndex(searchParam, value)
+    return n?.let { Triple(n.name, n.path, n.value) }
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:308]: never use single letter param names.

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 3]
```diff
@@ -286,6 +288,61 @@ internal object ResourceIndexer {
     }
   }
 
+  private fun indexValues(pair: Pair<SearchParamDefinition, Base>): Serializable? {
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:291]: so for every index record, you'll be calculating the index twice - this seems like a waste?

can you generate these indices first, and then find a way to deduplicate?

maybe you'll need to redefine a `equals` function for the index classes?

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 4]
```diff
@@ -72,6 +73,7 @@ internal object ResourceIndexer {
       .filter { it.path.isNotEmpty() }
       .map { it to fhirPathEngine.evaluate(resource, it.path) }
       .flatMap { pair -> pair.second.map { pair.first to it } }
+      .distinctBy { pair -> indexValues(pair) }
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:76]: why isn't this step after the index has been calculated below?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Comment by santosh-pingle** [comment]
@jingtang10 thanks!

Updated changes, please review once.

File: engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt [hunk 5]
```diff
@@ -1316,6 +1316,24 @@ class DatabaseImplTest {
...
+      database.search<Patient>(
+        Search(ResourceType.Patient)
+          .apply {
+            sort(Patient.GIVEN, Order.ASCENDING)
+            count = 100
+            from = 0
+          }
+          .getQuery()
+      )
+    assertThat(result.filter { it.id.contains("1401518") }).hasSize(1)
```
Comment (jingtang10) [inline engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt:1334]: can you do `it.id = something` rather than using `contains` (maybe you need to add `Patient/` or something?

unlikely to create flakey test in this example, but I'd really rather the logic in tests is always precise.

File: engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt [hunk 6]
```diff
@@ -1063,6 +1063,155 @@ class ResourceIndexerTest {
     assertThat(resourceIndices.stringIndices.any { it.name == "address" }).isFalse()
   }
 
+  @Test
+  fun index_duplicateString_deDuplicatesStringIndices() {
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt:1067]: supernit: deduplicate is one word. same below

```suggestion
  fun index_duplicateString_deduplicatesStringIndices() {
```

**Review by jingtang10 — APPROVED** [review]
Thanks @santosh-pingle! This way is much better! 🎉
