### PR TITLE
Handle local insert-delete sequence as no-op when squashing

### LINKED ISSUE #1951: Handle delete resource
**Describe the bug**
Handle delete resource :
1. If Resource is already deleted on server side
2. If Resource is deleted before uploading it. eg: Phone is offline, creates an Observation , adds it to the Provenance resource, Deletes the Observation. Now if referential integrity check on upload is on in the server, the upload will fail. 

**Component**
Core library

**To Reproduce**
Described above

**Expected behavior**
1. Handle with the appropriate result message
2. Do not squash the change? Not sure how FHIR servers handle insert followed by delete in the same transaction. 

**Would you like to work on the issue?**
No

cc: @aditya-07 @jingtang10

### PR DESCRIPTION
**Pull request by omarismail94**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1951, #2031 

**Description**
Clear and concise code change description. 

  *  Introduced a new Type.NO_OP to represent no-operation actions.
   *  Modified the mergeLocalChanges function to recognize a local insert followed by a delete, converting the sequence into a Type.NO_OP.
   *  Added error handling for unexpected usage of Type.NO_OP within the merge context.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

PR #2111

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt [hunk 1]
```diff
@@ -91,11 +93,12 @@ open class TransactionBundleGenerator(
     private fun putForCreateAndPatchForUpdateBasedBundleComponentMapper(
       type: Type,
       useETagForUpload: Boolean
-    ): BundleEntryComponentGenerator {
+    ): BundleEntryComponentGenerator? {
       return when (type) {
         Type.INSERT -> HttpPutForCreateEntryComponentGenerator(useETagForUpload)
         Type.UPDATE -> HttpPatchForUpdateEntryComponentGenerator(useETagForUpload)
         Type.DELETE -> HttpDeleteEntryComponentGenerator(useETagForUpload)
+        Type.NO_OP -> null
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt:101]: shouldn't this never happen?

so throw an exception? and keep the type non-null?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Comment by jingtang10** [comment]
thanks for this fix Omar! 👍🙏

File: engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt (hunk 1 above)
Comment (omarismail94) [reply engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt]: yes, you are right. updated the code to reflect that

**Review by jingtang10 — APPROVED** [review]
