### PR TITLE
Purge API implemented

### LINKED ISSUE #1472: Purge API implementation
**Describe the bug**
Problem with the current engine SDK design is if records are marked for deletion in the local database, these changes would be pushed to the server resulting in data loss.

Common scenarios	
CUJ 1: Purge all local data	
CUJ 2: Client initiated purge	
CUJ 3:  Server initiated purge

**Component**
Core library

**Expected behavior**
Engine SDK must provide API to support all 3 scenarios

**Related issues**
[856](https://github.com/google/android-fhir/issues/856)
[1178](https://github.com/google/android-fhir/issues/1178)

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1472 

**Description**
Purge API - purge(), clearDatabase() and getLocalChange() API implemented and test cases added for all API

**Alternative(s) considered**
Yes, details are mentioned in design doc

**Type**
Choose one: | Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/FhirEngine.kt [hunk 1]
```diff
@@ -72,6 +73,37 @@ interface FhirEngine {
...
+
+  /**
+   * Purge resource from database based on resource type and id without any deletion of data from
+   * the server.
+   * @param type
+   * - The [ResourceType]
+   * @param id
+   * - The resource id [Resource.id]
+   * @param isLocalPurge
+   * - default value is false here resource will not be deleted from LocalChangeEntity table but it
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/FhirEngine.kt:101]: formatting

File: engine/src/main/java/com/google/android/fhir/FhirEngine.kt [hunk 2]
```diff
@@ -72,6 +73,37 @@ interface FhirEngine {
...
+   * resource from database. Each resource will have at most one
+   * [LocalChangeEntity](multiple changes are squashed).
+   * @param type The [ResourceType]
+   * @param id The resource id [Resource.id]
+   * @return [LocalChangeEntity] A squashed local changes for given resource type and id.
+   */
+  suspend fun getLocalChange(type: ResourceType, id: String): LocalChangeEntity
+
+  /**
+   * Purge resource from database based on resource type and id without any deletion of data from
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/FhirEngine.kt:94]:
```suggestion
   * Purges a resource from the database based on resource type and id without any deletion of data from
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt [hunk 3]
```diff
@@ -222,6 +223,53 @@ internal class DatabaseImpl(
...
+   * @param id resource id [Resource.id]
+   * @returns [LocalChangeEntity] A squashed local changes for given resource type and id.
+   */
+  override suspend fun getLocalChange(type: ResourceType, id: String): LocalChangeEntity {
+    return db.withTransaction {
+      val localChangeEntityList =
+        localChangeDao.getLocalChanges(resourceType = type, resourceId = id)
+      if (localChangeEntityList.isEmpty()) {
+        throw ResourceNotFoundException(type.name, id)
+      }
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt:242]: this is a legitimate case where a resource does not have any local change. in this case just return an empty thing instead of throwing.

but you probably should throw if the resource itself actually doesn't exist.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt (hunk 3 above)
Comment (PallaviGanorkar) [reply engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt]: Done

File: engine/src/main/java/com/google/android/fhir/FhirEngine.kt [hunk 4]
```diff
@@ -72,6 +73,37 @@ interface FhirEngine {
 
   /** Returns the timestamp when data was last synchronized. */
   suspend fun getLastSyncTimeStamp(): OffsetDateTime?
+
+  /**
+   * Clears all database tables without resetting the auto-increment value generated by
+   * PrimaryKey.autoGenerate.
```
[the remark this answers is not in the document]
Comment (PallaviGanorkar) [reply engine/src/main/java/com/google/android/fhir/FhirEngine.kt:79]: Done

File: engine/src/main/java/com/google/android/fhir/FhirEngine.kt (hunk 2 above)
Comment (PallaviGanorkar) [reply engine/src/main/java/com/google/android/fhir/FhirEngine.kt]: Done

File: engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt [hunk 5]
```diff
@@ -67,6 +68,18 @@ internal class FhirEngineImpl(private val database: Database, private val contex
     return DatastoreUtil(context).readLastSyncTimestamp()
   }
 
+  override suspend fun clearDatabase() {
+    database.clearDatabase()
+  }
+
+  override suspend fun getLocalChange(type: ResourceType, id: String): LocalChangeEntity? {
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt:75]: i wonder if we should define a public local change data class, that encapsulates the local change entity class.

the local change entity class should be internal and for db layer only.... so if something happens in the future and we change our db implmementation, the public api which deveopers depend on will not be affected.

what do you think?

File: engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt [hunk 6]
```diff
@@ -194,6 +196,122 @@ class FhirEngineImplTest {
     testingUtils.assertResourceEquals(TEST_PATIENT_2, fhirEngine.get<Patient>(TEST_PATIENT_2_ID))
   }
 
+  @Test
+  fun getLocalChanges_withSingleLoaleChange_shouldReturnSingleLocalChanges() = runBlocking {
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt:200]: wonder if you can use the new kotlin test case names in reverse single quotes: https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt (hunk 6 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt]: done

File: engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt (hunk 5 above)
Comment (PallaviGanorkar) [reply engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt]: Yes , I agreed, there must be separation for hiding internal implementation as well as app developer should not be affected due internal changes

**Review by jingtang10 — APPROVED** [review]
move local change data class outside of db package.

**Comment by PallaviGanorkar** [comment]
> move local change data class outside of db package.

Done
