### PR TITLE
Disable leniency in DateFormat lib when converting date

### LINKED ISSUE #1638: Date picker validation accepts nonsensical answers
**Describe the bug**
I can type invalid dates into the Catalog app like `40/0/2` into the date picker with no validation error.

**Component**
SDC Library / Catalog

**To Reproduce**
1. Open a questionnaire with a datepicker, e.g. Catalog app which says it wants `M/d/yy`
2. Enter `40/0/2`

**Expected behavior**
Nonsense values should not pass validation

**Screenshots**

https://user-images.githubusercontent.com/7772901/192644308-f062952f-1c4a-40bc-bba6-6e8b50aff921.mp4

**Smartphone (please complete the following information):**
 - Device: Any

**Additional context**
`40/0/2` seems to translate to `4/2/05` if you tap the calendar icon?

### PR DESCRIPTION
**Pull request by omarismail94**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1638 

**Description**
By default, the [`DateFormat.parse`](https://developer.android.com/reference/java/text/DateFormat#parse(java.lang.String,%20java.text.ParsePosition)) method parsing is lenient: If the input is not in the form used by this object's format method but can still be parsed as a date, then the parse succeeds.

So in the case of `40/0/2`, with leniency set to true, it would convert this to `March 31, 5`. Not 2005. 05. FIVE! Mind blowing haha. I didnt dig into the implementation, but I assume it does `2 + 40//12 = 5` for the year, and then the remainder becomes the month and day.

**Alternative(s) considered**

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**
Date Time picker now throws validation error when typing `40/0/5`

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt [hunk 1]
```diff
@@ -134,6 +135,24 @@ class QuestionnaireItemDatePickerViewHolderFactoryEspressoTest {
     assertThat(validationResult).isEqualTo(Valid)
   }
 
+  @Test
+  fun shouldSetDateInput_invalid_date_entry() {
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt:139]: can you add another one with 5-digit year?

Comment (jingtang10) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt:139]: can you rename this test to be explicit about what this is testing?

I feel like in "40/0/2" there are actually 3 oddities - the month, day, and year are all unexpected and potentially invalid. So it would be good to separate them. For example, I'd like "40/5/2022", "12/0/2022" and "12/5/2022" as 3 different test cases so that you really cover everything.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt (hunk 1 above)
Comment (omarismail94) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt]: Added!

**Review by jingtang10 — APPROVED** [review]
thanks omar!
