### PR TITLE
Fix for removing old indexes when resource is updated

### LINKED ISSUE #1825: Old and outdated resource indexes still present in the database
**Describe the bug**
FHIR Engine search results sometimes returns outdated results because old indexes are not deleted

**Component**
Core library

**To Reproduce**
1. Select a resource to test with by it's ID and resourceUuid from the database
2. Write code to fetch and call `fhirEngine.update` on the same resource
3. Check the  `DateTimeIndexEntity` table using Android Studio app inspection for the `_lastUpdated` indexes for the specific resource
4. You'll realize that there are multiple indexes for the same property

**Expected behavior**

Inspecting the database should show only a single record for the resource's `_lastUpdated` index. This should be the latest index

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Nexus 5X API 28 emulator
 - Android version: 9
 - Build number: PSR1.180720.117
 - Version 28

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1825

**Description**
Issue: Updating resource via `FhirEngine.update ` api doesn't delete previous indexes.

Solution: In the database, for the `ResourceEntity` do `Insert` instead of `Update` as it results in the Deletion of old `ResourceEntity` (based on ConflictStrategy) that causes of its `IndexEntities` to get deleted as well based on their `ForeignKey` constrain.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

The other approach is to have a `Unique Index` for each IndexEntity that will Delete it based on the `insert*Index`'s `OnConflictStrategy`. 

Proposed solution is inline with how we handle updates for remote updates.

**Type**
Choose one: Bug fix
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt [hunk 1]
```diff
@@ -51,22 +51,9 @@ internal abstract class ResourceDao {
...
-          id = 0,
-          resourceType = resource.resourceType,
-          resourceUuid = it.resourceUuid,
-          resourceId = resource.logicalId,
-          serializedResource = iParser.encodeResourceToString(resource),
-          versionId = it.versionId,
-          lastUpdatedRemote = it.lastUpdatedRemote
-        )
+      val entity = it.copy(serializedResource = iParser.encodeResourceToString(resource))
+      insertResource(entity)
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:56]: can you comment on the fact that we can do this because we have the conflict resolution strategy of replace in the resoure table?

**Review by jingtang10 — APPROVED** [review]
Thanks for fixing this!

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt (hunk 1 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:61]: Done
