### PR TITLE
Change areItemsTheSame to check if internal objects are the same with ===

### LINKED ISSUE #765: Reselecting the single answer option initially set in questionnaire.item.initial disables nested answer options at the second level
**Describe the bug**
When using a questionnaire with three levels of nesting, if the top most question has a single answer which is already selected, then re-selecting that answer disables the third level of nesting permanently.

**Component**SDC library

**To Reproduce**
1. Use the questionnaire that is in this issue
2. Select the first answer in the drop down for the question number 1
3. You will see that on selecting the Ward i.e. the next question, the third question does not get displayed

**Expected behavior**
The third question must be enabled and displayed based on the answer of the second question.

**Screenshots**
singleAnswerBug

**Smartphone (please complete the following information):**
 -  Pixel4a emulator
 - Android version: 10
 - 29

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by joiskash**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #765 

**Description**
If you have a questionnaire with multiple levels of nesting, questionnaire response items are nested within answers. When the parent answer is changed, we clear the questionnaireResponseItem.answer list and add the new answer to it. The nested questionnaireResponseItems also get cleared and new instances of them are created in the questionnaireResponseItemChangedCallback. Since questionnaireItemViewItem.questionnaireResponseItem was a value , the ViewHolderFactory would always hold the reference to the old nested questionnaireResponseItem. On making it a variable, the viewHolderFactory now gets the reference of the correct questionnaireResponseitem while setting the answer.  This allows enable when to work properly and thus displays the third nested answer too.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by jingtang10** [comment]
Thanks Kashyap for fixing this. First thought is that we should write some tests to cover this case. Upon second thought I'm not entirely sure why this would be the fix anyway - it seems like if `val` vs `var` can fix this issue there's probably an underlying problem which is the items are not being replaced/deleted/cached correctly.

**Comment by joiskash** [comment]
> Thanks Kashyap for fixing this. First thought is that we should write some tests to cover this case. Upon second thought I'm not entirely sure why this would be the fix anyway - it seems like if `val` vs `var` can fix this issue there's probably an underlying problem which is the items are not being replaced/deleted/cached correctly.

Sure , ill write a UT first.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 1]
```diff
@@ -107,4 +107,22 @@ data class QuestionnaireItemViewItem(
...
+   * [questionnaireResponseItem] that are bound to the view. Whenever there is a change made to the
+   * [questionnaireResponseItem] via UI, a new list of QuestionnaireItemViewItems is created that
+   * holds a reference to the updated [questionnaireResponseItem]. It is important to note that
+   * [questionnaireResponseItem]s are nested in the parent
+   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent], so when a parent answer is
+   * changed, the nested items are cleared and need to be answered again. This new updated list with
+   * references to new nested [questionnaireResponseItem]s is passed to the adapter, which goes onto
+   * perform a Diff before updating the view. While checking if two [QuestionnaireItemViewItem]s are
+   * equal or not, we need to check if they are referencing the same objects.
+   */
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:122]:
```suggestion
  /**
   * [QuestionnaireItemViewItem] is a transient object for the UI only. Whenever the user makes any change
   * via the UI, a new list of [QuestionnaireItemViewItem]s will be created, each holding references to the
   * underlying [QuestionnaireItem] and [QuestionnaireResponseItem]. To avoid refreshing the UI 
   * unnecessarily with the same [QuestionnaireItem]s and [QuestionnaireResponseItem]s,  we consider two
   * [QuestionnaireItemViewItem]s to be the same if they have the same underlying [QuestionnaireItem] and
   * [QuestionnaireResponseItem]. See [QuestionnaireItemAdapter.DiffCallback].
   * 
   * On the other hand, under certain circumstances, the underlying [QuestionnaireResponseItem] might be 
   * recreated for the same question. For example, if a [QuestionnaireItem] is nested under another 
   * [QuestionnaireItem], the [QuestionnaireResponseItem](s) will be nested under the parent 
   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent]. and if the 
   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent] is changed, the nested 
   * [QuestionnaireResponseItem] will be recreated, too. In such cases, it would be incorrect
   * to simply check that the `linkId` of the underlying [QuestionnaireItem] and 
   * [QuestionnaireResponseItem] match.
   */
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 2]
```diff
@@ -107,4 +107,22 @@ data class QuestionnaireItemViewItem(
...
+  override fun equals(other: Any?): Boolean {
+    return this.questionnaireItem === (other as QuestionnaireItemViewItem).questionnaireItem &&
+      this.questionnaireResponseItem ===
+        (other as QuestionnaireItemViewItem).questionnaireResponseItem
+  }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:127]: add another function `equalsDeep` to handle the `areContentsTheSame` functino of the `DiffCallback`.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 3]
```diff
@@ -107,4 +107,22 @@ data class QuestionnaireItemViewItem(
...
+   * [questionnaireResponseItem] via UI, a new list of QuestionnaireItemViewItems is created that
+   * holds a reference to the updated [questionnaireResponseItem]. It is important to note that
+   * [questionnaireResponseItem]s are nested in the parent
+   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent], so when a parent answer is
+   * changed, the nested items are cleared and need to be answered again. This new updated list with
+   * references to new nested [questionnaireResponseItem]s is passed to the adapter, which goes onto
+   * perform a Diff before updating the view. While checking if two [QuestionnaireItemViewItem]s are
+   * equal or not, we need to check if they are referencing the same objects.
+   */
+  override fun equals(other: Any?): Boolean {
```
[the remark this answers is not in the document]
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:129]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt (hunk 2 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:148]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 4]
```diff
@@ -107,4 +107,43 @@ data class QuestionnaireItemViewItem(
...
+   * might be recreated for the same question. For example, if a [QuestionnaireItem] is nested under
+   * another [QuestionnaireItem], the [QuestionnaireResponseItem](s) will be nested under the parent
+   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent]. and if the
+   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent] is changed, the nested
+   * [QuestionnaireResponseItem] will be recreated, too. In such cases, it would be incorrect to
+   * simply check that the `linkId` of the underlying [QuestionnaireItem] and
+   * [QuestionnaireResponseItem] match.
+   */
+  override fun equals(other: Any?): Boolean {
+    return if (other is QuestionnaireItemViewItem) {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:130]: turn this if condition around and return early.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 5]
```diff
@@ -107,4 +107,43 @@ data class QuestionnaireItemViewItem(
...
+   * references to the underlying [QuestionnaireItem] and [QuestionnaireResponseItem]. To avoid
+   * refreshing the UI unnecessarily with the same [QuestionnaireItem]s and
+   * [QuestionnaireResponseItem]s, we consider two [QuestionnaireItemViewItem]s to be the same if
+   * they have the same underlying [QuestionnaireItem] and [QuestionnaireResponseItem]. See
+   * [QuestionnaireItemAdapter.DiffCallback].
+   *
+   * On the other hand, under certain circumstances, the underlying [QuestionnaireResponseItem]
+   * might be recreated for the same question. For example, if a [QuestionnaireItem] is nested under
+   * another [QuestionnaireItem], the [QuestionnaireResponseItem](s) will be nested under the parent
+   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent]. and if the
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:123]:
```suggestion
   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent], and if the
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 6]
```diff
@@ -107,4 +107,43 @@ data class QuestionnaireItemViewItem(
...
+      false
+    }
+  }
+
+  /**
+   * Comparing the contents of two [QuestionnaireItemViewItem]s,involves traversing the underlying
+   * [Questionnaire.QuestionnaireItemComponent] and
+   * [QuestionnaireResponse.QuestionnaireResponseItemComponent],and comparing values of all the
+   * properties. This is done by using the [Questionnaire.QuestionnaireItemComponent.equalsDeep] and
+   * [QuestionnaireResponse.QuestionnaireResponseItemComponent.equalsDeep] functions
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:143]:
```suggestion
   * Comparing the contents of two [QuestionnaireItemViewItem]s by traversing the underlying
   * [Questionnaire.QuestionnaireItemComponent] and
   * [QuestionnaireResponse.QuestionnaireResponseItemComponent] and comparing values of all the
   * properties. This is done by using [Questionnaire.QuestionnaireItemComponent.equalsDeep] and
   * [QuestionnaireResponse.QuestionnaireResponseItemComponent.equalsDeep].
```

**Review by jingtang10 — APPROVED** [review]
Thanks @joiskash again for debugging fixing this very thorning issue!

Just a few nits! Please feel free to merge once these are addressed.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt (hunk 4 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt (hunk 5 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt (hunk 6 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 7]
```diff
@@ -107,4 +107,43 @@ data class QuestionnaireItemViewItem(
...
+   * simply check that the `linkId` of the underlying [QuestionnaireItem] and
+   * [QuestionnaireResponseItem] match.
+   */
+  override fun equals(other: Any?): Boolean {
+    return if (other !is QuestionnaireItemViewItem) {
+      false
+    } else {
+      this.questionnaireItem === other.questionnaireItem &&
+        this.questionnaireResponseItem === other.questionnaireResponseItem
+    }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:135]:
```suggestion
    if (other !is QuestionnaireItemViewItem) return false
    return this.questionnaireItem === other.questionnaireItem &&
        this.questionnaireResponseItem === other.questionnaireResponseItem
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Review by jingtang10 — APPROVED** [review]
