### PR TITLE
Do not show soft keyboard on patient details card if it is opened on previous screen.

### LINKED ISSUE #861: Soft keyboard stays opened on screen in reference app.
**Describe the bug**
When Edittext box get clicked on screen such as patient list, create patient, edit patient screen, then soft keyboard get opened but once operation is done, then it still stays on screen.

**Component**
reference app, or SDC gallery app

**To Reproduce**
1. Open reference app.
2. Click on search box
3. Give input to search patient, 
4. Click on search icon on soft keyboard.
5. Keyboard still stay open.
4. Click on patient record, it launch patient edit screen.
5. It still shows keyboard.

**Expected behavior**
Keyboard should be hidden once operation is done.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?*
Screen Shot 2021-10-25 at 5 08 27 PM
*
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #861 

**Description**
If soft keyboard opened on Add, Edit, Screener and Search screen and user navigate to Patient details card, then 
keyboard stays opened on details screen.

Therefore once action is complete on Add, Edit, Search patient and screener screen, just hide/close the soft keyboard so that it will not be shown on details screen.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**
Before 
Screen Shot 2021-11-01 at 3 16 07 PM

After fix
Screen Shot 2021-11-01 at 3 16 34 PM

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: reference/src/main/java/com/google/android/fhir/reference/util/Util.kt [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import android.app.Activity
+import android.content.Context
+import android.view.inputmethod.InputMethodManager
+
+/**
+ * Hides soft keyboard.
+ *
+ * @param activity current activity
+ */
+inline fun hideSoftKeyboard(activity: Activity?) {
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/util/Util.kt:28]: can you change this into an extension function?

`inline fun Activity.hideSoftKeyboard`

File: reference/src/main/java/com/google/android/fhir/reference/util/Util.kt [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+  activity?.currentFocus?.let { view ->
+    view.clearFocus()
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/util/Util.kt:30]:
```suggestion
    // Clear focus to avoid showing soft keyboard again if activity is launched again 
    view.clearFocus()
```

File: reference/src/main/java/com/google/android/fhir/reference/util/Util.kt [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    val imm = activity?.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
+    imm.hideSoftInputFromWindow(view.windowToken, 0)
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/util/Util.kt:32]:
```suggestion
    (activity.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager).hideSoftInputFromWindow(view.windowToken, 0)
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]
What if you click the back button on the questionnaire screen without submitting the questionnaire? have you tested this case?

**Comment by jingtang10** [comment]
> What if you click the back button on the questionnaire screen without submitting the questionnaire? have you tested this case?

maybe try to do this in `onPause`?

**Comment by santosh-pingle** [comment]
looking into the review comments.

**Comment by santosh-pingle** [comment]
> > What if you click the back button on the questionnaire screen without submitting the questionnaire? have you tested this case?
> 
> maybe try to do this in `onPause`?

Done.

**Review by jingtang10 — COMMENTED** [review]
https://stackoverflow.com/questions/10627137/how-can-i-know-when-an-edittext-loses-focus

can you please try putting this logic in the data capture library (in the `views` package in the specific widgets), e.g.:

```
    textInputEditText.setOnFocusChangeListener {view, focused ->
      if (!focused) {
        // hide soft keyboard
        view.context.applicationContext.getSystemService()...
      }
    }
```

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt [hunk 4]
```diff
@@ -104,6 +105,7 @@ class PatientListFragment : Fragment() {
 
         override fun onQueryTextSubmit(query: String): Boolean {
           patientListViewModel.searchPatientsByName(query)
+          activity?.hideSoftKeyboard()
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt:108]: do you stil need this change?

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt [hunk 5]
```diff
@@ -158,11 +160,13 @@ class PatientListFragment : Fragment() {
   }
 
   private fun onPatientItemClicked(patientItem: PatientListViewModel.PatientItem) {
+    activity?.hideSoftKeyboard()
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt:163]: do you stil need this change?

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt [hunk 6]
```diff
@@ -158,11 +160,13 @@ class PatientListFragment : Fragment() {
...
     findNavController()
       .navigate(PatientListFragmentDirections.navigateToProductDetail(patientItem.resourceId))
   }
 
   private fun onAddPatientClick() {
+    activity?.hideSoftKeyboard()
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt:169]: do you stil need this change?

File: reference/src/main/java/com/google/android/fhir/reference/util/Util.kt [hunk 7]
```diff
@@ -0,0 +1,33 @@
+/*
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/util/Util.kt:1]: i don't think it's appropriate to still place this file in the `reference` module

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt (hunk 4 above)
Comment (santosh-pingle) [reply reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt]: Instead of this change below code snippet is added
```
searchView.setOnQueryTextFocusChangeListener { view, focused ->
      if (!focused) { ...
```

It is required here, as patient list fragment has searchview view which is part of reference app only.
If we do not add above code snippet then soft keyboard get shown on next page if it is already open on patient list screen.

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt (hunk 5 above)
Comment (santosh-pingle) [reply reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt]: same here.

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt (hunk 6 above)
Comment (santosh-pingle) [reply reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt]: same here

**Review by jingtang10 — APPROVED** [review]
Well done!

File: reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt [hunk 8]
```diff
@@ -108,6 +110,13 @@ class PatientListFragment : Fragment() {
         }
       }
     )
+    searchView.setOnQueryTextFocusChangeListener { view, focused ->
+      if (!focused) {
+        // hide soft keyboard
+        (activity?.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt:116]:
```suggestion
        (requireActivity().getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
```
