### PR TITLE
In paginated layout extra display text is shown at the top.

### LINKED ISSUE #1291: Extra blank space get added below question text if subtitle text is not present.
**Describe the bug**
There is extra blank space in between questionnaire text and answer options if subtitle text is not present.

Note : (We are able to reproduce this issue, as we have not added subtitle text in questionnaire json for default and paginated layout yet.)

**Component**
SDC library

**To Reproduce**
1. Open catalog app.
2. Click on layouts
3. Click on default 
4. See subtitle text are not present in default layout, it causes extra space in between question text and answer options.

**Expected behavior**
If subtitle text is not present then extra space should not be added in between question text and answer options.

**Screenshots**

Screen Shot 2022-04-14 at 11 21 19 AM

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1291 

**Description**
`QuestionnaireItemGroupViewHolderFactory` view binding code is moved to the `QuestionnaireItemHeaderView` as result `localizedHintSpanned` is called on group item and returns text if it has nested display item.
Just return null if localizedHintSpanned get called on group type item.

It also shows extra space in paginated layout for group type.
If question text is empty or null make question textview visibility gone.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

Before
Screen Shot 2022-04-20 at 9 17 07 AM

After
Screen Shot 2022-04-20 at 12 59 11 PM

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by aditya-07 — APPROVED** [review]
LGTM

File: datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt [hunk 1]
```diff
@@ -146,7 +146,8 @@ internal val Questionnaire.QuestionnaireItemComponent.localizedHintSpanned: Span
     item
       .firstOrNull { questionnaireItem ->
         questionnaireItem.type == Questionnaire.QuestionnaireItemType.DISPLAY &&
-          questionnaireItem.displayItemControl == null
+          questionnaireItem.displayItemControl == null &&
+          type != Questionnaire.QuestionnaireItemType.GROUP
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt:150]: this check should be at the beginning of this function... because it's nothing to do with the item.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt [hunk 2]
```diff
@@ -49,7 +49,16 @@ internal class QuestionnaireItemHeaderView(context: Context, attrs: AttributeSet
...
     }
-    question.text = questionnaireItem.localizedTextSpanned
+
+    questionnaireItem.localizedTextSpanned.let {
+      if (!it.isNullOrEmpty()) {
+        question.visibility = View.VISIBLE
+        question.text = it
+      } else {
+        question.visibility = View.GONE
+      }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt:59]: while we are here, can we change all of these to something a bit more readable:

```
question.visibility = if (it.isNullOrEmpty()) { View.VISIBLE } else { View.GONE }
question.text = it
// or maybe question.text = it ?: ""
```

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt:59]: do this for the prefix, text, and the hint

File: datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt [hunk 3]
```diff
@@ -340,6 +340,23 @@ class MoreQuestionnaireItemComponentsTest {
     assertThat(questionItemList.first().localizedHintSpanned).isNull()
   }
 
+  @Test
+  fun localizedHintSpanned_groupType_shouldReturnNull() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt:344]: great test case!

Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt:344]: can you add a test case in the group wigdet as well?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Review by jingtang10 — APPROVED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt [hunk 4]
```diff
@@ -41,22 +41,28 @@ internal class QuestionnaireItemHeaderView(context: Context, attrs: AttributeSet
   private var hint: TextView = findViewById(R.id.hint)
 
   fun bind(questionnaireItem: Questionnaire.QuestionnaireItemComponent) {
-    questionnaireItem.localizedPrefixSpanned.let {
-      if (!it.isNullOrEmpty()) {
-        prefix.visibility = View.VISIBLE
-        prefix.text = it
+    prefix.visibility =
+      if (questionnaireItem.localizedPrefixSpanned.isNullOrEmpty()) {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt:45]: actually can you extract `questionnaireItem.localizedPrefixSpanned` as a variable?
same with below
