### PR TITLE
Start saving local lastUpdated to resources for search operations.

### LINKED ISSUE #1956: Modified Date is needed as sorting parameter for all FHIR resources
**Describe the bug**
Currently while querying resources from SDC , sort() method is available which can be used to get sorted data specially while we want to query resources with pagination, but currently modified date is stored only in meta data , not available for sort method parameter.

**Component**
Engine library

**To Reproduce**
1. Go to PatientListViewModel file in demo app
2. check getSearchResults method to get Patient resource list
3. sort(Patient.GIVEN, Order.ASCENDING) method is used in that method which is available at query level sorting
4. But when you check other available sorting parameters for Patient as GIVEN, Modified date can not be found which is needed in some cases for example,  while we want to fetch last modified patients at top!
5. Same applies on all the resources

**Expected behavior**
For sort(Patient.GIVEN, Order.ASCENDING),  Modified date should be available as well,

@jingtang10

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1956 

**Description**
1. Save local last updated date of resources in a new column in ResourceEntity.
2. Add local last updated value as a custom DateTimeIndex value to allow search operations. 

TODO: 
Add tests. 
**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt [hunk 1]
```diff
@@ -46,14 +47,10 @@ internal abstract class LocalChangeDao {
...
-  open suspend fun addInsertAll(resources: List<Resource>) {
-    resources.forEach { resource -> addInsert(resource) }
-  }
-
-  suspend fun addInsert(resource: Resource) {
+  open suspend fun addInsert(resource: Resource, timeOfChange: Instant?) {
     val resourceId = resource.logicalId
     val resourceType = resource.resourceType
-    val timestamp = Date().toTimeZoneString()
+    val timestamp = Date.from(timeOfChange).toTimeZoneString()
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt:53]: AFAIK, we can we just making it human readable and not using it anywhere. We could save it as an `Instant` but some complex migration would be required as SQLite's Alter Table command is not extensive.

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt [hunk 2]
```diff
@@ -46,14 +47,10 @@ internal abstract class LocalChangeDao {
   @Insert abstract suspend fun addLocalChange(localChangeEntity: LocalChangeEntity)
 
   @Transaction
-  open suspend fun addInsertAll(resources: List<Resource>) {
-    resources.forEach { resource -> addInsert(resource) }
-  }
-
-  suspend fun addInsert(resource: Resource) {
+  open suspend fun addInsert(resource: Resource, timeOfChange: Instant?) {
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt]: Yes, It should have been non nullable. Change done.

[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt]: Since the class has Local in the name, don't think Local is super required in the function args name as well. But change done anyways.

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt [hunk 3]
```diff
@@ -69,13 +66,13 @@ internal abstract class LocalChangeDao {
     )
   }
 
-  suspend fun addUpdate(oldEntity: ResourceEntity, resource: Resource) {
+  suspend fun addUpdate(oldEntity: ResourceEntity, resource: Resource, timeOfChange: Instant) {
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt]: Since the class has Local in the name, don't think Local is super required in the function args name as well. But change done anyways.

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt [hunk 4]
```diff
@@ -168,18 +202,30 @@ internal abstract class ResourceDao {
...
+        }
+        .build()
+
+    updateIndicesForResource(index, resource.resourceType, resourceUuid)
 
     return resource.id
   }
 
-  private suspend fun updateIndicesForResource(
+  suspend fun updateIndicesForResource(
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt]: Done.  Refactored some code in `DatabaseImpl` to make it possible.

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndices.kt [hunk 5]
```diff
@@ -57,6 +57,18 @@ internal data class ResourceIndices(
     private val numberIndices = mutableListOf<NumberIndex>()
     private val positionIndices = mutableListOf<PositionIndex>()
 
+    constructor(indices: ResourceIndices) : this(indices.resourceType, indices.resourceId) {
+      stringIndices += indices.stringIndices
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndices.kt:61]: plusAssign `+=` feels more kotlin-y

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt (hunk 1 above)
[the remark this answers is not in the document]
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt]: Planning to do it in a separate PR.

File: engine/src/main/java/com/google/android/fhir/db/Database.kt [hunk 6]
```diff
@@ -145,4 +147,11 @@ internal interface Database {
    * delete resource entry from LocalChangeEntity table.
    */
   suspend fun purge(type: ResourceType, id: String, forcePurge: Boolean = false)
+
+  /** @return DateTimeIndexEntities for the resource. */
+  @VisibleForTesting
+  suspend fun getDateTimeIndexEntities(
```
Comment (omarismail94) [inline engine/src/main/java/com/google/android/fhir/db/Database.kt:153]: do we need this API? It seems like we are only using it in FhirEngineImplTest to verify the index exists in the index map, and to see if it changes when we do updates. Is it possible to use `getLocalChanges`, or any of the existing APIs for the same result.

I think this works in the tests where we want the timestampt:
```
services.database.getLocalChange(ResourceType.Patient, "patient-id-update")
      ?.localChange?.timestamp
```

File: engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt [hunk 7]
```diff
@@ -274,6 +280,12 @@ internal class DatabaseImpl(
     }
   }
 
+  override suspend fun getDateTimeIndexEntities(resourceId: String, resourceType: ResourceType) =
```
Comment (omarismail94) [inline engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt:283]: see comment in Database interface about getting rid of this

File: engine/src/main/java/com/google/android/fhir/db/Database.kt (hunk 6 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/Database.kt:153]: I am adding a custom client side index here. And there seems to be no available way to check if it is added or not.

Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/Database.kt]: done.

File: engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt (hunk 7 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt]: Done

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt [hunk 8]
```diff
@@ -152,7 +172,18 @@ internal abstract class ResourceDao {
 
   @RawQuery abstract suspend fun countResources(query: SupportSQLiteQuery): Long
 
-  private suspend fun insertResource(resource: Resource): String {
+  suspend fun insertResourceLocal(resource: Resource, timeOfChange: Instant) =
+    insertResource(resource, timeOfChange)
+
+  // Since the insert removes any old indexes and lastUpdatedLocal (data not contained in resource
+  // itself), we extract the lastUpdatedLocal if any and then set it back again.
+  private suspend fun insertResourceRemote(resource: Resource) =
```
Comment (omarismail94) [inline engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:180]: can we update this to:
```suggestion
  private suspend fun insertRemoteResource(resource: Resource) =
```

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt [hunk 9]
```diff
@@ -152,7 +172,18 @@ internal abstract class ResourceDao {
 
   @RawQuery abstract suspend fun countResources(query: SupportSQLiteQuery): Long
 
-  private suspend fun insertResource(resource: Resource): String {
+  suspend fun insertResourceLocal(resource: Resource, timeOfChange: Instant) =
```
Comment (omarismail94) [inline engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt:175]: can we rename to this:
```suggestion
  suspend fun insertLocalResource(resource: Resource, timeOfChange: Instant) =
```

**Review by omarismail94 — APPROVED** [review]
Superb change! 🚀

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt (hunk 8 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt]: Done

File: engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt (hunk 9 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt]: Done
