### PR TITLE
Evaluate enable when with newly created repeated groups

### LINKED ISSUE #2590: Repeated Group: Anomalous behaviour of enableWhen expressions in a repeated group
**Describe the bug**
The `enableWhen` expression condition cascades to other group items below or above the trigger group item. 

**Component**
SDC library

**To Reproduce**
Steps to reproduce the behaviour:
1. Define a repeated group with several items e.g. choice and date fields. 
2. Add an enableWhen expression for showing/hiding a field based on a choice selection (condition). 
3. When the app runs, add items in the UI and click the option(s) tied to the enableWhen expression. 
4. See that multiple fields are affected by the choice selection.

**Expected behaviour**
For an enableWhen expression condition that affects a single field should not cascade to other fields. 

**Screenshots**

https://github.com/google/android-fhir/assets/16164649/cef11fa5-2769-4207-b875-53e62e129fe8

**Smartphone (please complete the following information):**

 
**Additional context**
In the video shared above, there are two fields, a choice option, and a date field. 
The date field only shows if the choice is option A. 
Selecting option A shows all date fields and selecting any other option hides it.  

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2590

**Description**
Reinitialize the enablement evaluator when the questionnaire response tree changes (i.e. repeated groups or items with nested questions are added or removed). This makes sure the pre-order list and parent tree are recreated to reflect the new tree structure of the questionnaire response, and that the question referenced in the enable when can be identified correctly.

**Alternative(s) considered**
I asked this question in FHIR chat https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/parent.28.29.20or.20siblings.28.29.3F and Paul and Brian suggested that we could use a variable defined at the parent of the repeated group. If this works in our case still needs to be verified.

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt [hunk 1]
```diff
@@ -883,8 +883,8 @@ internal inline fun <T> groupByAndZipByLinkId(
  *
  * For background, see https://build.fhir.org/questionnaireresponse.html#link.
  */
-internal val Questionnaire.QuestionnaireItemComponent.shouldHaveNestedItemsUnderAnswers: Boolean
-  get() = item.isNotEmpty() && (type != Questionnaire.QuestionnaireItemType.GROUP || !repeats)
+internal val QuestionnaireItemComponent.shouldHaveNestedItemsUnderAnswers: Boolean
+  get() = item.isNotEmpty() && (type != Questionnaire.QuestionnaireItemType.GROUP || repeats)
```
Comment (santosh-pingle) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt:887]: ok.

**Review by santosh-pingle — APPROVED** [review]
thanks Jing.
LGTM!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt (hunk 1 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt:887]: thanks for catching this! this is an intentional change because the logic here is clearly wrong and doesn't fit the name and description fo the function. however i'm slightly disappointed this has not caused any test failure - i'll think about how to add tests to make the behavior locked down.

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt:887]: i added some tests to lock this behaviour
