### PR TITLE
Set values to date and time widget if answer already present

### LINKED ISSUE #649: If the date has an initial answer, then opening the widget selects todays date as default instead of the initial date
**Describe the bug**
If the date has an initial answer, then opening the widget selects today's date as default instead of the initial date

**Component**
SDC library

**To Reproduce**
1. Use sample questionnaire with a date type item with an initial value
2. Press the date widget
3. Selected date will be "today" instead of the initial value.

**Expected behavior**
If an answer already exists then that date should be the default value selected in the calendar.

**Screenshots**

[video](https://user-images.githubusercontent.com/48797364/125742855-9d4a87b9-3865-43d5-8a1a-efbdf417e547.mp4)

**Smartphone (please complete the following information):**
 - Device: One plus 7t pro
 - Android version: 11
 - Build number: Running Lineage OS 18.1

### PR DESCRIPTION
**Pull request by joiskash**
Set values to date and time widget if answer already present.This pevents the date/ time widget to always open with the default date/time

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #649 

**Description**
If the questionnaire.item has an initial answer or the questionnaireResponse.item has an answer for the date time question, then on opening the widget, the highlighted date/ selected time is always set to today/now respectively. This is confusing to the user, since the expected behavior is that if an answer is already present, then that should be the date/time highlighted/selected in the widget.
To handle this, I am passing the date/ time if any from the `questionnaireItemViewItem.singleAnswerOrNull` to the DatePicker and TimePicker fragments as arguments

**Alternative(s) considered**
Nope

**Type**
Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt [hunk 1]
```diff
@@ -30,8 +30,10 @@ internal class DatePickerFragment : DialogFragment(), DatePickerDialog.OnDateSet
   @SuppressLint("NewApi") // Suppress warnings for java.time APIs
   override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
     // Use the current date as the default date in the picker
-    val today = LocalDate.now()
-
+    var today = LocalDate.now()
+    if (this.arguments?.get("date") != null) {
+      today = (this.arguments?.get("date") as LocalDate)
+    }
```
Comment (epicadk) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt:36]: will this not work?

```suggestion
    val today =  (this.arguments?.get("date") as? LocalDate) ?: LocalDate.now()
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt [hunk 2]
```diff
@@ -30,7 +30,10 @@ internal class TimePickerFragment : DialogFragment(), TimePickerDialog.OnTimeSet
   @SuppressLint("NewApi") // Suppress warnings for java.time APIs
   override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
     // Use the current time as the default time in the picker
-    val now = LocalTime.now()
+    var now = LocalTime.now()
```
Comment (epicadk) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt:33]: same as above

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt (hunk 1 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt:36]: yup it should work, and looks much neater too! thanks ill make the change

Comment (epicadk) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt]: Sorry, you probably won't need the brackets either.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt [hunk 3]
```diff
@@ -30,7 +30,7 @@ internal class DatePickerFragment : DialogFragment(), DatePickerDialog.OnDateSet
   @SuppressLint("NewApi") // Suppress warnings for java.time APIs
   override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
     // Use the current date as the default date in the picker
-    val today = LocalDate.now()
+    val today = this.arguments?.get("date") as? LocalDate ?: LocalDate.now()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt:33]: `"date"` needs to be extracted as a string constant to be used consistently

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 4]
```diff
@@ -100,7 +101,24 @@ internal object QuestionnaireItemDatePickerViewHolderFactory :
...
+                  LocalDate.of(
+                    year,
+                    month + 1,
+                    day,
+                  )
+                }
+              }
+            }
+          val dateFragment = DatePickerFragment()
+          dateFragment.arguments = bundleOf("date" to selectedDate)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:118]: here you need to reference the string const instead of hardcoding the value `"date"`

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 5]
```diff
@@ -89,7 +92,24 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
+              questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.month?.let { month ->
+                questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.day?.let { day ->
+                  LocalDate.of(
+                    year,
+                    month + 1,
+                    day,
+                  )
+                }
+              }
+            }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:107]: i think this can be improved. this 3 nested levels of seems a little redundant... what about

```
val selectedDate =
            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.let {
              LocalDate.of(
                it.year,
                it.month + 1,
                it.day,
              )
            }
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 6]
```diff
@@ -119,7 +139,26 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
             // Clear focus so that the user can refocus to open the dialog
             timeInputEditText.clearFocus()
           }
-          TimePickerFragment().show(context.supportFragmentManager, TimePickerFragment.TAG)
+
+          val selectedTime =
+            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.hour?.let { hour ->
+              questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.minute?.let { minute
+                ->
+                questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.second?.let {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:147]: same here

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt [hunk 7]
```diff
@@ -30,7 +30,8 @@ internal class TimePickerFragment : DialogFragment(), TimePickerDialog.OnTimeSet
   @SuppressLint("NewApi") // Suppress warnings for java.time APIs
   override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
     // Use the current time as the default time in the picker
-    val now = LocalTime.now()
+    val now = this.arguments?.get("time") as? LocalTime ?: LocalTime.now()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt:33]: same thing with the string

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 8]
```diff
@@ -100,7 +101,24 @@ internal object QuestionnaireItemDatePickerViewHolderFactory :
               }
             }
           )
-          DatePickerFragment().show(context.supportFragmentManager, DatePickerFragment.TAG)
+
+          val selectedDate =
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:105]: see below comment in the date time picker

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt (hunk 3 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt (hunk 4 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 5 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 6 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt (hunk 7 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt (hunk 8 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:106]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 9]
```diff
@@ -100,7 +102,20 @@ internal object QuestionnaireItemDatePickerViewHolderFactory :
...
+            questionnaireItemViewItem.singleAnswerOrNull?.valueDateType?.let {
+              LocalDate.of(
+                it.year,
+                it.month + 1,
+                it.day,
+              )
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:112]: add a private extension function:

```
private val DateType.localDate = ...
```

and do the same for the DateTime picker below

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 10]
```diff
@@ -89,7 +94,20 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
           }
-          DatePickerFragment().show(context.supportFragmentManager, DatePickerFragment.TAG)
+
+          val selectedDate =
+            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.let {
+              LocalDate.of(
+                it.year,
+                it.month + 1,
+                it.day,
+              )
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:104]:
```
private val DateTimeType.localDate = ...
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 11]
```diff
@@ -119,7 +137,20 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
           }
-          TimePickerFragment().show(context.supportFragmentManager, TimePickerFragment.TAG)
+
+          val selectedTime =
+            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.let {
+              LocalTime.of(
+                it.hour,
+                it.minute,
+                it.second,
+              )
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:147]:
```
private val DateTimeType.localTime = ...
```

or maybe do 

```
   ... =
  get() {
  }
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt (hunk 9 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 10 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 12]
```diff
@@ -91,7 +93,13 @@ internal object QuestionnaireItemDatePickerViewHolderFactory :
               }
             }
           )
-          DatePickerFragment().show(context.supportFragmentManager, DatePickerFragment.TAG)
+
+          val selectedDate = questionnaireItemViewItem.singleAnswerOrNull?.valueDateType?.localDate
+          val dateFragment = DatePickerFragment()
+          dateFragment.arguments = bundleOf(REQUEST_BUNDLE_KEY_DATE to selectedDate)
+          dateFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:100]: this feels more kotlin-y:

```suggestion
          DatePickerFragment().apply {
            arguments = bundleOf(REQUEST_BUNDLE_KEY_DATE to selectedDate)
          }.show(context.supportFragmentManager, DatePickerFragment.TAG)
```

?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 13]
```diff
@@ -80,7 +85,14 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
             updateDateTimeInput(localDateTime)
             updateDateTimeAnswer(localDateTime)
           }
-          DatePickerFragment().show(context.supportFragmentManager, DatePickerFragment.TAG)
+
+          val selectedDate =
+            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.localDate
+          val dateFragment = DatePickerFragment()
+          dateFragment.arguments = bundleOf(REQUEST_BUNDLE_KEY_DATE to selectedDate)
+          dateFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:93]:
```suggestion
          DatePickerFragment().apply {
            arguments = bundleOf(REQUEST_BUNDLE_KEY_DATE to selectedDate)
          }.show(context.supportFragmentManager, DatePickerFragment.TAG)
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 14]
```diff
@@ -110,7 +122,14 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
             // Clear focus so that the user can refocus to open the dialog
             timeInputEditText.clearFocus()
           }
-          TimePickerFragment().show(context.supportFragmentManager, TimePickerFragment.TAG)
+
+          val selectedTime =
+            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.localTime
+          val timeFragment = TimePickerFragment()
+          timeFragment.arguments = bundleOf(REQUEST_BUNDLE_KEY_TIME to selectedTime)
+          timeFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:130]:
```suggestion
          TimePickerFragment().apply {
            arguments = bundleOf(REQUEST_BUNDLE_KEY_TIME to selectedTime)
          }.show(context.supportFragmentManager, DatePickerFragment.TAG)
```

**Review by jingtang10 — APPROVED** [review]
just a few cosmetic comments.

feel free to merge once addressed. thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 14 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 13 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt (hunk 12 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt]: yup makes sense, done
