### PR TITLE
Pack repeated groups into answers

### LINKED ISSUE #1900: Repeated Group: Mapping fails when questionaire response is passed as argument.
**Describe the bug**
If a questionnaire response for repeated group item is passed, the mapping fails. This happens because the implementation currently adds answers to item.answer for repeated groups, and then later createRepeatedGroupResponse takes care of putting answerItemComponents to the repeated groups item.item field. So when questionnaire response is passed it expects repeated group items in item.answer field

 Initial UI shows up but when submitted, answers are missing

**Component**
SDC library

**To Reproduce**
Use following questionnaire and questionnaire response
[component_repeated_group.txt](https://github.com/google/android-fhir/files/10906756/component_repeated_group.txt)
[component_repeated_group_response.txt](https://github.com/google/android-fhir/files/10906762/component_repeated_group_response.txt)

**Screenshots**

https://user-images.githubusercontent.com/82660329/223357700-0c03463a-8202-41ac-93e8-528cad5ff343.mp4

@jingtang10

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1900 

**Description**
In our in-memory representation of QuestionnaireResponse, we nest repeated groups under the parent questionnaire response item as individual answers. However user-provided qustionnaire response JSON has repeated groups flattened as repeated items. To make the QuestionnaireViewModel accept such JSON, we need to pack the repeated groups under the same questionnaire response item. Additionally, when questionnaire response is returned to the application, repeated groups need to be unpacked again.

We created two extension functions `QuestionnaireResponse.packRepeatedGroups` and `QuestionnaireResponse.unpackRepeatedGroups` for this.

Create packRepeatedGroup and unpackRepeatedGroup functions

**Alternative(s) considered**
NA

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt [hunk 1]
```diff
@@ -16,8 +16,105 @@
...
+
+private fun List<QuestionnaireResponse.QuestionnaireResponseItemComponent>.packRepeatedGroups():
+  List<QuestionnaireResponse.QuestionnaireResponseItemComponent> {
+  forEach { it ->
+    it.item = it.item.packRepeatedGroups()
+    it.answer.forEach { it.item = it.item.packRepeatedGroups() }
+  }
+  val linkIdToPackedResponseItems =
+    groupBy { it.linkId }
+      .mapValues {
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt:51]: Maybe let's destructure the `it` up here, to make it a bit clearer?

```
.mapValues { (linkId, item) ->
  ...
}
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt [hunk 2]
```diff
@@ -16,8 +16,105 @@
...
+ * This function should be called before returning the questionnaire response to the application.
+ *
+ * See also [packRepeatedGroups].
+ */
+internal fun QuestionnaireResponse.unpackRepeatedGroups(questionnaire: Questionnaire) {
+  item = unpackRepeatedGroups(questionnaire.item, item)
+}
+
+private fun unpackRepeatedGroups(
+  questionnaireItems: MutableList<Questionnaire.QuestionnaireItemComponent>,
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt:88]: Does it have to be `MutableList`? I would think `List` is okay.

**Review by kevinmost — APPROVED** [review]
Overall looks really good to me

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt [hunk 3]
```diff
@@ -16,8 +16,105 @@
...
+ * correctly. This is because they are flattened out and nested directly under the parent in the
+ * FHIR data format. See discussion:
+ * http://community.fhir.org/t/questionnaire-repeating-groups-what-is-the-correct-format/2276/3
+ *
+ * This function should be called before the questionnaire view model accepts an
+ * application-provided questionnaire response.
+ *
+ * See also [unpackRepeatedGroups].
+ */
+internal fun QuestionnaireResponse.packRepeatedGroups() {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt:39]: is `packRepeatedGroups` the best name for this function? Your change seems to have removed the need to distinguish between a repeated group, and a single value answer in the QVM. Should that be reflected in the function name here? Is `packAnswers` a better name?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt [hunk 4]
```diff
@@ -16,8 +16,105 @@
...
+ * For example, if the group contains 2 questions, and the user answered the group 3 times, this
+ * function will return a list with 3 responses; each of those responses will have the linkId of the
+ * provided group, and each will contain an item array with 2 items (the answers to the individual
+ * questions within this particular group instance).
+ *
+ * This function should be called before returning the questionnaire response to the application.
+ *
+ * See also [packRepeatedGroups].
+ */
+internal fun QuestionnaireResponse.unpackRepeatedGroups(questionnaire: Questionnaire) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt:83]: same comment about the name as above

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt [hunk 5]
```diff
@@ -16,8 +16,105 @@
...
+  questionnaireItem: Questionnaire.QuestionnaireItemComponent,
+  questionnaireResponseItem: QuestionnaireResponse.QuestionnaireResponseItemComponent
+): List<QuestionnaireResponse.QuestionnaireResponseItemComponent> {
+  questionnaireResponseItem.item =
+    unpackRepeatedGroups(questionnaireItem.item, questionnaireResponseItem.item)
+  questionnaireResponseItem.answer.forEach {
+    it.item = unpackRepeatedGroups(questionnaireItem.item, it.item)
+  }
+
+  val isRepeatedGroup =
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt:107]: inline variable?

**Review by omarismail94 — COMMENTED** [review]
Do we need to add an Espresso test to verify that a user provided QR that gets answered is saved? i.e. mimicing the issue that Nitin had

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt [hunk 6]
```diff
@@ -16,8 +16,105 @@
...
 val QuestionnaireResponse.allItems: List<QuestionnaireResponse.QuestionnaireResponseItemComponent>
   get() = item.flatMap { it.descendant }
+
+/**
+ * Packs repeated groups under the same questionnaire response item.
+ *
+ * Repeated groups need some massaging before the questionnaire view model can interpret them
+ * correctly. This is because they are flattened out and nested directly under the parent in the
+ * FHIR data format. See discussion:
+ * http://community.fhir.org/t/questionnaire-repeating-groups-what-is-the-correct-format/2276/3
```
[the remark this answers is not in the document]
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt:32]: odd - that link is indeed invalid now... not sure if they shut down the community section of fhir.org site (and maybe decided the zulip chat is the way forward).

i added a different link for this.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt (hunk 3 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt]: I do like `packRepeatedGroups` actually because it's packing repeated groups and leaving other answers untouched.

I think although QVM doesn't necessarily know the how/why we're processing repeated groups differently, it still needs to know that we DO NEED to pack/unpack repeated groups... Otherwise someone else can just go and delete that line fo code in QVM.

For that reason I think I'd prefer to leave this as is.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt (hunk 4 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt]: ditto

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt (hunk 5 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesResponses.kt]: done.

File: engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
[the remark this answers is not in the document]
Comment (jingtang10) [reply engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt:1]: as discussed the TestingUtils.kt file should probably be in the testing module if reused.

I'll fix that in a follow-up. For this PR I've reverted the change.

**Comment by jingtang10** [comment]
> Do we need to add an Espresso test to verify that a user provided QR that gets answered is saved? i.e. mimicing the issue that Nitin had

i think the QVM test covers this sufficiently.

i believe expresso tests (and any other integration tests) should cover broad cases. corner cases should be covered by unit tests.

**Review by omarismail94 — APPROVED** [review]
Thanks Jing, great change!!
