### PR TITLE
Give unique name for periodic and oneTime sync worker

### LINKED ISSUE #2046: SyncJobStatus is not triggered for Finish state for android 13
**Describe the bug**

**Component**
Core library

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by omarismail94**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

**Description**
Clear and concise code change description. 

Give a unique name for the one time sync worker and the periodic worker. Currently, If we have a periodic worker set up, then trigger a oneTime, the periodic worker does not run after as it's over-written due to having the same name. This PR fixes that.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/sync/Sync.kt [hunk 1]
```diff
@@ -36,7 +36,7 @@ import kotlinx.coroutines.flow.asFlow
 import kotlinx.coroutines.flow.flatMapConcat
 import kotlinx.coroutines.flow.mapNotNull
 
-object Sync {
+class Sync(val workManager: WorkManager) {
```
Comment (aditya-07) [inline engine/src/main/java/com/google/android/fhir/sync/Sync.kt:39]: Can we keep Sync as an object and pass WorkManager as function arg for `oneTimeSync`  and `periodicSync` ?

Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/sync/Sync.kt:39]: If you want to keep it as a class, we should move functions other than `oneTimeSync` and `periodicSync` into a companion object.

File: demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt [hunk 2]
```diff
@@ -50,8 +51,8 @@ class MainActivityViewModel(application: Application) : AndroidViewModel(applica
 
   init {
     viewModelScope.launch {
-      Sync.periodicSync<FhirSyncWorker>(
-          application.applicationContext,
+      Sync(WorkManager.getInstance(application.applicationContext))
+        .periodicSync<FhirSyncWorker>(
```
Comment (aditya-07) [inline demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt:55]: The `FhirSyncWorker` class in demo app should be renamed to maybe `DemoFhirSyncWorker` as it is a bit confusing since it extends `FhirSyncWorker` from engine lib.

**Review by aditya-07 — APPROVED** [review]
LGTM
