### PR TITLE
Fixed crash caused by java.lang.UnsupportedOperationException when evaluating Observation.component.valueQuantity

### LINKED ISSUE #768: Resource Indexer throws Exception when parsing Observation with Quantity value.
**Describe the bug**
FhirPathEngine throws UnsupportedOperationException when evaluating Observation.component.valueQuantity

**Failing Test :**
```
  @Test
  fun index_observation_quantity_type_basic() {

    val observation =
      Observation().apply {
        addComponent().apply {
          this.valueQuantity.apply {
            value = BigDecimal.valueOf(70)
            system = "http://unitsofmeasure.org"
          }
        }
        addComponent().apply {
          this.valueQuantity.apply {
            value = BigDecimal.valueOf(110)
            system = "http://unitsofmeasure.org"
          }
        }
      }

    val resourceIndices = ResourceIndexer.index(observation)
    assertThat(resourceIndices.quantityIndices).isNotEmpty()
  }
```
Observation example on HAPI Server that fails http://hapi.fhir.org/baseR4/Observation/49413

**Exception trace**
```
java.lang.UnsupportedOperationException
	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.getUcumService(HapiWorkerContext.java:289)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.qtyEqual(FHIRPathEngine.java:1670)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.doEquals(FHIRPathEngine.java:1640)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.doContains(FHIRPathEngine.java:2124)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.opUnion(FHIRPathEngine.java:2112)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1422)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1189)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:525)
	at com.google.android.fhir.index.ResourceIndexerTest.index_observation_quantity_type_basic(ResourceIndexerTest.kt:631)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
```
**Component**
Core library

**Additional context**
Issue was first documented in [#694](https://github.com/google/android-fhir/issues/694#issuecomment-907234781)
Issue is also created for HAPI- [hapifhir-592](https://github.com/hapifhir/org.hl7.fhir.core/issues/592)

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #768 

**Description**
Switched HapiWorkerContext with SimpleWorkerContext in the ResourceIndexer. Added necessary unit test.
Additionally, locally tested against large file from [Synthea]( https://synthea.mitre.org/downloads) to make sure indexing works fine.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 1]
```diff
@@ -64,9 +62,9 @@ import org.hl7.fhir.r4.utils.FHIRPathEngine
  * [search parameters](https://www.hl7.org/fhir/searchparameter-registry.html).
  */
 internal object ResourceIndexer {
-  private val context = FhirContext.forR4()
-  private val fhirPathEngine =
-    FHIRPathEngine(HapiWorkerContext(context, DefaultProfileValidationSupport(context)))
+  // Switched HapiWorkerContext to SimpleWorkerContext as a fix for
+  // https://github.com/google/android-fhir/issues/768
```
Comment (deepankarb) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:66]: Nit: Info in this comment can be derived from looking at the commit message and diff.

Comment (deepankarb) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:66]: Do we need to make this change in other places where `HapiWorkerContext` is used?
https://github.com/google/android-fhir/blob/7d9c57ffb0fae2c1f39ccbc57ce8ea7c8d7842fc/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt#L81

**Review by deepankarb — APPROVED** [review]
Left a non-blocking comment. Thanks!

**Review by jingtang10 — APPROVED** [review]
