### PR TITLE
Fixed add patient crash after resource extraction

### LINKED ISSUE #663: Add Patient crashes app after submit.
**Describe the bug**
Add Patient crashes app after user presses submit button.

**Component**
 reference app

**Crash Log**
java.lang.ClassCastException: org.hl7.fhir.r4.model.Bundle cannot be cast to org.hl7.fhir.r4.model.Patient
        at com.google.android.fhir.reference.AddPatientViewModel$savePatient$1.invokeSuspend(AddPatientViewModel.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:342)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.google.android.fhir.reference.AddPatientViewModel.savePatient(AddPatientViewModel.kt:52)
        at com.google.android.fhir.reference.AddPatientFragment.savePatient(AddPatientFragment.kt:97)
        at com.google.android.fhir.reference.AddPatientFragment.onSubmitAction(AddPatientFragment.kt:93)
        at com.google.android.fhir.reference.AddPatientFragment.onOptionsItemSelected(AddPatientFragment.kt:58)

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #663 

**Description**
Fixed issue by extracting `Patient` from the `Bundle` returned by `ResourceMapper.extract()` 

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt [hunk 1]
```diff
@@ -50,7 +50,9 @@ class AddPatientViewModel(application: Application, private val state: SavedStat
    */
   fun savePatient(questionnaireResponse: QuestionnaireResponse) {
     viewModelScope.launch {
-      val patient = ResourceMapper.extract(questionnaireResource, questionnaireResponse) as Patient
+      val patient =
+        ResourceMapper.extract(questionnaireResource, questionnaireResponse).entry[0].resource as
```
Comment (stevenckngaa) [inline reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt:54]: Could entry be an empty list? If it's possible, should you fail the save operation gracefully with error message rather than crashing the reference app?

Comment (jingtang10) [reply reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt:54]: try something like this?

```suggestion
        val something = ResourceMapper.extract(questionnaireResource, questionnaireResponse).singleOrNull() ?: return
        val patient = something.resource as Patient
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt (hunk 1 above)
Comment (aditya-07) [reply reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt]: Using `entryFirstRep` property of `Bundle` that promises to returns first entry. If entry list is empty, it will add an entry and then return the first. I am now checking for the type of the `entry.resource` and returning gracefully if its not Patient.

**Review by jingtang10 — APPROVED** [review]
