### PR TITLE
Slider max and min value should be set from from the questionnaire.

### LINKED ISSUE #1715: Slider max value should be updated from the questionnaire.
**Describe the bug**
Slider max value is always shown 100.
It does not updates the max value limit as per value mentioned in the questionnaire.

**Component**
SDC library

**Expected behavior**
Max value of the slider should be read from the questionnaire.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: pixel xl emulator
 - Android version: api 30
 - Build number: na
 - Version na

**Additional context**
100 as max value is hard coded in the code.

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1715 

**Description**
Clear and concise code change description. 

- This change will read the maxValue from the extension, if maxValue extension is not present then will use the default 
   value to update the valueTo on slider to set the maxValue.
- This change will also read the minValue from the extension, if minValue extension is not present then it will use the default 
   value to update the valueFrom on slider to set the maxValue.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

https://user-images.githubusercontent.com/86107848/201939661-861d04fa-ef64-49b3-9d10-17f69e0ce29e.mov

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt [hunk 1]
```diff
@@ -80,3 +83,25 @@ internal object QuestionnaireItemSliderViewHolderFactory :
 }
 
 private const val SLIDER_DEFAULT_STEP_SIZE = 1
+private const val SLIDER_DEFAULT_VALUE_FROM = 0.0F
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt:86]: What is the reason behind the default being a float, rather than an integer?

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt:86]: `SLIDER_DEFAULT_VALUE_FROM ` is default value for `valueFrom` of Float type property of slider, therefore it is declared as Float.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryTest.kt [hunk 2]
```diff
@@ -106,6 +106,72 @@ class QuestionnaireItemSliderViewHolderFactoryTest {
...
+        Questionnaire.QuestionnaireItemComponent(),
+        QuestionnaireResponse.QuestionnaireResponseItemComponent(),
+        validationResult = NotValidated,
+        answersChangedCallback = { _, _, _ -> },
+      )
+    )
+
+    assertThat(viewHolder.itemView.findViewById<Slider>(R.id.slider).valueFrom).isEqualTo(0.0F)
+  }
+
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryTest.kt:174]: looking into it.

[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryTest.kt:176]: Added unit test, if minValue >= maxValue then it throws IllegalArgumentException.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt [hunk 3]
```diff
@@ -80,3 +83,25 @@ internal object QuestionnaireItemSliderViewHolderFactory :
...
+private const val SLIDER_DEFAULT_VALUE_TO = 100.0F
+
+private fun Slider.updateValueFrom(questionnaireItem: Questionnaire.QuestionnaireItemComponent) {
+  val minValue = MinValueConstraintValidator.getMinValue(questionnaireItem)
+  valueFrom =
+    when (minValue) {
+      is IntegerType -> minValue.value.toFloat()
+      is DecimalType -> minValue.value.toFloat()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt]: combine these 2 lines

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt [hunk 4]
```diff
@@ -80,3 +83,25 @@ internal object QuestionnaireItemSliderViewHolderFactory :
...
+      else -> SLIDER_DEFAULT_VALUE_FROM
+    }
+}
+
+private fun Slider.updateValueTo(questionnaireItem: Questionnaire.QuestionnaireItemComponent) {
+  val maxValue = MaxValueConstraintValidator.getMaxValue(questionnaireItem)
+  valueTo =
+    when (maxValue) {
+      is IntegerType -> maxValue.value.toFloat()
+      is DecimalType -> maxValue.value.toFloat()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt]: same, combine these two lines

**Review by jingtang10 — APPROVED** [review]

**Review by omarismail94 — APPROVED** [review]
Great change Santosh!
