### PR TITLE
Remove No Valuequantity text from patient details card.

### LINKED ISSUE #859: After submitting complete survey, Questionnaire in observations is missing
**Describe the bug**
After submitting complete survey, Questionnaire in observations is missing. It is only showing answer

**Component**
SDC library, reference app

Precondition:
Patient should already added

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Reference App'
2. Search for Patient already added
3. Click on 'Complete survey'
4. Add all details and click on submit
5. Observe "observation section" on patient card

**Expected behaviour**
It should show observations with Questionnaire

**Screenshots**
Screenshot_2021-10-25-16-42-24-951

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab
 - Android version: 10
 - Build number: TB-8505X-S320017_210427_BMP

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #859

**Description**
Some observation and Condition resources do not have valuequantity field, as result on patient details card no valuequantity text was shown.
Now, no value quantity text is not shown, instead of that blank text is shown.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt [hunk 1]
```diff
@@ -237,7 +237,7 @@ class PatientDetailsViewModel(
         if (observation.hasValueQuantity()) {
           observation.valueQuantity.value.toString()
         } else {
-          resources.getText(R.string.message_no_value_quantity).toString()
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt:240]: can you remove the resource in the xml file?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Review by jingtang10 — APPROVED** [review]
