### PR TITLE
Configure Review layout for SDC catalog application

### LINKED ISSUE #2777: Setup Review Layout for SDC Catalog Application
**Describe the bug**
In the catalog application under layouts section, there is no functionality associated with the Review button currently. The aim of this bug is to fix this. As the Review button is clicked, it should showcase how the Review Before Submit functionality works using standard data capture library.

**Component**
SDC Catalog App

**To Reproduce**
1. Open the SDC Catalog application
2. Click on Review button/tile
3. Nothing happens

**Expected behavior**
The user should get the questionnaire form as they click the Review tile and it should show Review button at the bottom right instead of Submit. As we click the Review button, we should go to the Review screen where user can take a look at all the information filled in a read-only layout and finally submit it.

**Smartphone (please complete the following information):**
 - Device: Pixel
 - Android version: 10

**Additional context**
N/A

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by rahulmalhotra**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2777 

**Description**
This change configures Review layout for SDC Catalog Application. It consist of the following updates:
1. Add new parameter `enableReviewMode` to Layout enum under `LayoutListViewModel.kt` and pass it as `true` for the REVIEW enum value along with `layout_review.json` to render questionnaire
2. Pass this parameter's value as an argument to `DemoQuestionnaireFragment.kt` and use it to show Review Page when its value is `true`
3. Fix `layout_review.json` to render questionnaire properly

**Alternative(s) considered**
N/A

**Type**
Bug fix

**Screenshots (if applicable)**
Screenshot 2025-02-03 at 1 36 26 PM

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by santosh-pingle — COMMENTED** [review]
Can we have questionnaire response along with questionnaire json, so that when layout get shown in the review mode it will have answers to show data in the review mode, and if user want to edit those answers, user can click on edit button at the top.

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt [hunk 1]
```diff
@@ -146,6 +146,7 @@ class DemoQuestionnaireFragment : Fragment() {
                     .LOCATION_WIDGET_PROVIDER,
                 )
                 setQuestionnaire(args.questionnaireJsonStringKey!!)
+                showReviewPageBeforeSubmit(args.enableReviewMode)
```
Comment (nsabale7) [inline catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:149]: I suggest we should also use `showReviewPageFirst(true)` and show the use-case where the user ends up directly into the review page.

Comment (jingtang10) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:149]: i think this is a good idea. just a little more direct for users to see the review mode.

Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:149]: Updated `layout_review.json` file with initial values for questions in questionnaire and added `showReviewPageFirst(true)` here as suggested.

Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:149]: Marking this conversation as resolved. Please feel free to re-open if there are any other suggestions.

File: catalog/src/main/assets/layout_review.json [hunk 2]
```diff
@@ -1,893 +1,988 @@
...
-  "meta": {
-    "profile": [
-      "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|2.7"
+    "status": "draft",
+    "publisher": "Roshnee team",
+    "name": "covid-19-screening",
+    "title": "COVID-19 Screening",
+    "resourceType": "Questionnaire",
+    "subjectType": [
+        "Encounter"
```
Comment (jingtang10) [inline catalog/src/main/assets/layout_review.json:8]: can you remove these fields? would be good for the questionnaire to be minimal

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt [hunk 3]
```diff
@@ -34,19 +34,22 @@ class LayoutListViewModel(application: Application, private val state: SavedStat
...
     ),
     PAGINATED(
       R.drawable.ic_paginatedlayout,
       R.string.layout_name_paginated,
       "layout_paginated.json",
+      false,
     ),
-    REVIEW(R.drawable.ic_reviewlayout, R.string.layout_name_review, ""),
-    READ_ONLY(R.drawable.ic_readonlylayout, R.string.layout_name_read_only, ""),
+    REVIEW(R.drawable.ic_reviewlayout, R.string.layout_name_review, "layout_review.json", true),
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt:51]: @santosh-pingle fyi

I was asking santosh to see if there's a way to use lambda to configure this.. it's sort of annoying to keep adding new arguments to this. @rahulmalhotra can you think of a way to do this?

santosh has a similar pr as well #2803

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt (hunk 3 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt]: This is done. I introduced another data class named `LayoutConfig` and converted this configuration to use lambda. Please take a look and let me know if this looks good?

File: catalog/src/main/assets/layout_review.json (hunk 2 above)
Comment (rahulmalhotra) [reply catalog/src/main/assets/layout_review.json]: Hi @MJ1998 as discussed I've converted this into two pages. The first page has a section and 4 questions and the second page has another section with 3 questions. PTAL

Comment (rahulmalhotra) [reply catalog/src/main/assets/layout_review.json]: The existing JSON had mainly 3 data types: quantity, decimal and choice. Moreover, in review mode, the layout looks pretty much the same irrespective of the data type.

Comment (MJ1998) [reply catalog/src/main/assets/layout_review.json]: Gotcha! Jing, I am resolving this. The json file LGTM.

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutConfig.kt [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+package com.google.android.fhir.catalog
+
+import androidx.annotation.DrawableRes
+import androidx.annotation.StringRes
+
+data class LayoutConfig(
+  @DrawableRes val iconId: Int,
+  @StringRes val textId: Int,
+  val questionnaireFileName: String,
+  val enableReviewMode: Boolean,
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/LayoutConfig.kt:26]:
```suggestion
  val lambda: QuestionnaireFragment.(),
```

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt [hunk 5]
```diff
@@ -31,27 +29,45 @@ class LayoutListViewModel(application: Application, private val state: SavedStat
...
   ) {
     DEFAULT(
-      R.drawable.ic_defaultlayout,
-      R.string.layout_name_default_text,
-      "layout_default.json",
+      layoutConfig {
+        iconId = R.drawable.ic_defaultlayout
+        textId = R.string.layout_name_default_text
+        questionnaireFileName = "layout_default.json"
+        enableReviewMode = false
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt:39]:
```suggestion
        {},
```

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt [hunk 6]
```diff
@@ -31,27 +29,45 @@ class LayoutListViewModel(application: Application, private val state: SavedStat
...
     ),
     PAGINATED(
-      R.drawable.ic_paginatedlayout,
-      R.string.layout_name_paginated,
-      "layout_paginated.json",
+      layoutConfig {
+        iconId = R.drawable.ic_paginatedlayout
+        textId = R.string.layout_name_paginated
+        questionnaireFileName = "layout_paginated.json"
+        enableReviewMode = false
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt:47]:
```suggestion
        {},
```

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt [hunk 7]
```diff
@@ -31,27 +29,45 @@ class LayoutListViewModel(application: Application, private val state: SavedStat
...
+      },
+    ),
+    REVIEW(
+      layoutConfig {
+        iconId = R.drawable.ic_reviewlayout
+        textId = R.string.layout_name_review
+        questionnaireFileName = "layout_review.json"
+        enableReviewMode = true
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt:55]:
```suggestion
        {
          this.showReviewPageBeforeSubmit(true)
          this.showReviewPageFirst(true)
        },
```

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt [hunk 8]
```diff
@@ -146,6 +146,8 @@ class DemoQuestionnaireFragment : Fragment() {
...
+                showReviewPageFirst(true)
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:150]:
```suggestion
```

**Review by jingtang10 — COMMENTED** [review]
can you see if something like this might work?

File: catalog/src/main/res/navigation/nav_graph.xml [hunk 9]
```diff
@@ -89,6 +89,11 @@
             app:nullable="true"
             android:defaultValue="@null"
         />
+    <argument
```
Comment (rahulmalhotra) [inline catalog/src/main/res/navigation/nav_graph.xml:92]: Hi @jingtang10 we cannot pass lambda as an argument in these navigation parameters as it only supports primitive data types. Do you have any recommendation for it?

Some of the solutions me and @MJ1998 discussed were:
1. Defining a map of string -> key and lambda and passing the key as an argument and retrieving the lambda by accessing the map in demoquestionnairefragment.
2. Using a shared view model to for LayoutListFragment as wel as DemoQuestionnaireFragment

Though I think both the approaches are somewhat different to what's happening at the moment. Please let me know your thoughts on how to proceed here.

Comment (jingtang10) [reply catalog/src/main/res/navigation/nav_graph.xml:92]: i think we should do 1

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutConfig.kt (hunk 4 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/LayoutConfig.kt]: Suggestion Applied.

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt (hunk 5 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt]: Suggestion Applied.

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt (hunk 6 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt]: Suggestion Applied.

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt (hunk 7 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt]: Suggestion Applied.

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt (hunk 8 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt]: Suggestion Applied.

File: catalog/src/main/res/navigation/nav_graph.xml (hunk 9 above)
Comment (rahulmalhotra) [reply catalog/src/main/res/navigation/nav_graph.xml:92]: Done

**Review by jingtang10 — COMMENTED** [review]
would be good to have a video for features like this in the future

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt [hunk 10]
```diff
@@ -31,27 +29,45 @@ class LayoutListViewModel(application: Application, private val state: SavedStat
   }
 
   enum class Layout(
-    @DrawableRes val iconId: Int,
-    @StringRes val textId: Int,
-    val questionnaireFileName: String,
+    val config: LayoutConfig,
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt:32]: can layout and layoutconfig not be merged? seems a bit redundant and roundabout to have 2 levels of config.

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt [hunk 11]
```diff
@@ -138,17 +138,18 @@ class DemoQuestionnaireFragment : Fragment() {
...
-                setCustomQuestionnaireItemViewHolderFactoryMatchersProvider(
-                  ContribQuestionnaireItemViewHolderFactoryMatchersProviderFactory
-                    .LOCATION_WIDGET_PROVIDER,
-                )
-                setQuestionnaire(args.questionnaireJsonStringKey!!)
-              }
-              .build()
-          add(R.id.container, questionnaireFragment, QUESTIONNAIRE_FRAGMENT_TAG)
+          val questionnaireFragmentLambda =
+            LayoutConfig.questionnaireLambdaMap[args.questionnaireLambdaKey]
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:142]: i would remove this variable declaration.

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt [hunk 12]
```diff
@@ -138,17 +138,18 @@ class DemoQuestionnaireFragment : Fragment() {
...
+          val questionnaireFragmentBuilder =
+            QuestionnaireFragment.builder().apply {
+              setCustomQuestionnaireItemViewHolderFactoryMatchersProvider(
+                ContribQuestionnaireItemViewHolderFactoryMatchersProviderFactory
+                  .LOCATION_WIDGET_PROVIDER,
+              )
+              setQuestionnaire(args.questionnaireJsonStringKey!!)
```
Comment (jingtang10) [inline catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:149]: you can simply do:

```
LayoutConfig.questionnaireLambdaMap[args.questionnaireLambdaKey ?: ""]!!.invoke(this)
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt (hunk 11 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt]: Done

File: catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt (hunk 10 above)
Comment (rahulmalhotra) [reply catalog/src/main/java/com/google/android/fhir/catalog/LayoutListViewModel.kt]: Removed `LayoutConfig` and moved `questionnaireLambdaMap` to `LayoutListViewModel`
