### PR TITLE
Clearing the old state of date and date-time ViewHolders

### LINKED ISSUE #1580: Input of one datepicker view get updated to another date picker view in layout.
**Describe the bug**
If number of date pickers are added to the layout/form, and input is given to the one date picker view then same value get updated to the another random date picker from the layout.
Please refer attached video and questionnaire json for more information.

https://user-images.githubusercontent.com/86107848/188381513-f8c6d2ef-31e9-49aa-aed9-b831eceb18b0.mov

```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "1",
      "text": "When was your last menstrual period? (LMP)",
      "type": "date"
    },
    {
      "linkId": "1-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "2-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "3-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "4-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "5-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "6-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "7-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "2",
      "text": "When was your last menstrual period? (LMP)-1",
      "type": "date"
    },
    {
      "linkId": "3",
      "text": "When was your last menstrual period? (LMP)-2",
      "type": "date"
    },
    {
      "linkId": "4",
      "text": "When was your last menstrual period? (LMP)-4",
      "type": "date"
    },
    {
      "linkId": "5",
      "text": "When was your last menstrual period? (LMP)-5",
      "type": "date"
    },
    {
      "linkId": "6",
      "text": "When was your last menstrual period? (LMP)-6",
      "type": "date"
    },
    {
      "linkId": "7",
      "text": "When was your last menstrual period? (LMP)-7",
      "type": "date"
    }
  ]
}
```

**Component**
SDC library

**To Reproduce**

**Expected behavior**
Input of one date picker should not be updated to the another date picker view.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1580 

**Description**

**Cause:** 
The date and date time view holders only set text to the TextInput if it was empty before. This logic is required when answer update causes an update in the adapter and subsequent bindView on the ViewHolder.
 But, this causes issue when the ViewHolder is recycled for a new QuestionnaireItem and the ViewHolder retains the old text (date).

**Fix:**
Cleanup up the the ViewHolder state when bind is called for a different QuestionnaireItem.
**UPDATE**
As per discussion with @jingtang10 , instead of cleaning state using a hack, `isTextUpdateRequired` is added to the particular `QuestionnaireItemViewHolderDelegate`s to check if textview has to be update or not based on current text and the `QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent` .

**Alternative(s) considered**
1. [RecyclerView.Adapter#onViewRecycled](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#onViewRecycled(VH)) could be used to forward a callback to the individual `QuestionnaireItemViewHolderDelegate` to do cleanup.
2. Have a way for `QuestionnaireItemViewHolderDelegate` to know that the bind is called as an update for the same item user is updating or is a regular bind.

Both of these require refactoring in all the `QuestionnaireItemViewHolderDelegate` and can be taken as a separate PR if required.

**Type**
Choose one: Bug fix
**Screenshots (if applicable)**
[Date Picker](https://user-images.githubusercontent.com/18224849/188478128-ecdb8c37-1b0f-4563-878d-eff548b143a1.webm)
[Date Time Picker](https://user-images.githubusercontent.com/18224849/188478268-009d7201-44e2-44be-86a7-3dbd0e889372.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by santosh-pingle — COMMENTED** [review]
If possible, can you please add one positive and negative test case in both pickers, otherwise it looks ok to me. thanks!

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt [hunk 1]
```diff
@@ -265,12 +253,59 @@ class QuestionnaireItemDatePickerViewHolderFactoryTest {
...
 
   private fun setLocale(locale: Locale) {
     Locale.setDefault(locale)
     context.resources.configuration.setLocale(locale)
   }
+
+  private val QuestionnaireItemViewHolder.dateInputView: TextView
+    get() {
+      return itemView.findViewById(R.id.text_input_edit_text)
+    }
```
Comment (santosh-pingle) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt:310]: nit: is it ok to have this logic in test itself, so that test will be more readable?

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt [hunk 2]
```diff
@@ -267,9 +254,65 @@ class QuestionnaireItemDateTimePickerViewHolderFactoryTest {
...
-    assertThat(viewHolder.itemView.findViewById<EditText>(R.id.date_input_edit_text).isEnabled)
-      .isFalse()
-    assertThat(viewHolder.itemView.findViewById<EditText>(R.id.time_input_edit_text).isEnabled)
-      .isFalse()
+    assertThat(viewHolder.dateInputView.isEnabled).isFalse()
+    assertThat(viewHolder.timeInputView.isEnabled).isFalse()
+  }
+
+  @Test
+  fun `bind multiple times with separate QuestionnaireItemViewItem should show proper date and time`() {
```
Comment (santosh-pingle) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt:262]: nit : ditto

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt [hunk 3]
```diff
@@ -265,12 +253,59 @@ class QuestionnaireItemDatePickerViewHolderFactoryTest {
...
+        QuestionnaireResponse.QuestionnaireResponseItemComponent()
+          .addAnswer(
+            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent()
+              .setValue(DateType(2021, 10, 19))
+          ),
+        validationResult = NotValidated,
+        answersChangedCallback = { _, _, _ -> },
+      )
+    )
+    assertThat(viewHolder.dateInputView.text.toString()).isEqualTo("11/19/21")
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt:289]: This tests the case of overriding the old date with the new date. The function tests 3 cases in total :
Empty -> Text, Text -> New Text, Text to Empty.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt [hunk 4]
```diff
@@ -267,9 +254,65 @@ class QuestionnaireItemDateTimePickerViewHolderFactoryTest {
...
+            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent()
+              .setValue(DateTimeType(Date(2021 - 1900, 1, 5, 2, 30, 0)))
+          ),
+        validationResult = NotValidated,
+        answersChangedCallback = { _, _, _ -> },
+      )
+    )
+
+    assertThat(viewHolder.dateInputView.text.toString()).isEqualTo("2/5/21")
+    assertThat(viewHolder.timeInputView.text.toString()).isEqualTo("2:30 AM")
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt:294]: This tests the case of overriding the old date/ time with the new date/time. The function tests 3 cases in total :
Empty -> Text, Text -> New Text, Text to Empty.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt (hunk 1 above)
Comment (aditya-07) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt:310]: IMO this makes test more readable.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt [hunk 5]
```diff
@@ -265,12 +253,59 @@ class QuestionnaireItemDatePickerViewHolderFactoryTest {
       )
     )
 
-    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.text_input_edit_text).isEnabled)
-      .isFalse()
+    assertThat(viewHolder.dateInputView.isEnabled).isFalse()
+  }
+
+  @Test
+  fun `bind multiple times with different QuestionnaireItemViewItem should show proper date`() {
```
[the remark this answers is not in the document]
Comment (aditya-07) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt:260]: The name would be misleading unless the test in broken into  2 separate tests.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt (hunk 2 above)
Comment (aditya-07) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt:262]: The name would be misleading unless the test in broken into  2 separate tests.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 6]
```diff
@@ -157,6 +161,21 @@ internal object QuestionnaireItemDatePickerViewHolderFactory :
...
+    answer: DateType?,
+    inputText: String?
+  ): Boolean {
+    val inputDate =
+      try {
+        parseDate(inputText, context)
+      } catch (e: Exception) {
+        null
+      }
+    if (answer == null || inputDate == null) return true
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:176]: why do you need this as a separate condition?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 7]
```diff
@@ -201,7 +220,7 @@ internal fun parseDate(text: CharSequence?, context: Context): LocalDate {
     } else {
       android.text.format.DateFormat.getDateFormat(context).parse(text.toString())
     }
-  val localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()
+  val localDate = LocalDate.of(date.year + 1900, date.month + 1, date.date)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:223]: do we not have a java util `Date` to `LocalDate` conversion util function anywhere?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 8]
```diff
@@ -146,7 +146,10 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
         val dateTime = questionnaireItemViewItem.answers.singleOrNull()?.valueDateTimeType
         updateDateTimeInput(
           dateTime?.let {
-            LocalDateTime.of(it.year, it.month + 1, it.day, it.hour, it.minute, it.second)
+            LocalDateTime.of(it.year, it.month + 1, it.day, it.hour, it.minute, it.second)?.also {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:149]: likewise

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt (hunk 7 above)
Comment (aditya-07) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:223]: No, we don't have any utility for this.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 8 above)
Comment (aditya-07) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:149]: No, we don't have any utility for this.

**Review by jingtang10 — APPROVED** [review]
