### PR TITLE
Nested questionnaireResponseComponent with enableWhen in repeated group is missing from questionnaire response.

### LINKED ISSUE #1895: Repeated Group: Items within group are duplicated in the Questionnaire Response, if question depends on enableWhen condition.
**Describe the bug**
If a question depends on enableWhen condition in a repeated group, it duplicates the items from the first response.

**Component**
SDC library

**To Reproduce**
Use [component_repeated_group.txt](https://github.com/google/android-fhir/files/10871700/component_repeated_group.txt) as a questionnaire

**Screenshots**
https://user-images.githubusercontent.com/82660329/222439586-5edfd017-31bb-485b-88d3-622de7b0a80e.mp4

@jingtang10

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1895

**Description**
The questionnaire response contains answers to all selected and enabled questionnaire items. However, when copying the questionnaire response, the use of 'getEnabledResponseItems' fails to copy the selected answers of enabled items.
when the type is a repeated group item, the questionnaireResponseItemParentMap is always empty in the findEnableWhenQuestionnaireResponseItem() API. This is because the buildParentList logic in EnablementEvaluator fails to correctly build the parent list for repeated group items.

**Alternative(s) considered**

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
I am adding end to end android test for this fix, but getting below error when `Add item ` get clicked second time to add more repeated group.

```
androidx.test.espresso.AmbiguousViewMatcherException: 'view.getId() is <2131230792/com.google.android.fhir.datacapture.test:id/add_item>' matches multiple views in the hierarchy.
Problem views are marked with '****MATCHES****' below.
```
Can we please review the PR? If the Android test gets fixed, I will push the changes; otherwise, I will have a separate PR for this Android test.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt [hunk 1]
```diff
@@ -75,16 +75,18 @@ internal class EnablementEvaluator(val questionnaireResponse: QuestionnaireRespo
 
   init {
     /** Adds each child-parent pair in the [QuestionnaireResponse] to the parent map. */
-    fun buildParentList(item: QuestionnaireResponse.QuestionnaireResponseItemComponent) {
-      for (child in item.item) {
-        questionnaireResponseItemParentMap[child] = item
-        buildParentList(child)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt:81]:
```
  for (child in item.item) {
    ...
  }
  for (answer in item.ansewr) {
    for (nestedItem in answer.item) {
      map[nestedItem] = item
      ... // recursion
    }
  }
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 2]
```diff
@@ -305,7 +305,12 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
    */
   fun getQuestionnaireResponse(): QuestionnaireResponse {
     return questionnaireResponse.copy().apply {
-      item = getEnabledResponseItems(this@QuestionnaireViewModel.questionnaire.item, item)
+      item =
+        getEnabledResponseItems(
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:309]:
```suggestion
        // Use the view model's questionnaire and questionnaire response for calculating enabled items because the calculation relies on references to the questionnaire response items.
        getEnabledResponseItems(
```

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt:1]: I feel the changes in this test can be in the QuestionnaireViewModelTest.kt file.

The reason that I say this, is that, espresso tests and integration tests are more expensive than unit tests. Their purpose is to test the e2e user journey and especially UI. In this case, the bug is a specific case for repeated group and is the result of `getQuestionnaireResponse` function. So if we can write a unit test case to catch this, it is preferable.

**Review by jingtang10 — CHANGES_REQUESTED** [review]
This is a great catch! Thanks for debugging!

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
Comment (santosh-pingle) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt:1]: done. 
Added unit test.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:314]: done.
Updated inline comment.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt]: done.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 3]
```diff
@@ -4295,6 +4295,375 @@ class QuestionnaireViewModelTest {
     assertThat(enabledDisplayItems[0].text).isEqualTo("Text when yes is selected")
   }
 
+  @Test
+  fun `repeatedGroupItem response contains enabled items`() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:4299]: 1) this function needs to be moved up. under the section called "Questionnaire Response"

```suggestion
  fun `getQuestionnaireResponse() should return enabled repeated groups`() {
```

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt [hunk 4]
```diff
@@ -443,6 +448,89 @@ class QuestionnaireUiEspressoTest {
     }
   }
 
+  @Test
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt:451]: i think we don't need this test case for two reasons:

1) i think the bug is sufficiently covered by your test case in QVM test.
2) @kevinmost 's work to complete repeate group UI might add new items in the recycler view, and your test case relies on the indices of UI widgets. i think this test will break with kevin's change.

File: datacapture/sampledata/repeated_group.json
Comment (jingtang10) [inline datacapture/sampledata/repeated_group.json:1]: can this be removed? see comment later.

**Review by jingtang10 — APPROVED** [review]
@santosh-pingle thanks again for this change!

File: datacapture/sampledata/repeated_group.json
Comment (santosh-pingle) [reply datacapture/sampledata/repeated_group.json:1]: done.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt]: done.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done.
