### PR TITLE
Fix for dropdown showing up again on answer change.

### LINKED ISSUE #1554: Double selection of a dropdown
**Describe the bug**
When filling a questionnaire with an input type choice drop-down, the answer is not automatically picked on the first selection, it requires a second selection for it to update on the input field.

**Component**
SDC library
 
**Expected behavior**
Upon selection of an answer from the drop-down list, the answer should be automatically updated on the input field.

**Screenshots** 
[device-2022-08-11-122529.webm](https://user-images.githubusercontent.com/26279422/184105258-1745b205-0498-46d8-874f-ac167bd4247d.webm)

**Smartphone (please complete the following information):**
 - Device:All

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1554 

**Description**
A change in the dropdown answer triggers bindView to be called on the `ViewHolder` again. Since the `adapter` is already set on the `autoCompleteTextView`, this causes the dropdown to appear again as soon as the text is set to it.

Issue is fixed by setting a `null adapter` in the `bindView` before setting text so that any old adapter from previous binding is gone.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
[drop_down.webm](https://user-images.githubusercontent.com/18224849/185599805-d327c68a-8ab7-44dc-bbea-02b71993a4b9.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt [hunk 1]
```diff
@@ -84,5 +85,9 @@ internal object QuestionnaireItemDropDownViewHolderFactory :
       override fun setReadOnly(isReadOnly: Boolean) {
         textInputLayout.isEnabled = !isReadOnly
       }
+
+      private fun cleanupOldState() {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt:89]: does this really need to be a separate function?

**Review by jingtang10 — APPROVED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt (hunk 1 above)
Comment (aditya-07) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt:89]: It doesn't but a good reminder for anyone in the future to cleanup stuff here.
