### PR TITLE
DateTime Picker : Do not enable time input if date textfield is empty, do not show error message if date input is valid.

### LINKED ISSUE #1870: Date Time Picker Component behavior is broken
**Describe the bug**
In catalog app, select date time picker component - there are 2 issue as broken behavior
1. By default time input UI is enabled, which is expected to be enabled after entering Valid date
2. Date format error is displayed, though user has entered valid date 

**Component**
SDC library, SDC gallery app

**To Reproduce**
1. Go to 'Catalog App, Date time picker component'
3. See error 'By default time input UI is enabled'
4. Enter 'Valid date in date input widget by text (without date picker)'
5. See error "Date format needs to be MM/dd/yyyy (e.g. 01/31/2023)"

**Expected behavior**
1. By default time widget should be disabled untill Valid date is entered
2.  Date format error should disappear on entering Valid date.

**Screenshots**
Videos are attached below

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - Android version:API 24

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1870 

**Description**

- Do not enable the time input textField if the date input textField is empty.
- If the date input in the date textField is valid, then there should be no error message displayed.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 1]
```diff
@@ -210,25 +210,31 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
-            Invalid(
-              listOf(
-                dateInputEditText.context.getString(
-                  R.string.date_format_validation_error_msg,
-                  canonicalizedDatePattern,
-                  canonicalizedDatePattern
-                    .replace("dd", "01")
-                    .replace("MM", "01")
-                    .replace("yyyy", "2023")
+          val dateAsPartialInput =
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:216]: jsut remove this variable

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 2]
```diff
@@ -210,25 +210,31 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
+                    canonicalizedDatePattern
+                      .replace("dd", "01")
+                      .replace("MM", "01")
+                      .replace("yyyy", "2023")
+                  )
                 )
               )
             )
-          )
+          }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:237]: just put this in the catch block

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 3]
```diff
@@ -210,25 +210,31 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
-                  R.string.date_format_validation_error_msg,
-                  canonicalizedDatePattern,
-                  canonicalizedDatePattern
-                    .replace("dd", "01")
-                    .replace("MM", "01")
-                    .replace("yyyy", "2023")
+          val dateAsPartialInput =
+            try {
+              parseDate(partialAnswerToDisplay, canonicalizedDatePattern)
+            } catch (parseException: Exception) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:219]: Use ParseException instead of Exception

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done.

**Comment by santosh-pingle** [comment]
https://user-images.githubusercontent.com/86107848/219035310-d7c6675c-903c-4744-a9be-a2de6617564f.mov

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 4]
```diff
@@ -437,3 +428,10 @@ internal val DateTimeType.localDateTime
       minute,
       second,
     )
+
+internal fun Context.invalidDateErrorText(@StringRes resId: Int, formatPattern: String) =
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:432]: As discussed, let's make this a function as opposed to an extension function

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 5]
```diff
@@ -337,7 +337,8 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
         try {
           localDate = parseDate(text, canonicalizedDatePattern)
           questionnaireItemViewItem.updatePartialAnswer(text.toString())
-          displayDateValidationError(Valid)
+          displayDateValidationError(NotValidated)
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:340]: is there a reason we set this now as `NotValidated` as opposed to `Valid`?

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:340]: If the validation result is either `Valid` or `NotValidated', it removes the validation error text from the view, except in one case where if the result is 'valid' but the answer is not present.
In this case, even though the date is valid, the answer cannot be present, so it is still necessary to remove the error text.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 5 above)
Comment (omarismail94) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:341]: Im still struggling to understand this. I just ran the catalog app and wrote text in the Date field, then deleted it, but the error text remained. From your comment, that is not supposed to happen right? Please add a unit test for this case if so

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 6]
```diff
@@ -431,3 +430,11 @@ internal val DateTimeType.localDateTime
       minute,
       second,
     )
+
+/** Replaces 'dd' with '31', 'MM' with '01' and 'yyyy' with '2023' and returns new string. */
+internal fun invalidDateErrorText(context: Context, @StringRes resId: Int, formatPattern: String) =
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:435]: Can we move this function to another file? I think `MoreLocalDates` or `QuestionnaireItemDatePickerViewHolderFactory` are better suited as this function only deals with Dates, and not DateTime

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 7]
```diff
@@ -431,3 +430,11 @@ internal val DateTimeType.localDateTime
       minute,
       second,
     )
+
+/** Replaces 'dd' with '31', 'MM' with '01' and 'yyyy' with '2023' and returns new string. */
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:434]: Could you add an example of this? e.g:

```
For example, given a formatPattern of dd/MM/yyyy, returns 31/01/2023
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 5 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:343]: If a date input is parsed as a partial answer, then 'NotValidated' is required to remove the error text.
I have already added a unit test, but I renamed it to `if the date input is parsed, do not display the error message for a parsed date input` and added one more assertion to make it clearer.

**Comment by santosh-pingle** [comment]
```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "1",
      "text": "Schedule an appointment 1",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "2",
      "text": "Schedule an appointment 2",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "3",
      "text": "Schedule an appointment 3",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "4",
      "text": "Schedule an appointment 4",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "5",
      "text": "Schedule an appointment 5",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "6",
      "text": "Schedule an appointment 6",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "7",
      "text": "Schedule an appointment 7",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "8",
      "text": "Schedule an appointment 8",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "9",
      "text": "Schedule an appointment 9",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "10",
      "text": "Schedule an appointment 10",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "11",
      "text": "Schedule an appointment 11",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "12",
      "text": "Schedule an appointment 12",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "13",
      "text": "Schedule an appointment 13",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "14",
      "text": "Schedule an appointment 14",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "15",
      "text": "Schedule an appointment 15",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    }

  ]
}
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 8]
```diff
@@ -400,7 +293,8 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
             datePatternSeparator,
             isDeleting
           )
-          updateAnswerAfterTextChanged(editable.toString())
```
Comment (aditya-07) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:403]: We don't have to update /invalidate answer? In a case where user sets proper date and time (so that answer gets set) and then changes date text, would answer get removed from questionnaireItemViewItem?

**Review by aditya-07 — COMMENTED** [review]
Some initial comments.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 9]
```diff
@@ -112,7 +112,7 @@ data class QuestionnaireItemViewItem(
     )
   }
 
-  /** Clears existing answers. */
+  /** Clears existing answers and any draft answer. */
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt:115]: add to the documentation of `setAnswer`, `addAnswer` and `removeAnswer` that they will clear the draft answer.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt [hunk 10]
```diff
@@ -293,34 +286,68 @@ class QuestionnaireItemDateTimePickerViewHolderFactoryTest {
...
+      )
+
+    viewHolder.bind(itemViewItem)
+
+    assertThat(viewHolder.itemView.findViewById<TextInputLayout>(R.id.time_input_layout).isEnabled)
+      .isFalse()
+  }
+
+  @Test
+  fun `if the draft answer input is null, do not enable the time text input layout`() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt:323]:
```suggestion
  fun `if there is no answer or draft answer, do not enable the time text input layout`() {
```

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt [hunk 11]
```diff
@@ -100,4 +101,64 @@ class QuestionnaireUiEspressoTest {
...
+
+    // Check the answer exists in Questionnaire Response
+    activityScenarioRule.scenario.onActivity { activity ->
+      val testQuestionnaireFragment =
+        activity.supportFragmentManager
+          .findFragmentById(R.id.container_holder)
+          ?.childFragmentManager?.findFragmentById(R.id.container) as QuestionnaireFragment
+      val questionnaireResponse = testQuestionnaireFragment.getQuestionnaireResponse()
+      assertThat(questionnaireResponse.item.first().answer.size).isEqualTo(1)
+      assertThat(questionnaireResponse.item.first().answer.first().hasValueDateTimeType()).isTrue()
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt:161]: assert on the value

**Review by jingtang10 — APPROVED** [review]
