### PR TITLE
Add 100ms delay to the AutoComplete action in emulator tests to fix the test flakiness

### LINKED ISSUE #1323: DropDown widget Espresso tests flaky
**Describe the bug**
https://github.com/google/android-fhir/runs/6130147669?check_suite_focus=true

**Component**
SDC lib

**To Reproduce**
1. Run `QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt` locally in Android Studio

**Expected behavior**
Passes every time

**Actual results**
`shouldSetDropDownValueToAutoCompleteTextView ` fails frequently (but not all the time)

**Screenshots**

https://user-images.githubusercontent.com/28757340/165289316-d96de6a8-7eb1-4917-906f-3d604f5a7cb3.mp4

**Smartphone (please complete the following information):**
 - Device: PIxel 6
 - Build number: SP2A.220505.002
 - Android version: 12
 - API Level: 32
 
**Additional context**
NA

**Would you like to work on the issue?**
NA

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1323

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt [hunk 1]
```diff
@@ -38,7 +38,7 @@ fun showDropDown(): ViewAction {
     override fun perform(uiController: UiController, view: View?) {
       val autoCompleteTextView = view as AutoCompleteTextView
       autoCompleteTextView.showDropDown()
-      uiController.loopMainThreadUntilIdle()
+      uiController.loopMainThreadForAtLeast(100)
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt:41]:
```suggestion
      // Avoid test flakiness with a delay. See https://github.com/google/android-fhir/issues/1323.
      uiController.loopMainThreadForAtLeast(100)
```

**Review by jingtang10 — APPROVED** [review]
thanks @PallaviGanorkar for fixing this!

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt (hunk 1 above)
Comment (jingtang10) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt:41]: sorry i accidentally merged this. i'll add this comment in my next pr. don't worry.

Comment (jingtang10) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt:41]: addressed in PR #1352
