### PR TITLE
Hidden extension to hide question item.

### LINKED ISSUE #683: Question item was not hidden after adding hidden extension in item in questionnaire.
**Describe the bug**
After adding hidden extension to questionnaire, it does not hide questionnaire item while rendering the ui.

"extension": [
                {
                  "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden",
                  "valueBoolean": "true"
                }
              ],

- If hidden extension is true, then question item will not be shown irrespective of whether it enabled or not.
- If hidden extension is true and question item is enabled, then initial answers (if present) will be part of questionnaire response.
- If hidden extension is false or not present, and question item is enabled, then question item will be shown.
- If hidden extension is false or not present, and question item is not enabled, then question item will not be shown.

**Component**
SDC library

**To Reproduce**

**Expected behavior**
It should hide questionnaire item with hidden extension.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #683 

**Description**
Add hidden extension implementation.

- If hidden extension is true, then question item will not be shown irrespective of whether it is enabled or not.
- If hidden extension is true and question item is enabled, then initial answers (if present) will be part of questionnaire response.
- If hidden extension is false or not present, and question item is enabled, then question item will be shown.
- If hidden extension is false or not present, and question item is not enabled, then question item will not be shown.

**Alternative(s) considered**
no

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by jingtang10 — COMMENTED** [review]
Thanks @santosh-pingle!

Have you considered the alternative -- in the view model figure out if a questionnaire item is hidden and avoid adding it to the list for the recycler view?

**Comment by santosh-pingle** [comment]
I will try to push review changes by end of today which will have addressed review comments and updated unit tests.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 1]
```diff
@@ -198,23 +198,28 @@ internal class QuestionnaireViewModel(state: SavedStateHandle) : ViewModel() {
...
+                        questionnaireResponseItem.answer.first().item
+                      },
+                    // we're now dealing with nested items, so pagination is no longer a concern
+                    pagination = null,
+                  )
+                  .items
+            }
           } else {
             emptyList()
           }
```
Comment (aditya-07) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:225]: Can be simplified to: 
```suggestion
            if (enabled && !questionnaireItem.isHidden) {
              listOf(
                QuestionnaireItemViewItem(questionnaireItem, questionnaireResponseItem) {
                  questionnaireResponseItemChangedCallback(questionnaireItem.linkId)
                }
              ) +
                getQuestionnaireState(
                    questionnaireItemList = questionnaireItem.item,
                    questionnaireResponseItemList =
                      if (questionnaireResponseItem.answer.isEmpty()) {
                        questionnaireResponseItem.item
                      } else {
                        questionnaireResponseItem.answer.first().item
                      },
                    // we're now dealing with nested items, so pagination is no longer a concern
                    pagination = null,
                  )
                  .items
            }
          } else {
            emptyList()
          }
```

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 2]
```diff
@@ -813,6 +813,70 @@ class QuestionnaireViewModelTest {
...
+        )
+      )
+      .isTrue()
+    assertThat(
+        viewModel.getQuestionnaireItemViewItemList()[0].questionnaireResponseItem.equalsDeep(
+          questionnaireResponse.item[1]
+        )
+      )
+      .isTrue()
+    assertResourceEquals(viewModel.getQuestionnaireResponse(), questionnaireResponse)
```
Comment (aditya-07) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:877]: Are these assertions necessary for the test case?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:225]: Actually, below edge case is also required.
If hidden extension is true and question item is enabled, then initial answers (if present) will be part of questionnaire response.
(Line no. 201 change is required if it is enabled and hidden.)

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:877]: (Line. no 877 assertion) Actually, it is required, to make sure, if question item is hidden and enabled and it has initial value, then those answers should be part of questionnaire response.

(Line no. 871 assertion) it is good to have to just check questionnaireItemView has correct indexed responseItem if previous questionnaireItemView is hidden.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt [hunk 3]
```diff
@@ -74,6 +77,13 @@ internal val Questionnaire.QuestionnaireItemComponent.localizedText: String?
 internal val Questionnaire.QuestionnaireItemComponent.localizedPrefix: String?
   get() = prefixElement?.getLocalizedText()
 
+/** Hidden extension value as boolean. */
+internal val Questionnaire.QuestionnaireItemComponent.isHidden: Boolean
+  get() {
+    val value = this.extension.firstOrNull { it.url == EXTENSION_HIDDEN_URL }?.value as BooleanType?
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt:83]: this cast could cause a crash.

do this instead:

```
    val extension = this.extension.singleOrNull { it.url == EXTENSION_HIDDEN_URL } ?: return false
    val value = extension.value
    if (value is BooleanType){
      return value.booleanValue()
    }
    return false
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 4]
```diff
@@ -198,23 +198,28 @@ internal class QuestionnaireViewModel(state: SavedStateHandle) : ViewModel() {
...
-                    } else {
-                      questionnaireResponseItem.answer.first().item
-                    },
-                  // we're now dealing with nested items, so pagination is no longer a concern
-                  pagination = null,
-                )
-                .items
+            // TODO Issue#755 update question item with initial value, there is separate PR.
+            if (questionnaireItem.isHidden) {
+              emptyList()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:203]: early return.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Review by jingtang10 — APPROVED** [review]

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 2 above)
Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:877]: this is fine - but to simplify a little more you could just check the link id rather than comparing the whole response item

File: datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt [hunk 5]
```diff
@@ -74,6 +77,17 @@ internal val Questionnaire.QuestionnaireItemComponent.localizedText: String?
 internal val Questionnaire.QuestionnaireItemComponent.localizedPrefix: String?
   get() = prefixElement?.getLocalizedText()
 
+/** Hidden extension value as boolean. */
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt:80]:
```suggestion
/** Whether the QuestionnaireItem should be hidden according to the hidden extension or lack thereof. */
```
