### PR TITLE
Show submit button in review mode.

### LINKED ISSUE #1817: Submit button is not visible on review summary page.
**Describe the bug**
If review mode is enabled, and user click on review mode button it launches review summary page, but here Submit button is missing to submit the form, issue is seen on default and paginated layout.

**Component**
 SDC library

**To Reproduce**
Precondition : 
Set QuestionnaireFragment.EXTRA_ENABLE_REVIEW_PAGE to true in DemoquestionnaireFragment in catalog app.
1. Open catalog app.
2. Click on layouts
3. Click on Review  button
4. There is no Submit button on review summary page.

**Expected behavior**
Submit button should be visible on review summary page.

**Screenshots**

https://user-images.githubusercontent.com/86107848/213367859-28609a67-217f-486f-b4e2-3d8ce5cf66aa.mov

**Smartphone (please complete the following information):**
 - Device: PixelXL Emulator
 - Android version: Android Api 30
 - Build number: not required
 - Version : not required

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1817

**Description**
 1. Make submit button Visible in Review mode if the app is using the inbuilt submit button.
 2. Updated `QuestionnaireValidationErrorMessageDialogFragment` and `QuestionnaireFragment` to pass in appropriate result messages in callback to change mode from Review to Edit incase there are errors on Submit and user decides to fix them.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
[review_mode_edit.webm](https://user-images.githubusercontent.com/18224849/214304944-d5fd066d-a9f8-4626-91a8-d5fe219b8843.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 1]
```diff
@@ -131,7 +131,7 @@ open class QuestionnaireFragment : Fragment() {
             questionnaireReviewRecyclerView.visibility = View.VISIBLE
 
             // Set button visibility
-            submitButton.visibility = View.GONE
+            submitButton.visibility = if (displayMode.showSubmitButton) View.VISIBLE else View.GONE
```
Comment (santosh-pingle) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:134]:
```suggestion
            submitButton.visibility = if (displayMode.showSubmitButton) {
            View.VISIBLE 
            } else {
            View.GONE
            }
```

**Review by santosh-pingle — COMMENTED** [review]
@aditya-07 can we please also add unit tests or android tests, if possible?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt (hunk 1 above)
Comment (aditya-07) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:134]: Since the whole `if else ` fits in a single line, I don't think adding brackets is necessary.

**Comment by aditya-07** [comment]
> @aditya-07 can we please also add unit tests or android tests, if possible?

Added some tests for checking the visibility of Submit Button.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 2]
```diff
@@ -202,7 +202,15 @@ open class QuestionnaireFragment : Fragment() {
...
       QuestionnaireValidationErrorMessageDialogFragment.RESULT_CALLBACK,
       viewLifecycleOwner
-    ) { _, _ -> setFragmentResult(SUBMIT_REQUEST_KEY, Bundle.EMPTY) }
+    ) { _, bundle ->
+      when (bundle[QuestionnaireValidationErrorMessageDialogFragment.RESULT_KEY]) {
+        QuestionnaireValidationErrorMessageDialogFragment.RESULT_VALUE_FIX -> {
+          // Go back to the Edit mode if currently in the Review mode.
+          viewModel.setReviewMode(false)
+        }
+        else -> setFragmentResult(SUBMIT_REQUEST_KEY, Bundle.EMPTY)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:211]: can you make this a bit more explicit but using RESULT_VALUE_SUBMIT?

this is so that if in the future we add another value it would be more obvious what to do

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 3]
```diff
@@ -3294,6 +3294,8 @@ class QuestionnaireViewModelTest {
       viewModel.setReviewMode(true)
       assertThat(viewModel.questionnaireStateFlow.first().displayMode)
         .isInstanceOf(DisplayMode.ReviewMode::class.java)
+      assertThat(viewModel.questionnaireStateFlow.first().displayMode)
+        .isEqualTo(DisplayMode.ReviewMode(showEditButton = true, showSubmitButton = true))
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:3298]: is there a case where showSubmitButton would be false? is that covered here?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 3 above)
Comment (aditya-07) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:3298]: It would be false when the application overrides the default theme to disable SDC's Submit button and have their own.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt (hunk 2 above)
Comment (aditya-07) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt]: Done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:3298]: may be one more test can be added in QuestionnaireFragmentTest.kt by enabling readOnlyMode  with argument `QuestionnaireFragment.EXTRA_READ_ONLY to true` which can set showSubmitButton as false?

**Review by jingtang10 — APPROVED** [review]
