### PR TITLE
Accepts questionnaire URI as an extra for QuestionnaireFragment in the datacapture library

### LINKED ISSUE #672: Crash on configuration change with a large questionnaire
**Describe the bug**
App crashes with configuration change while using a large questionnaire

**Component**
datacapturegallery

**To Reproduce**

1. Use the questionnaire attached in this issue
2. Minimize the application after rendering the quesitonnaire

**Expected behavior**
App should not crash and the current state should be available

**Smartphone (please complete the following information):**
- OnePlus 7t Pro

[questionnaireLarge.txt](https://github.com/google/android-fhir/files/6870052/questionnaireLarge.txt)

### PR DESCRIPTION
**Pull request by stevenckngaa**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #672

**Description**
Accepts questionnaire in the form of URI on top of raw JSON string.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
Yes, Jing, Yigit and I talked about sharing the questionnaire json among ViewModels but that solution was discarded because we still store a huge questionnaire in the memory. The current solution accepts an `URI` which is then passed to FHIR parser as input stream.

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt [hunk 1]
```diff
@@ -67,12 +72,14 @@ class QuestionnaireContainerFragment : Fragment() {
 
       val fragment = CustomQuestionnaireFragment()
 
-      fragment.arguments =
-        bundleOf(
-          QuestionnaireFragment.BUNDLE_KEY_QUESTIONNAIRE to viewModel.questionnaire,
-          QuestionnaireFragment.BUNDLE_KEY_QUESTIONNAIRE_RESPONSE to viewModel.questionnaireResponse
-        )
-      childFragmentManager.commit { add(R.id.container, fragment, QUESTIONNAIRE_FRAGMENT_TAG) }
+      GlobalScope.launch(Dispatchers.Main) {
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt:75]:
```suggestion
      viewLifecycleOwner.lifecycleScope.launch {
```

?

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt [hunk 2]
```diff
@@ -67,12 +72,14 @@ class QuestionnaireContainerFragment : Fragment() {
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt:72]: remove line

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt [hunk 3]
```diff
@@ -67,12 +72,14 @@ class QuestionnaireContainerFragment : Fragment() {
 
       val fragment = CustomQuestionnaireFragment()
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt:74]: remove empty line

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 4]
```diff
@@ -99,6 +99,7 @@ open class QuestionnaireFragment : Fragment() {
 
   companion object {
     const val BUNDLE_KEY_QUESTIONNAIRE = "questionnaire"
+    const val BUNDLE_KEY_QUESTIONNAIRE_URI = "questionnaire_URI"
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:102]:
```suggestion
    const val BUNDLE_KEY_QUESTIONNAIRE_URI = "questionnaire-uri"
```

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt [hunk 5]
```diff
@@ -100,6 +100,11 @@ class QuestionnaireListFragment : Fragment() {
             "HL7 example \"bb\" with questionnaire response to pre-fill answers",
             "hl7-questionnaire-example-bluebook.json",
             "hl7-questionnaireresponse-example-bluebook.json"
+          ),
+          QuestionnaireListItem(
+            "Large questionnaire",
+            "HL7 example Large questionnaire",
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt:106]: @joiskash is it ok if we put this questionnaire you authored in the gallery app? if so can you suggest name and description? thanks!

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt [hunk 6]
```diff
@@ -17,33 +17,57 @@
...
 import androidx.lifecycle.SavedStateHandle
+import kotlinx.coroutines.CoroutineScope
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.withContext
+import java.io.File
+import java.io.FileOutputStream
 
 class QuestionnaireViewModel(application: Application, private val state: SavedStateHandle) :
   AndroidViewModel(application) {
+  private val backgroundContext = CoroutineScope(Dispatchers.IO).coroutineContext
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt:31]: viewModelScope?

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt [hunk 7]
```diff
@@ -17,33 +17,57 @@
...
-        state.get<String>(QuestionnaireContainerFragment.QUESTIONNAIRE_RESPONSE_FILE_PATH_KEY)
-          ?.let { questionnaireResponseJson = readFileFromAssets(it) }
-      }
-      return questionnaireResponseJson
-    }
 
-  private fun readFileFromAssets(filename: String): String {
-    return getApplication<Application>().assets.open(filename).bufferedReader().use {
+  suspend fun getQuestionnaireJson() = withContext(backgroundContext) {
+    questionnaireJson = questionnaireJson?.let { it }
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt:37]: does `.let{ it }` do anything? is it just no-op?

**Review by jingtang10 — CHANGES_REQUESTED** [review]
thanks for the fix @stevenckngaa

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt (hunk 5 above)
Comment (joiskash) [reply datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt:106]: Sure you can. We can call it Malaria Net Card Distribution - Door to Door survey

**Comment by Tarun-Bhardwaj** [comment]
@stevenckngaa , just curious to know if there's any progress on this PR?

**Comment by stevenckngaa** [comment]
@jingtang10 @yigit could you please take a look?

**Comment by stevenckngaa** [comment]
@jingtang10, @yigit could you please take a look?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 8]
```diff
@@ -98,8 +98,21 @@ open class QuestionnaireFragment : Fragment() {
...
+     */
+    const val EXTRA_JSON_ENCODED_QUESTIONNAIRE = "questionnaire"
+    /**
+     * A [Uri] extra for streaming a questionnaire.
+     *
+     * This is required unless [EXTRA_JSON_ENCODED_QUESTIONNAIRE] is provided.
+     */
+    const val EXTRA_QUESTIONNAIRE_URI = "questionnaire-uri"
+    /** A JSON encoded string extra for a prefilled questionnaire response. */
+    const val EXTRA_QUESTIONNAIRE_RESPONSE = "questionnaire-response"
```
Comment (yigit) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:115]: should this also have a URI for consistency ?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 9]
```diff
@@ -34,21 +36,31 @@ import org.hl7.fhir.r4.model.QuestionnaireResponse
...
+      if (state.contains(QuestionnaireFragment.EXTRA_QUESTIONNAIRE_URI)) {
+        val uri: Uri = state[QuestionnaireFragment.EXTRA_QUESTIONNAIRE_URI]!!
+        FhirContext.forR4()
+          .newJsonParser()
+          .parseResource(application.contentResolver.openInputStream(uri)) as
+          Questionnaire
+      } else {
+        val questionnaireJson: String =
+          state[QuestionnaireFragment.EXTRA_JSON_ENCODED_QUESTIONNAIRE]!!
+        FhirContext.forR4().newJsonParser().parseResource(questionnaireJson) as Questionnaire
```
Comment (yigit) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:55]: we probably want to throw in another else case.
like update this else to check for EXTRA_JSON_ENCODED_QUESTIONNAIRE and another else branch to have `error("one of these parameters must be supplied")`

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 10]
```diff
@@ -98,8 +98,21 @@ open class QuestionnaireFragment : Fragment() {
...
   companion object {
-    const val BUNDLE_KEY_QUESTIONNAIRE = "questionnaire"
-    const val BUNDLE_KEY_QUESTIONNAIRE_RESPONSE = "questionnaire-response"
+    /**
+     * A JSON encoded string extra for a questionnaire. This should only be used for questionnaires
+     * with size at most 512KB. For large questionnaires, use [EXTRA_QUESTIONNAIRE_URI].
+     *
+     * This is required unless [EXTRA_QUESTIONNAIRE_URI] is provided.
+     */
+    const val EXTRA_JSON_ENCODED_QUESTIONNAIRE = "questionnaire"
```
Comment (yigit) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:107]: need to document which one wins if both are provided.

**Review by yigit — CHANGES_REQUESTED** [review]
feel free to submit after the small nits are fixed.

we can implement accepting answers as URI as nother PR.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt (hunk 10 above)
Comment (stevenckngaa) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:110]: Done. I log a warning in case both EXTRA_JSON_ENCODED_QUESTIONNAIRE & EXTRA_QUESTIONNAIRE_URI are provided.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt (hunk 8 above)
Comment (stevenckngaa) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:120]: Sure. Tracked in https://github.com/google/android-fhir/issues/916

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 9 above)
Comment (stevenckngaa) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt]: Done. Also added a test case.

**Comment by stevenckngaa** [comment]
Filed https://github.com/google/android-fhir/issues/916 to track questionnaire response URI.

**Comment by stevenckngaa** [comment]
@jingtang10 @yigit could you please take another look? I can't submit this change because both of you have requested changes.

**Review by yigit — APPROVED** [review]

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt [hunk 11]
```diff
@@ -17,33 +17,62 @@
...
+      questionnaireUri
+    }
+
+  suspend fun getQuestionnaireResponse() =
+    withContext(backgroundContext) {
+      state.get<String>(QuestionnaireContainerFragment.QUESTIONNAIRE_RESPONSE_FILE_PATH_KEY)?.let {
+        path ->
+        questionnaireResponseJson?.let { cachedResponse ->
+          questionnaireResponseJson =
+            questionnaireResponseJson?.let { cachedResponse } ?: readFileFromAssets(path)
```
Comment (jingtang10) [inline datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt:57]: i find this line kinda hard to read. can we just do `if (questionnaireResponseJson == null) { ... }`?

**Review by jingtang10 — CHANGES_REQUESTED** [review]
As discussed, please load the small questionnaires in the gallery app without using a file.

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt [hunk 12]
```diff
@@ -100,6 +100,11 @@ class QuestionnaireListFragment : Fragment() {
             "HL7 example \"bb\" with questionnaire response to pre-fill answers",
             "hl7-questionnaire-example-bluebook.json",
             "hl7-questionnaireresponse-example-bluebook.json"
+          ),
+          QuestionnaireListItem(
+            "Malaria Net Card Distribution Survey",
+            "A very large HL7 questionnaire for Malaria Net card distribution",
```
[the remark this answers is not in the document]
Comment (stevenckngaa) [reply datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt:106]: Done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 13]
```diff
@@ -98,8 +98,26 @@ open class QuestionnaireFragment : Fragment() {
...
+    /**
+     * A [Uri] extra for streaming a questionnaire.
+     *
+     * This is required unless [EXTRA_JSON_ENCODED_QUESTIONNAIRE] is provided.
+     *
+     * If this and [EXTRA_JSON_ENCODED_QUESTIONNAIRE] are provided, this extra takes precedence.
+     */
+    const val EXTRA_QUESTIONNAIRE_URI = "questionnaire-uri"
```
[the remark this answers is not in the document]
Comment (stevenckngaa) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:118]: Done

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt (hunk 12 above)
[the remark this answers is not in the document]
Comment (stevenckngaa) [reply datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt:106]: Done.

File: datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt (hunk 11 above)
Comment (stevenckngaa) [reply datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt:57]: Done.

**Comment by stevenckngaa** [comment]
@jingtang10 I have changed the data capture gallery app to only load large questionnaires via URI. PTAL.

**Review by jingtang10 — APPROVED** [review]
👍👍👍🎉🎉🎉
