### PR TITLE
Refactor edit text widget to fix integer issue

### LINKED ISSUE #1718: Catalog: Integer field deletes itself after 11th digit
**Describe the bug**
While typing into "ID number" which is an integer field, once you type the 11th number the field auto-deletes all the contents.

**Component**
SDC gallery app

**To Reproduce**
1. Select "Text field" in catalog app
2. Select "ID number" field
3. Enter an 11 digit number

**Expected behavior**
Field does not delete itself.

**Screenshots**

https://user-images.githubusercontent.com/7772901/201771093-4cbd5ca1-d353-482b-a687-06c4d6e8a194.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4

**Additional context**
Different than #1594 - the auto-delete behavior is new, in 1594 the text just scrolls so it's not visible.

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1718 

**Description**
This PR does the following:
- rename "partial" answer to "draft" answer which is a more accurate name
- save out-of-range integers as a draft answer and therefore avoid deleting them
- remove function `displayValidationError` as it is no longer suitable for all widgets with draft answers

**Alternative(s) considered**
NA

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt [hunk 1]
```diff
@@ -84,7 +84,11 @@ interface QuestionnaireItemViewHolderDelegate {
    */
   fun init(itemView: View)
 
-  /** Binds a [QuestionnaireItemViewItem] to the view. */
+  /**
+   * Binds a [QuestionnaireItemViewItem] to the view. This may update the UI to display the
+   * question, the answer, and any validation result. Note that any validation result being
+   * displayed in this function may be overwritten by [displayValidationResult].
+   */
   fun bind(questionnaireItemViewItem: QuestionnaireItemViewItem)
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:92]: minor nit: should we move the `bind` function definition below `displayValidationResult` as the latter now gets called before in `open fun bind`?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt [hunk 2]
```diff
@@ -83,26 +83,14 @@ abstract class QuestionnaireItemEditTextViewHolderDelegate(private val rawInputT
...
-
-  private fun updateAnswer(editable: Editable?) {
-    val input = getValue(editable.toString())
-    if (input != null) {
-      questionnaireItemViewItem.setAnswer(input)
-    } else {
-      questionnaireItemViewItem.clearAnswer()
-    }
+      textInputEditText.doAfterTextChanged { editable: Editable? ->
+        handleInput(editable!!, questionnaireItemViewItem)
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:90]: is `editable!!` always guaranteed to be non-null?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt [hunk 3]
```diff
@@ -117,16 +105,13 @@ abstract class QuestionnaireItemEditTextViewHolderDelegate(private val rawInputT
...
+  abstract fun handleInput(editable: Editable, questionnaireItemViewItem: QuestionnaireItemViewItem)
 
-  /**
-   * Returns the text that should be displayed in the [TextInputEditText] from the existing answer
-   * to the question (may be input by the user or previously recorded).
-   */
-  abstract fun getText(
-    answer: QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent?
-  ): String
+  /** Handles the */
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:111]: nit: please update doc string

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt [hunk 4]
```diff
@@ -83,26 +83,14 @@ abstract class QuestionnaireItemEditTextViewHolderDelegate(private val rawInputT
...
-      questionnaireItemViewItem.clearAnswer()
-    }
+      textInputEditText.doAfterTextChanged { editable: Editable? ->
+        handleInput(editable!!, questionnaireItemViewItem)
+      }
   }
 
-  open fun isTextUpdatesRequired(answerText: String, inputText: String) = (answerText != inputText)
-
   override fun displayValidationResult(validationResult: ValidationResult) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:94]: should we now move `displayValidationResult` above `bind`?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt [hunk 5]
```diff
@@ -30,18 +33,41 @@ internal object QuestionnaireItemEditTextIntegerViewHolderFactory :
...
+        editable: Editable,
+        questionnaireItemViewItem: QuestionnaireItemViewItem
+      ) {
+        val input = editable.toString()
+        val inputInteger = input.toIntOrNull()
+        if (inputInteger != null) {
+          questionnaireItemViewItem.setAnswer(
+            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent()
+              .setValue(IntegerType(input))
+          )
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt:46]: we are saying here that any input that can be turned into an Integer will be saves in the Questionnaire Response. Is there a scenario where we want to save the integer as a partial answer

**Review by omarismail94 — COMMENTED** [review]
Do we need to write unit tests as well?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 6]
```diff
@@ -213,13 +213,18 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
       QuestionnaireResponseItemComponent, List<QuestionnaireResponseItemAnswerComponent>>()
 
   /**
-   * Map from QuestionnaireResponseItem to invalid input as partial answer e.g "02/02" for date type
-   * (year part missing). If the partial answer becomes valid then the entry in this map should be
-   * removed, e.g, "02/02/2023" is valid answer and should not be part of the map. This is used to
-   * maintain partial input on the screen especially when the widgets are being recycled as a result
-   * of scrolling.
+   * Map from QuestionnaireResponseItems to draft answers, e.g "02/02" for date with missing year
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:216]:
```suggestion
   * Map from [QuestionnaireResponseItemComponent] to draft answers, e.g "02/02" for date with missing year
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 7]
```diff
@@ -213,13 +213,18 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
...
+   * part.
+   *
+   * This is used to maintain draft answers on the screen especially when the widgets are being
+   * recycled as a result of scrolling. Draft answers cannot saved in [QuestionnaireResponse]
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:220]:
```suggestion
   * recycled as a result of scrolling. Draft answers cannot be saved in [QuestionnaireResponse]
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 8]
```diff
@@ -213,13 +213,18 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
...
+   * because it might be incomplete and unparsable. Without this map, incomplete and unparsable
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:221]:
```suggestion
   * because they might be incomplete and unparsable. Without this map, incomplete and unparsable
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 9]
```diff
@@ -213,13 +213,18 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
...
+   * answers would be lost.
+   *
+   * If a draft answer becomes valid then the entry in this map should be removed, e.g, "02/02/2023"
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:224]:
```suggestion
   * When the draft answer becomes valid, its entry in the map is removed, e.g, "02/02/2023"
```

File: datacapture/src/main/res/values/strings.xml [hunk 10]
```diff
@@ -1,52 +1,60 @@
...
+    <!-- 1. The following sections include strings used for the questionnaire UI -->
+
+    <!-- 1.1 Navigation -->
     <string name="button_pagination_next">Next</string>
     <string name="button_pagination_previous">Previous</string>
     <string name="back_button_text">Back</string>
     <string name="edit_button_text">Edit</string>
     <string name="review_answers_text">Review answers</string>
+    <string name="button_review">Review</string>
+    <string name="submit_questionnaire">Submit</string>
```
Comment (omarismail94) [inline datacapture/src/main/res/values/strings.xml:12]: nit: can we have these in alphabetical order?

Comment (omarismail94) [reply datacapture/src/main/res/values/strings.xml:12]: here and in every section in this file

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt [hunk 11]
```diff
@@ -244,13 +244,13 @@ class QuestionnaireItemDatePickerViewHolderFactoryTest {
...
     viewHolder.bind(questionnaireItem)
-    questionnaireItem.updatePartialAnswer("02/07")
+    questionnaireItem.setDraftAnswer("02/07")
 
     assertThat(answers!!).isEmpty()
   }
 
   @Test
-  fun `clear partial value on an valid answer update`() {
+  fun `clear darft value on an valid answer update`() {
```
Comment (omarismail94) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt:253]:
```suggestion
  fun `clear draft value on an valid answer update`() {
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt [hunk 12]
```diff
@@ -85,15 +83,11 @@ interface QuestionnaireItemViewHolderDelegate {
...
-   * Binds a [QuestionnaireItemViewItem] to the view. This may update the UI to display the
-   * question, the answer, and any validation result. Note that any validation result being
-   * displayed in this function may be overwritten by [displayValidationResult].
+   * Binds a [QuestionnaireItemViewItem] to the view. This should update the UI to display the
+   * question, the answer, and any validation result.
    */
   fun bind(questionnaireItemViewItem: QuestionnaireItemViewItem)
 
-  /** Displays validation messages on the view. */
-  fun displayValidationResult(validationResult: ValidationResult)
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:91]: Maaan, the code is sooooo much nicer without this function now!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 13]
```diff
@@ -142,10 +142,17 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
           canonicalizedDatePattern
         )
         dateInputEditText.addTextChangedListener(textWatcher)
+
+        displayValidationResult(questionnaireItemViewItem.validationResult)
+      }
+
+      fun displayValidationResult(validationResult: ValidationResult) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:149]:
```suggestion
     private fun displayValidationResult(validationResult: ValidationResult) {
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 14]
```diff
@@ -142,10 +142,17 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
+        displayDateValidationError(validationResult)
+        displayTimeValidationError(validationResult)
       }
 
       fun displayDateValidationError(validationResult: ValidationResult) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:154]:
```suggestion
      private fun displayDateValidationError(validationResult: ValidationResult) {
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt [hunk 15]
```diff
@@ -38,14 +43,19 @@ internal object QuestionnaireItemEditTextIntegerViewHolderFactory :
         questionnaireItemViewItem: QuestionnaireItemViewItem
       ) {
         val input = editable.toString()
+        if (input.isNullOrEmpty()) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt:46]: Since `editable` is non-nullable, do we need the `isNull`?
```suggestion
        if (input.isEmpty()) {
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt [hunk 16]
```diff
@@ -51,7 +51,6 @@ import java.time.format.DateTimeFormatterBuilder
 import java.time.format.FormatStyle
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt:51]: Since we're touching this file, could you delete the function `isTextUpdateRequired` ? We don't use it anywhere

**Review by omarismail94 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt (hunk 12 above)
Comment (omarismail94) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:91]: We also need to remove this function from [QuestionnaireItemBarCodeReaderViewHolderFactory.kt](https://github.com/google/android-fhir/blob/master/contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/QuestionnaireItemBarCodeReaderViewHolderFactory.kt#L121-L123) as the 'displayValidationResult' overrides nothing

Comment (omarismail94) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:91]: and in [CustomNumberPickerFactory](https://github.com/google/android-fhir/blob/master/catalog/src/main/java/com/google/android/fhir/catalog/CustomNumberPickerFactory.kt#L46-L48)

**Review by jingtang10 — COMMENTED** [review]
thanks omar!

**Review by omarismail94 — APPROVED** [review]
Excellent change!! 🚀

**Comment by jingtang10** [comment]
thanks omar!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt (hunk 12 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt:91]: done
