### PR TITLE
Display category extension for instructions.

### LINKED ISSUE #1450: Subtitle text not behaving as expected
Case 1: The text "Correct!" appears twice, once incorrectly above the question "Cats are better than dogs", and once correctly based on the `enableWhen` element.
```json
{
  "resourceType": "Questionnaire",
  "status": "active",
  "item": [
    {
      "linkId": "2",
      "text": "Demographic Information",
      "type": "group",
      "item": [
        {
          "linkId": "2.1",
          "text": "Cats are better than dogs",
          "type": "boolean"
        },
        {
          "linkId": "2.1.1",
          "text": "Correct!",
          "type": "display",
          "enableWhen": [
            {
              "question": "2.1",
              "operator": "=",
              "answerBoolean": true
            }
          ]
        }
      ]
    }
  ]
}
```
image

Case 2: When `enableWhen` is a child of the item, the "Correct!" text never appears. It still shows up incorrectly above the question, like in Case 1.
```json
{
  "resourceType": "Questionnaire",
  "status": "active",
  "item": [
    {
      "linkId": "2",
      "text": "Demographic Information",
      "type": "group",
      "item": [
        {
          "linkId": "2.1",
          "text": "Cats are better than dogs",
          "type": "boolean",
          "item": [
            {
              "linkId": "2.1.1",
              "text": "Correct!",
              "type": "display",
              "enableWhen": [
                {
                  "question": "2.1",
                  "operator": "=",
                  "answerBoolean": true
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
image

This is using the published version of `com.google.android.fhir:data-capture:0.1.0-beta03`.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1450

**Description**
Clear and concise code change description. 

- Implement display category extension to show instructions text.
- http://hl7.org/fhir/R4/valueset-questionnaire-display-category.html
- update questionnaire json in catalog app for instructions.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
Just realised I need to update the all questionnaire json for instructions text in catalog app as well, once its is done, I will update the assignee for code review. thanks!

File: datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt [hunk 1]
```diff
@@ -465,18 +470,35 @@ class MoreQuestionnaireItemComponentsTest {
...
     Locale.setDefault(Locale.US)
 
-    assertThat(questionItemList.first().localizedHintSpanned.toString()).isEqualTo("subtitle text")
+    assertThat(questionItemList.first().localizedInstructionsSpanned.toString())
+      .isEqualTo("subtitle text")
   }
 
   @Test
-  fun localizedHintSpanned_nonMatchingLocale_shouldReturnText() {
+  fun localizedInstructionsSpanned_nonMatchingLocale_shouldReturnText() {
```
Comment (PallaviGanorkar) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt:486]: you can use the new kotlin test case names in reverse single quotes: https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods, this is applicable to all test cases in PR

**Review by PallaviGanorkar — DISMISSED** [review]

**Comment by jingtang10** [comment]
@santosh-pingle please include screenshots and make sure @shelaghm has seen them! thanks!

**Comment by santosh-pingle** [comment]
Screen Shot 2022-09-07 at 12 58 02 PM
Screen Shot 2022-09-07 at 12 58 25 PM
Screen Shot 2022-09-07 at 12 59 01 PM

**Review by PallaviGanorkar — COMMENTED** [review]
Please rename "shouldHideHint" test method with "hides instructions" in QuestionnaireGroupTypeHeaderViewTest and QuestionnaireItemHeaderViewTest class to consistency in name with instructions test methods

**Comment by PallaviGanorkar** [comment]
> Please rename "shouldHideHint" test method with "hides instructions" in QuestionnaireGroupTypeHeaderViewTest and QuestionnaireItemHeaderViewTest class to consistency in name with instructions test methods

other code changes LGTM, Thanks

**Comment by shelaghm** [comment]
@santosh-pingle The date format has some letters in lower case and some capitalized. 
dd/MM/yy. 

Is this set by device settings or can it be changed so it is all lower case? 
dd/mm/yyyy

**Comment by santosh-pingle** [comment]
> @santosh-pingle The date format has some letters in lower case and some capitalized. dd/MM/yy.
> 
> Is this set by device settings or can it be changed so it is all lower case? dd/mm/yyyy

This is local date pattern, which comes from device system.

Instructions texts shown in attached screenshot which are 
- Select one
- Check all that apply
- First day of most recent period.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt [hunk 2]
```diff
@@ -175,6 +175,68 @@ class MoreQuestionnaireItemComponentsTest {
     assertThat(questionnaireItem.displayItemControl).isEqualTo(DisplayItemControlType.FLYOVER)
   }
 
+  @Test
+  fun `isFlyoverCode item returns true`() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt:179]:
```suggestion
  fun `isFlyoverCode should return true`() {
```

same below

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt [hunk 3]
```diff
@@ -100,14 +122,30 @@ class QuestionnaireItemHeaderViewTest {
...
+              listOf(
+                Coding().apply {
+                  code = INSTRUCTIONS
+                  system = EXTENSION_DISPLAY_CATEGORY_SYSTEM
+                }
+              )
+          }
+        )
+      }
     view.bind(
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt:141]: make this a const in this class since it's been used twice?

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt [hunk 4]
```diff
@@ -100,14 +123,30 @@ class QuestionnaireGroupTypeHeaderViewTest {
...
+            coding =
+              listOf(
+                Coding().apply {
+                  code = INSTRUCTIONS
+                  system = EXTENSION_DISPLAY_CATEGORY_SYSTEM
+                }
+              )
+          }
+        )
+      }
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt:141]: make this a const in this class since it's been used twice?

**Review by jingtang10 — APPROVED** [review]

File: catalog/src/main/assets/boolean_choice_questionnaire.json [hunk 5]
```diff
@@ -7,7 +7,22 @@
...
+              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
+              "valueCodeableConcept": {
+                "coding": [
+                  {
+                    "system": "http://hl7.org/fhir/questionnaire-display-category",
+                    "code": "instructions",
+                    "display": "Instructions"
+                  }
+                ],
+                "text": "The text provides guidance on how the information will be handled from a instructions perspective."
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply catalog/src/main/assets/boolean_choice_questionnaire.json]: done.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt]: done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt]: done.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt]: done.
