### PR TITLE
Indexing for SearchParams defined in Resource class

### LINKED ISSUE #1305: Update search indexing logic to consider search params in full Class hierarchy.
1. It appears that engine is not traversing the full Class hierarchy of the model classes to figure out all the SearchParams that need to be indexed into the database. This is causing search by `Patient.RES_ID` to fail.

_Originally posted by @aditya-07 in https://github.com/google/android-fhir/issues/1283#issuecomment-1102336832_

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1305 

**Description**
The search parameters defined in Resource class like id has path defined as `Resource.id`. With this, when a derived class like `Patient` is passed into the `FHIRPathEngine.evaluate` function, it doesn't return anything. So, we are adding the index values manually.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt [hunk 1]
```diff
@@ -38,7 +38,7 @@ class FhirApplication : Application() {
     }
     FhirEngineProvider.init(
       FhirEngineConfiguration(
-        enableEncryptionIfSupported = true,
+        enableEncryptionIfSupported = false,
```
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt:41]: did you need this change for testing? reverse please if so.

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 2]
```diff
@@ -98,6 +100,28 @@ internal object ResourceIndexer {
         }
       }
 
+    addIndexesFromResourceClass(resource, indexBuilder)
+    return indexBuilder.build()
+  }
+
+  /**
+   * Adds indexes for [SearchParameter] defined in [Resource] class. The reason they are added here
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:108]:
```suggestion
   * Adds indexes for [SearchParameter]s defined in [Resource] class. The reason they are added here
```

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 3]
```diff
@@ -98,6 +100,28 @@ internal object ResourceIndexer {
...
+   * manually is because the path for these [SearchParameter]s is defined for [Resource] class and
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:109]: "The reason they are added here manually is because" -> "This is because"

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 4]
```diff
@@ -98,6 +100,28 @@ internal object ResourceIndexer {
...
+   * [FHIRPathEngine.evaluate] doesn't return anything when run against a derived resource like
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:110]: The actual reason is the code generator doesn't generate search parameters for the base resource class right?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt (hunk 1 above)
Comment (aditya-07) [reply demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt:41]: Yes, oversight on my end. Will revert it.

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt (hunk 4 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:110]: Right and also because the expression path is defined for the resource class and hence when a derived class like `Patient` is evaluated for id using expression path `Resource.id`, `FHIRPathEngine` doesn't return anything. it expects the path to be "Patient.id".

File: demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt (hunk 1 above)
Comment (aditya-07) [reply demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt]: Done

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt (hunk 4 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt]: Updated the comments to explain the reason.

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt (hunk 3 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt]: Done

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt (hunk 2 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt]: Done

**Review by jingtang10 — APPROVED** [review]
