### PR TITLE
Reference app get crashed when it get launched.

### LINKED ISSUE #565: Reference app get crashed when it get launched.
**Describe the bug**
Reference app get crashed when it get launched.

**Component**
 reference app

**To Reproduce**
1. Just launch the reference app.

**Expected behavior**
Reference app should not be crashed when it get launched.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Moto G5 Plus]
 - Android version: [8.1]

**Additional context**

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
        at androidx.room.RoomDatabase$JournalMode.resolve(RoomDatabase.java:663)
        at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:1346)
        at com.google.android.fhir.db.impl.DatabaseImpl.<init>(DatabaseImpl.kt:59)
        at com.google.android.fhir.FhirServices$Builder.build(FhirServices.kt:40)
        at com.google.android.fhir.FhirEngineBuilder.build(FhirEngineBuilder.kt:26)
        at com.google.android.fhir.reference.FhirApplication.constructFhirEngine(FhirApplication.kt:47)
        at com.google.android.fhir.reference.FhirApplication.<init>(FhirApplication.kt:32)
        at java.lang.Class.newInstance(Native Method)

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
Fix reference app crash.

Testing
Tested on Moto G5 Plus, Android 8.1

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #565 

**Description**
Reference app was getting crashed when context was null in ContextWrapper.
Moved init block to onCreate callback method in FhirApplication. 

**Alternative(s) considered**
No

**Type**
Choose one: (Bug fix)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by santosh-pingle** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fandroid-fhir%2Fpull%2F571) for more info**.

@googlebot I signed it!

**Review by aditya-07 — APPROVED** [review]

**Comment by aditya-07** [comment]
Nice first PR Santosh @santosh-pingle !

**Comment by aditya-07** [comment]
@jingtang10 Please review the PR.

File: reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt [hunk 1]
```diff
@@ -29,7 +29,15 @@ import kotlinx.coroutines.launch
 import org.hl7.fhir.r4.model.ResourceType
 
 class FhirApplication : Application() {
-  init {
+  //     only initiate the FhirEngine when used for the first time, not when the app is created
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt:32]: Remove the unnecessary spaces. Also capitalize the sentence.

```suggestion
  // Only initiate the FhirEngine when used for the first time, not when the app is created.
```

File: reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt [hunk 2]
```diff
@@ -29,7 +29,15 @@ import kotlinx.coroutines.launch
...
+  private val fhirEngine: FhirEngine by lazy { constructFhirEngine() }
+
+  companion object {
+    fun fhirEngine(context: Context) = (context.applicationContext as FhirApplication).fhirEngine
+  }
```
Comment (jingtang10) [inline reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt:37]: nit and optional: move this back to the bottom of the class

**Review by jingtang10 — APPROVED** [review]
thanks @santosh-pingle
