### PR TITLE
Change validateQuestionnaireResponseItems to allow questionnaire response with missing items

### LINKED ISSUE #912: QuestionnaireResponse validator not consider missing items and answers
**Describe the bug**
QuestionnaireResponse validator assumes that questionnaire and response items has 1-1 mapping in [validator](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt#L42). This leads to validating question item X against response item Y

```
while (questionnaireItemListIterator.hasNext() &&
      questionnaireResponseItemListIterator.hasNext())
```

**Component**
Data Capture

**To Reproduce**
1. Create Questionnaire with multiple items in groups having skip logic and assign validation to all
2. Skip one group from answer
3. Validate
4. See error on item A although answer is correct due to the fact that the item above was not answered due to skip logic

### PR DESCRIPTION
**Pull request by joiskash**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #912 #836

**Description**
Re-wrote validateQuestionnaireResponseItems to take the input questionnaire response and validate it against the questionnaire response that is created by using the questionnaire.

**Alternative(s) considered**
Yes the alternative was to use the input questionnaire response as the main questionnaire response and add items if and when enable was activated. This seemed to be a more complicated solution

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by joiskash** [comment]
@jingtang10 please take a look at this. There are two questions:

**Comment by joiskash** [comment]
@jingtang10 please take a look at this. These two questions are dealt as follows:

1. How do we deal with a questionnaire response that has more items than the questionnaire? Currently throwing an error No matching questionnaire item for questionnaire response item
2. How do we deal with a questionnaire response that has less items than the questionnaire? Not throwing any error because questionnaire response may not have disabled items.

**Comment by joiskash** [comment]
> Should the validation code live in QuestionnaireResponseValidator.kt instead?
That class is responsible for validating answers that are typed in via UI. I dont think we should mix them up. Maybe we change the name of this function to checkQuestionnaireResponseAgainstQuestionnaire

This function is independent of creating the questionnaire response item . What I have done is to use the questionnaire response item that is created with the questionnaire and only fill up answers from the input questionnaire response after verifying that 

1. linkIDs match and order of questions is maintained
2. type matches for the primitive types
3. only questionnaire items which allow repeats allow multiple answers
4. There are no extra questionnaire response items

Since we are not using the input questionnaire response as the main questionnaire response to build view items, we will not be generating view items without response in the tuple. This is to make sure that irrespective of the items present in the input questionnaire response, the SDK will allow the user to answer the questionnaire completely.

PS: input questionnaire response is the one that is passed to the fragment via the bundle. The main questionnaire response is what we create by going through the questionnaire hierarchy.

**Comment by joiskash** [comment]
I have made two changes as per @jingtang10 suggestion

1. Moved the validation function to QuestionnaireResponseValidator.kt 
2. Made some change in the getQuestionnaireState function to add missing questionnaireResponseItems.

I felt that instead of allowing for empty questionnaireResponseItems in the QuestionnaireItemViewItem, we could just use existing code to create them while fetching the list for the state flow. This change also helps us in the futures by avoiding zipping questionnaires and questionnaireResponse together because of the details in #910

**Comment by jingtang10** [comment]
@kevinmost can you please also take a look at this? thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 1]
```diff
@@ -248,14 +249,22 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
...
-        .flatMap { (questionnaireItemAndIndex, questionnaireResponseItem) ->
-          val (index, questionnaireItem) = questionnaireItemAndIndex
-
+        .flatMap { (index, questionnaireItem) ->
+          var questionnaireResponseItem = questionnaireItem.createQuestionnaireResponseItem()
+
+          // If there is an enabled questionnaire response available then we use that. Or else we
+          // just use an empty questionnaireResponse Item
+          if (responseIndex < questionnaireResponseItemList.size &&
+              questionnaireItem.linkId.equals(questionnaireResponseItem.linkId)
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:263]: Nit: Prefer `==` in Kotlin

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 2]
```diff
@@ -248,14 +249,22 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
     pagination: QuestionnairePagination?,
   ): QuestionnaireState {
     // TODO(kmost): validate pages before switching between next/prev pages
+    var responseIndex = 0
     val items: List<QuestionnaireItemViewItem> =
       questionnaireItemList
         .asSequence()
         .withIndex()
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:256]: Nit: Would be a bit more performant to use

```
.flatMapIndexed { index, questionnaireItem ->
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt [hunk 3]
```diff
@@ -59,4 +59,85 @@ object QuestionnaireResponseValidator {
...
+   * Traverse (DFS) through the list of questionnaire items and the list of questionnaire response
+   * items and check if the linkId of the matching pairs of questionnaire item and questionnaire
+   * response item are equal.
+   */
+  fun validateQuestionnaireResponseItems(
+    questionnaireItemList: List<Questionnaire.QuestionnaireItemComponent>,
+    questionnaireResponseInputItemList:
+      List<QuestionnaireResponse.QuestionnaireResponseItemComponent>,
+  ) {
+    val questionnaireResponseInputItemListIterator = questionnaireResponseInputItemList.iterator()
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt:73]: If these two need to have the same length (which it looks like they do, as we throw an error if they don't on line 137), I would recommend using `zip` and doing something like this:

```kotlin
require(questionnaireItemList.size == questionnaireResponseInputItemList.size) {
  "Unequal item amounts: ${questionnaireItemList.size} items and ${questionnaireResponseInputItemList.size} responses"
}
questionnaireItemList.zip(questionnaireResponseInputItemList)
  .forEach { (questionnaireItem, questionnaireResponseInputItem) -> ... }
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt [hunk 4]
```diff
@@ -59,4 +59,85 @@ object QuestionnaireResponseValidator {
...
+    val questionnaireItemListIterator = questionnaireItemList.iterator()
+
+    while (questionnaireResponseInputItemListIterator.hasNext()) {
+      // TODO: Validate type and item nesting within answers for repeated answers
+      // https://github.com/google/android-fhir/issues/286
+      val questionnaireResponseInputItem = questionnaireResponseInputItemListIterator.next()
+      if (questionnaireItemListIterator.hasNext()) {
+        val questionnaireItem = questionnaireItemListIterator.next()
+        if (!questionnaireItem.linkId.equals(questionnaireResponseInputItem.linkId)) {
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt:82]: Nit: I'd also do this via `require`, and use `==`.

```kotlin
require(questionnaireItem.linkId == questionnaireResponseInputItem.linkId) { "Mismatching..." }
```

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 5]
```diff
@@ -313,10 +353,165 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
...
       }
     val questionnaireResponse = QuestionnaireResponse().apply { id = "a-questionnaire-response" }
+    val questionnaireResponseWithMissingItem =
+      QuestionnaireResponse().apply {
+        id = "a-questionnaire-response"
+        addItem(
+          QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
+            linkId = "a-link-id"
+            answer =
+              mutableListOf(
```
Comment (kevinmost) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:368]: Does this need to be mutable?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt (hunk 3 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt:73]: They don't have to be of the same length.. The questionnaire response may not have some items . This can happen if the item was disabled / not answered. That's why i removed the zip from the previous implementation.

Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt:73]: The error we throw on line 137 is to make sure the questionnaire response does not have more items than the questionnaire. But the questionnaire response can have less number of items. Thats why I am iterating over questionnaireResponseList and using the index to fetch the corresponding questionnaire item. You will find more details regarding this in #836 . Please let me know if it does not make sense.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 1 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 2 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt (hunk 4 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt]: done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 5 above)
Comment (joiskash) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: nope , i made changed it to `listOf` :)

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt [hunk 6]
```diff
@@ -59,4 +59,85 @@ object QuestionnaireResponseValidator {
     }
     return linkIdToValidationResultMap
   }
+
+  /**
+   * Traverse (DFS) through the list of questionnaire items and the list of questionnaire response
+   * items and check if the linkId of the matching pairs of questionnaire item and questionnaire
+   * response item are equal.
+   */
+  fun validateQuestionnaireResponseItems(
```
[the remark this answers is not in the document]
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt]: done, I have made this function a private helper and changed the names of the validate functions.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt [hunk 7]
```diff
@@ -53,10 +53,104 @@ object QuestionnaireResponseValidator {
...
+            type != Questionnaire.QuestionnaireItemType.GROUP
+        ) {
+          if (!questionnaireItem.repeats && questionnaireResponseInputItem.answer.size > 1) {
+            throw IllegalArgumentException(
+              "Multiple answers in ${questionnaireResponseInputItem.linkId} and repeats false in " +
+                "questionnaire item ${questionnaireItem.linkId}"
+            )
+          }
+          questionnaireResponseInputItem.answer.forEachIndexed {
+            index,
```
Comment (kevinmost) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt:112]: Nit: Looks like the index is not needed, could this become `forEach` instead?

**Review by kevinmost — APPROVED** [review]

**Review by jingtang10 — APPROVED** [review]
Thanks @joiskash!

I think with this change, we should move a lot of the test cases from view model to the validation package. But that can be done in a follow-up.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt (hunk 7 above)
Comment (joiskash) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt:112]: Will take care of it in my next PR. Thanks!

**Comment by joiskash** [comment]
> Thanks @joiskash!
> 
> I think with this change, we should move a lot of the test cases from view model to the validation package. But that can be done in a follow-up.
> 
> 

Yes absolutely! That shouldn't be too hard to do.
