### PR TITLE
Handle indexing of timing with no event or has a repeating timing. 

### LINKED ISSUE #1282: Timing type with missing event field crashes application in ResourceIndexer with NPE.
**Describe the bug**

`Timing` (http://hl7.org/fhir/datatypes.html#Timing) type with missing `event` crashes application in ResourceIndexer with NPE.

```
2022-04-06 15:38:07.496 9331-9331/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 9331
    java.util.NoSuchElementException
        at com.google.android.fhir.index.ResourceIndexer.dateTimeIndex(ResourceIndexer.kt:190)
        at com.google.android.fhir.index.ResourceIndexer.extractIndexValues(ResourceIndexer.kt:84)
        at com.google.android.fhir.index.ResourceIndexer.index(ResourceIndexer.kt:68)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertResource(ResourceDao.kt:202)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll$suspendImpl(ResourceDao.kt:74)
```

**Component**
Core library

**To Reproduce**
1. Add a CarePlan with Timing field and no 'event' and save into DB 
```
{
	"resourceType": "CarePlan",
	"status": "active",
	"intent": "plan",
	"title": "Child Routine visit CarePlan",
	"description": "This defines the schedule of care for patients under 5 years old",
	"subject": {
	    "reference": "Patient/36eb5dae-cdff-4049-9dce-470fe286cc9e"
	},
	"period": {
	    "start": "2022-04-06T00:00:00",
	    "end": "2026-12-01T00:00:00"
	},
	"created": "2022-04-06T13:55:50+00:00",
	"activity": [
	    {
		"detail": {
		    "kind": "Task",
		    "code": {
		        "coding": [
		            {
		                "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
		                "code": "MO",
		                "display": "MO"
		            }
		        ],
		        "text": "MO"
		    },
		    "status": "in-progress",
		    "scheduledTiming": {
		        "repeat": {
		            "count": 55,
		            "countMax": 60,
		            "duration": 2,
		            "durationMax": 4,
		            "durationUnit": "h",
		            "frequency": 1,
		            "frequencyMax": 1,
		            "period": 1,
		            "periodMax": 1,
		            "periodUnit": "mo"
		        }
		    },
		    "description": "Child Monthly Routine visit"
		}
	    }
	]
}
```
2- Right after save when indexing it would crash and would save if any value is added to timing.event. 
ResourceIndexer L#185 should not use max and assumes a non null/empty event field
```
"Timing" -> {
        val timing = value as Timing
        DateTimeIndex(
          searchParam.name,
          searchParam.path,
          timing.event.minOf { it.value.time },
          timing.event.maxOf { it.precision.add(it.value, 1).time } - 1
        )
      }
```

**Expected behavior**
It should not crash as event is nullable by spec http://hl7.org/fhir/datatypes.html#Timing.

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1282 

**Description**
1. Skip timings if they don't have an event to specify start and end date.
2. Handle string values for date time.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt [hunk 1]
```diff
@@ -209,12 +210,31 @@ internal object ResourceIndexer {
...
-        )
+        // Skip for now if its is repeating.
+        if (timing.hasEvent()) {
+          DateTimeIndex(
+            searchParam.name,
+            searchParam.path,
+            timing.event.minOf { it.value.time },
+            timing.event.maxOf { it.precision.add(it.value, 1).time } - 1
+          )
+        } else null
```
Comment (PallaviGanorkar) [inline engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:221]: Though we are not handling repeating event here, i think we should not sent null as its confusing for user as there is repeating event is present but SDK is giving it as null, atleast we should inform in some way if possible

Comment (PallaviGanorkar) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:221]: one suggestion added, Other things LGTM. Code owner can have look once

**Review by jingtang10 — APPROVED** [review]

File: engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt (hunk 1 above)
Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt:221]: This is used by the database layer to create indexes for searching. Returning null will signify to caller that there is nothing to be added to the index table for this particular property.
