### PR TITLE
Match questionnaire items and questionnaire response items by link id

### LINKED ISSUE #1664: SDC | Unexpected behaviour on saving a questionnaire after loading it using a filled QR.
**Describe the bug**
The Questionnaire Response generated on save after rendering a Questionnaire with QR is erroneous.

**Component**
SDC library

**To Reproduce**
1. Render a questionnaire in SDC
2. Fill the form and save the Questionnaire Response
3. Render again using same questionnaire and saved QR.
4. Now save the questionnaire response again, this will be erroneous.
5. On loading again using same Questionnaire and last generated QR, the form filler will act weird.

**Expected behavior**
Form filler should behave the same on step 5 as on step 3.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1664 

**Description**

The problem is that the `getEnabledResponseItems` function does not match questionnaire items and questionnaire response items by linkId. As a result if there is any missing items in the questionnaire response the entire enablement calculation gets out of sync. The fix in this PR is to match them by linkId before doing any enablement calculation.

- Match questionnaire items and questionnaire response items by link id
- Test case for it
- Group questionnaire view model test cases

**Alternative(s) considered**
NA

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 1]
```diff
@@ -905,168 +955,285 @@ class QuestionnaireViewModelTest(
...
-            linkId = "a-link-id"
-            text = "Basic question"
-            type = Questionnaire.QuestionnaireItemType.GROUP
-            initial =
-              mutableListOf(
-                Questionnaire.QuestionnaireItemInitialComponent().setValue(BooleanType(true))
-              )
+            linkId = "question-1"
+            type = Questionnaire.QuestionnaireItemType.BOOLEAN
+            addInitial().apply { value = BooleanType(true) }
```
Comment (omarismail94) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:1059]: can you please remove this line as it's confusing? Thanks!

Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done

**Review by omarismail94 — APPROVED** [review]
