### PR TITLE
Unselect single choice option on click if option was previously selected.

### LINKED ISSUE #1512: Single choice does not unselect the answer option on click.
**Describe the bug**

- Currently, in single choice view if selected answer option get clicked, it does not get unselected.

**Component**
SDC library

**To Reproduce**

**Expected behavior**
If selected answer option is clicked then it sould be shown as unselected answer option.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1512 

**Description**
Unselect single choice answer option on click, if option was previously selected.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

https://user-images.githubusercontent.com/86107848/182087020-09edd007-f650-46d2-ade0-58c716960bb4.mov

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt [hunk 1]
```diff
@@ -99,6 +99,7 @@ internal object QuestionnaireItemRadioGroupViewHolderFactory :
             .inflate(R.layout.questionnaire_item_radio_button, null)
         val radioButton =
           radioButtonItem.findViewById<RadioButton>(R.id.radio_button) as RadioButton
+        var isCurrentlySelected = false
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:102]: I think `false` is redundant here. Change to `var isCurrentlySelected: Boolean`

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt [hunk 2]
```diff
@@ -111,8 +112,10 @@ internal object QuestionnaireItemRadioGroupViewHolderFactory :
               ViewGroup.LayoutParams.WRAP_CONTENT
             )
           isChecked = questionnaireItemViewItem.isAnswerOptionSelected(answerOption)
-          setOnCheckedChangeListener { checkedButton, isChecked ->
-            when (isChecked) {
+          isCurrentlySelected = questionnaireItemViewItem.isAnswerOptionSelected(answerOption)
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:115]: can we use `isChecked` as the value for `isCurrentlySelected`? We run the same method twice

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt [hunk 3]
```diff
@@ -111,8 +112,10 @@ internal object QuestionnaireItemRadioGroupViewHolderFactory :
...
+          setOnClickListener { radioButton ->
+            isCurrentlySelected = !isCurrentlySelected
+            when (isCurrentlySelected) {
               true -> {
                 // if-else block to prevent over-writing of "items" nested within "answer"
                 if (questionnaireItemViewItem.answers.isNotEmpty()) {
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:121]: Since we are adding a layer of indentation with the `when`, let's extract the if/else statement into a separate function (`functionName(annswerOption)` to make this easier to read

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt [hunk 4]
```diff
@@ -112,22 +112,12 @@ internal object QuestionnaireItemRadioGroupViewHolderFactory :
               ViewGroup.LayoutParams.WRAP_CONTENT
             )
           isChecked = questionnaireItemViewItem.isAnswerOptionSelected(answerOption)
-          isCurrentlySelected = questionnaireItemViewItem.isAnswerOptionSelected(answerOption)
+          isCurrentlySelected = isChecked
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:115]: one more comment: `isCurrentlySelected`  wont be affected if `isChecked` changes later right? IIUC, Kotlin does not assign the same memory address, but rather a copy of the reference.

**Review by omarismail94 — APPROVED** [review]
Nice change! Just one comment

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:115]: correct!

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt [hunk 5]
```diff
@@ -316,6 +316,33 @@ class QuestionnaireItemRadioGroupViewHolderFactoryTest {
       .isTrue()
   }
 
+  @Test
+  fun `onClick should unselect radio button if previous state is selected`() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt:320]: separate this into two test cases. one to assert on the button status (checked vs unchecked), one to assert on the answer component.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt (hunk 4 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:115]: what you have here is essentially a function closure - have you considered actually saving these as a variables in the delegate object?

you can declare a list of boolean values, for example.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Comment by santosh-pingle** [comment]
working on review comments.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt [hunk 6]
```diff
@@ -99,6 +99,7 @@ internal object QuestionnaireItemRadioGroupViewHolderFactory :
             .inflate(R.layout.questionnaire_item_radio_button, null)
         val radioButton =
           radioButtonItem.findViewById<RadioButton>(R.id.radio_button) as RadioButton
+        var isCurrentlySelected: Boolean
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: done.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt (hunk 5 above)
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: there is only single boolean variable `isCurrentlySelected` and others are property which belongs to radio button itself.

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: well this approach is probably fine. but the alternative is to create an array to track these things for the whole widget. have you considered that?

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: Sorry, can you please help me to understand it, would you like to share some code suggestion.

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt]: you could add an array to the widget, e.g.

```
val selected: List<Boolean>
```

that tracks the status of all these selections.

i'm not suggesting that this is better, but this is an alternative approach to adding variables.

an article able function closures: https://www.i-programmer.info/programming/other-languages/12255-the-programmers-guide-to-kotlin-anonymous-and-lambda-functions.html?start=2#:~:text=3%20of%203-,Closure,variable%20work%20rather%20than%20closure.

your code only works because the variable you added is being maintained as environment to the lambda callback function. it's fine, but it's a bit implicit.

**Comment by jingtang10** [comment]
i think this is good to merge

**Review by jingtang10 — APPROVED** [review]
thanks @santosh-pingle
