### PR TITLE
Show time-picker in input mode.

### LINKED ISSUE #1620: SDC Catalog app: nothing happens when tapping the text field box of Time entry
**Describe the bug**
nothing happens when you press the text field box of Time entry, only when you press the time icon does the time widget open

**Component**
SDC gallery app

**To Reproduce**
1. Go to DateTime picker in SDC catalog app
2. Tap on text field box
3. Wait for nothing to happen and press again
4. Tap on the time icon and widget opens, then press the keyboard icon in the bottom left.

**Expected behavior**
Show the same widget as what's displayed in the time widget when you press the keyboard entry icon

**Screenshots**
Screenshot_20220921-154710

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1620 

**Description**

- Existing implementation shows time picker view in clock mode.
- This change shows time-picker in input mode.  

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
https://user-images.githubusercontent.com/86107848/200792581-9bea6dbe-16d4-436d-8342-72ef8e6dec05.mov

**Comment by omarismail94** [comment]
@santosh-pingle  This PR doesn't solve the problem that Shelagh had. Right now, the PR changes the input format to the keyboard, as opposed to having a clock. 

The issue that Shelagh had was if you press on the textbox, the pop-up window to select the time doesn't open. It only opens if you press the icon

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 1]
```diff
@@ -298,6 +299,7 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
             } else {
               setTimeFormat(TimeFormat.CLOCK_12H)
             }
+            setInputMode(INPUT_MODE_KEYBOARD)
```
Comment (PallaviGanorkar) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:302]: It wont fix the actual issue , it has just changed TimePicker dialog UI, 
Here Instead of selecting time from analogue clock , user can now enter time with keyboard.
But still the TimePicker dialog open only on the click of clock icon on the right, it still doesn't open on click of time input box which is expected.

**Comment by santosh-pingle** [comment]
> @santosh-pingle This PR doesn't solve the problem that Shelagh had. Right now, the PR changes the input format to the keyboard, as opposed to having a clock.
> 
> The issue that Shelagh had was if you press on the textbox, the pop-up window to select the time doesn't open. It only opens if you press the icon

sorry, I misunderstood the Jing's comment, he suggested to open the time picker in input mode when user click on input text field.
I will implement that change.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:302]: sorry, I misunderstood the Jing's comment, he suggested to open the time picker in input mode when user click on input text field.
I will implement that change.

Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done.

**Comment by PallaviGanorkar** [comment]
@santosh-pingle Please attach video after latest fix for this issue

**Comment by santosh-pingle** [comment]
https://user-images.githubusercontent.com/86107848/203945244-bc7e1ac7-f5af-46b8-ad41-61d88034b421.mov

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt [hunk 2]
```diff
@@ -143,6 +143,28 @@ class QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest {
...
+    onView(allOf(withText("OK")))
+      .inRoot(isDialog())
+      .check(matches(isDisplayed()))
+      .perform(ViewActions.click())
+    onView(withId(R.id.time_input_edit_text)).perform(ViewActions.click())
+    onView(allOf(withId(R.id.material_textinput_timepicker)))
+      .inRoot(isDialog())
+      .check(matches(isDisplayed()))
+  }
+
```
Comment (PallaviGanorkar) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:167]: if possible we can add test case to check input mode( INPUT_MODE_CLOCK and INPUT_MODE_KEYBOARD) OR can add assert for same in existing test case when click on input text or icon

**Review by PallaviGanorkar — COMMENTED** [review]
Added one small comment, other things LGTM. code owner can have look.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:167]: This test already cover if time picker is launched in keyboard input mode or not, 
Basically, if input mode is Keyboard then time picker launch with layout element `material_textinput_timepicker` for which check(assertion) is added.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 3]
```diff
@@ -283,7 +274,7 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
           .build()
       }
 
-      private fun createMaterialTimePicker(context: Context): MaterialTimePicker {
+      private fun createMaterialTimePicker(context: Context, inputMode: Int): MaterialTimePicker {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:277]: i think your `createMaterialTimePicker` and `showMaterialTimePicker` can be one function.

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:277]: the only case where i can think of we might want to have these 2 functions separate is when you cache the time picker and reuse it throughout the questionnaire - which might have a performance gain. but if we're not doing that i feel the code is simpler (more readable) if we just merge the two functions.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt [hunk 4]
```diff
@@ -143,6 +143,28 @@ class QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest {
...
+      )
+
+    runOnUI { viewHolder.bind(questionnaireItemView) }
+    onView(withId(R.id.date_input_layout)).perform(clickIcon(true))
+    onView(allOf(withText("OK")))
+      .inRoot(isDialog())
+      .check(matches(isDisplayed()))
+      .perform(ViewActions.click())
+    onView(withId(R.id.time_input_edit_text)).perform(ViewActions.click())
+    onView(allOf(withId(R.id.material_textinput_timepicker)))
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:163]: add a comment here to say that R.id.material_textinput_timepicker is the id for the text input in the time picker.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt (hunk 2 above)
Comment (jingtang10) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:167]: would be useful to add another test case to check that the dialog with clock is shown when you click the icon.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:277]: done.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:163]: done.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt (hunk 2 above)
Comment (santosh-pingle) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:167]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 5]
```diff
@@ -326,6 +298,41 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
+              setHour(selectedTime.hour)
+              setMinute(selectedTime.minute)
+              if (DateFormat.is24HourFormat(context)) {
+                setTimeFormat(TimeFormat.CLOCK_24H)
+              } else {
+                setTimeFormat(TimeFormat.CLOCK_12H)
+              }
+              setInputMode(inputMode)
+            }
+            .build()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:319]:
```suggestion
          let timeFormat = if (DateFormat.is24HourFormat(context)) {
                TimeFormat.CLOCK_24H
              } else {
                TimeFormat.CLOCK_12H
              }
          MaterialTimePicker.Builder()
            .setTitleText(R.string.select_time)
            .setHour(selectedTime.hour)
            .setMinute(selectedTime.minute)
            .setTimeFormat(timeFormat)
            .setInputMode(inputMode)
            .build()
            .apply{ ... }
            .show( ... )
```

**Review by jingtang10 — APPROVED** [review]
thanks @santosh-pingle

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 5 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt]: done.
