### PR TITLE
KM: Use resourcetype when searching by url 

### LINKED ISSUE #2490: Knowledge Manager uses the name instead of URL to fetch resources
**Describe the bug**
@jingtang10 @MJ1998 @aditya-07 QQ, is my assumption that Knowledge Manager searches for resources using the URLs right?  If yes, I think we have a bug where it is searching by name.

We have a situation where a Library and PlanDefinition have the same name.
 If the KM fetches the resource by the name it ends up with 2 results and always picks the first item.

https://github.com/WorldHealthOrganization/smart-immunizations/blob/cleanup/input/fsh/plandefinitions/IMMZD5DTMeasles.fsh and  https://github.com/WorldHealthOrganization/smart-immunizations/blob/cleanup/input/cql/IMMZD5DTMeasles.cql will end up having the same "name"

### PR DESCRIPTION
**Pull request by MJ1998**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2490 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt [hunk 1]
```diff
@@ -164,10 +166,74 @@ internal class KnowledgeManagerTest {
...
+        id = "PlanDefinition/pdId"
+        name = "PlanDefinitionName"
+        url = commonUrl
+      }
+
+    knowledgeManager.install(writeToFile(libraryWithSameUrl))
+    knowledgeManager.install(writeToFile(planDefinitionWithSameUrl))
+
+    val resources = knowledgeDb.knowledgeDao().getResources()
+    assertThat(resources).hasSize(2)
```
Comment (aditya-07) [inline knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt:189]: Since we assert on the individual resources in the next lines, does this serve any purpose here? If yes, can you add a comment explaining the reason for it here.

File: knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt [hunk 2]
```diff
@@ -164,10 +166,74 @@ internal class KnowledgeManagerTest {
...
+        name = "PlanDefinitionName"
+        url = commonUrl
+        version = "0"
+      }
+
+    knowledgeManager.install(writeToFile(libraryWithSameUrl))
+    knowledgeManager.install(writeToFile(planDefinitionWithSameUrl))
+
+    val resources = knowledgeDb.knowledgeDao().getResources()
+    assertThat(resources).hasSize(2)
```
Comment (aditya-07) [inline knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt:222]: Same as above.

**Review by aditya-07 — APPROVED** [review]
Small nits, otherwise LGTM. Feel free to merge once you have resolved the comments.

File: knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt (hunk 2 above)
Comment (MJ1998) [reply knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt:222]: This is just consistent with other tests as well.
