### PR TITLE
CQL combo 2.0.0 Upgrade - Full PD$apply implementation

### LINKED ISSUE #1403: Generating careplan using workflow library.
**Describe the bug**
When trying to generate a careplan using the generateCarePlan method from FhirOperator.kt, it fails with an Notimplemented error.

**Component**
Workflow library

**To Reproduce**
1. Creating the patient, plandefinition and encounter resource in fhir engine. (Used dummy data from the test files)
2. Using the generateCarePlan method with the respective id of the resources saved.

**Expected behavior**
To return the careplan object.

**Additional context**
- I tried running it on the demo application, on the master branch.
- The patient, plandefinition & encounter resources - [patient-plandef-encounter.txt](https://github.com/google/android-fhir/files/8727816/patient-plandef-encounter.txt).
- Stack Trace:
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
        at com.google.android.fhir.workflow.FhirEngineDal.read(FhirEngineDal.kt:33)
        at org.opencds.cqf.cql.evaluator.plandefinition.r4.PlanDefinitionProcessor.apply(PlanDefinitionProcessor.java:117)
        at com.google.android.fhir.workflow.FhirOperator.generateCarePlan(FhirOperator.kt:188)
        at com.google.android.fhir.demo.ScreenerViewModel$saveScreenerEncounter$1.invokeSuspend(ScreenerViewModel.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

cc: @jingtang10

### PR DESCRIPTION
**Pull request by vitorpamplona**
Fixes #1403, #1423, #1407, #1365, #915, #656, #718, #1189 
Unlocks: #1334, #1055
Depreciates: #1395

**Description**

This PR brings the full functionality of the $apply operator to Android. 
1. Migrates the CQL Translator, Engine, and Evaluator to version 2.0, which enables the on-device compilation of CQL as well as import/export of JSON and XML executable libraries, dependent libraries, FHIR objects, and ModelInfo. 
2. Upgrades HAPI to 6.0.1 and the project to Java 11 and min SDK 26. It removes desugaring to Java 1.8 (doubling compilation speed), reorganizes the dependency stack, and creates a new module to share workflow testing assets (code and data) between `androidTest` and `test`. 
3. `FhirEngineRetrieveProvider` now uses the existing `XFhirQueryTranslator` to automatically create filtering parameters based on previously-annotated context paths; 
4. Completes the `FhirEngineRetrieveProvider` and provides testing coverage for all types of filters:  
   - filters by context
   - filters by code in codes
   - filters by code in ValueSets
   - filters by id in codes
   - filters by dates
5. Completes the `FhirEngineTerminologyProvider` with a lookup function and reviews all other functions to behave in a similar way to a desktop version. Test cases were added to cover all desktop use cases
6. The hard-coded `active=true` clause for `FhirEngineRetrieveProvider` searches involving Patients was deleted in favor of `active=true` clauses in the CQL files. CQL authors are supposed to filter active records in the CQL itself, not in the provider.  
7. Current test cases were reformatted to be property-order agnostic by using [JSONAssert](https://github.com/skyscreamer/JSONassert) and [XMLUnit](https://www.xmlunit.org/) libraries instead of hardcoding assertions in kotlin
8. Additional test cases were pulled from #1395 and [CQL-Evaluator's PlanDefinition module](https://github.com/DBCG/cql-evaluator/tree/master/evaluator.plandefinition), transformed into a fluent design and included here. 

Thanks to: 
- https://github.com/cqframework/clinical_quality_language/pull/745 
- https://github.com/cqframework/clinical_quality_language/pull/747 
- https://github.com/cqframework/clinical_quality_language/pull/748 
- https://github.com/cqframework/clinical_quality_language/pull/750 
- https://github.com/cqframework/clinical_quality_language/pull/752 
- https://github.com/cqframework/clinical_quality_language/pull/760
- https://github.com/cqframework/clinical_quality_language/pull/766 
- https://github.com/cqframework/clinical_quality_language/pull/769 
- https://github.com/cqframework/clinical_quality_language/pull/770
- https://github.com/cqframework/clinical_quality_language/pull/788
- https://github.com/cqframework/clinical_quality_language/pull/791
- https://github.com/cqframework/clinical_quality_language/pull/793 
- https://github.com/cqframework/clinical_quality_language/pull/794 
- https://github.com/cqframework/clinical_quality_language/pull/802 
- https://github.com/DBCG/cql_engine/pull/581 
- https://github.com/DBCG/cql_engine/pull/587 
- https://github.com/DBCG/cql_engine/pull/601 
- https://github.com/DBCG/cql_engine/pull/602 
- https://github.com/DBCG/cql_engine/pull/603 
- https://github.com/DBCG/cql_engine/pull/604
- https://github.com/DBCG/cql_engine/pull/605 
- https://github.com/DBCG/cql-evaluator/pull/73 
- https://github.com/DBCG/cql-evaluator/pull/74 
- https://github.com/DBCG/cql-evaluator/pull/96 
- https://github.com/DBCG/cql-evaluator/pull/102 
- https://github.com/DBCG/cql-evaluator/pull/103
- https://github.com/DBCG/cql-evaluator/pull/107
- https://github.com/DBCG/cql-evaluator/pull/138 
- https://github.com/DBCG/cql-evaluator/pull/139 
- https://github.com/DBCG/cql-evaluator/pull/143 
- https://github.com/hapifhir/hapi-fhir/pull/4070
- https://github.com/cqframework/clinical_quality_language/pull/810
- https://github.com/DBCG/cql_engine/pull/613
- https://github.com/DBCG/cql-evaluator/pull/157

**Alternative(s) considered**
No

**Type**
Choose one: Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by vitorpamplona** [comment]
@jingtang10 @fredhersch @pld @ktarasenko 

CQL 2.0 is good to go. This proposal moves us to minSDK 26, pending confirmation from all stakeholders.

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+import org.cqframework.cql.cql2elm.LibraryManager
+import org.cqframework.cql.cql2elm.ModelManager
+import org.cqframework.cql.cql2elm.fhir.r4.FhirLibrarySourceProvider
+import org.hl7.fhir.r4.model.Attachment
+import org.hl7.fhir.r4.model.Enumerations
+import org.hl7.fhir.r4.model.Library
+import org.junit.Assert
+import org.opencds.cqf.cql.engine.serializing.CqlLibraryReaderFactory
+
+object CqlBuilderUtils {
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt:32]: Utils classes were abolished in Kotlin, feel free to use the 
https://kotlinlang.org/docs/java-to-kotlin-interop.html#package-level-functions 
use `@file:JvmName("CqlBuilderUtils")` for java interop, same for other utils

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+
+    // Helper makes sure the test CQL compiles. Reports an error if it doesn't
+    if (translator.errors.isNotEmpty()) {
+      val errors =
+        translator
+          .errors
+          .map { "${it.locator?.toLocator() ?: "[n/a]"}: ${it.message}" }
+          .joinToString("\n")
+
+      Assert.fail("Could not compile CQL File. Errors:\n$errors")
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt:76]: use static import for `fail`, same in the other classes

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+  /**
+   * Assembles an ELM Library exported as a JSON in to a FHIRLibrary
+   *
+   * @param jsonElmStr the JSON representation of the ELM Library
+   * @param libName the Library name
+   * @param libVersion the Library Version
+   *
+   * @return a FHIR Library that includes the ELM Library.
+   */
+  fun assembleFhirLib(
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt:91]: I'd really prefer 3 different functions, but for test utils this is ok

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/XMLAssert.kt [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+
+object XMLAssert {
+  fun assertEquals(expected: String, actual: String) {
+    val diff =
+      DiffBuilder.compare(expected)
+        .withTest(actual)
+        .withNodeMatcher(DefaultNodeMatcher(ElementSelectors.byName))
+        .withDocumentBuilderFactory(
+          DocumentBuilderFactoryImpl()
+        ) // Overrides an incomplete implementation
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/XMLAssert.kt:33]: move the comment up

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/XMLAssert.kt [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+        .checkForSimilar()
+        .build()
+
+    Assert.assertFalse(diff.fullDescription(), diff.hasDifferences())
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/XMLAssert.kt:37]: We use `Truth` for other tests, it reads a bit better

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package com.google.android.fhir.workflow.testing.plandefinition;
+
+import java.util.*;
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java:18]: please avoid * imports

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+import java.util.stream.Collectors;
+
+import org.hl7.fhir.instance.model.api.IBaseResource;
+import org.hl7.fhir.instance.model.api.IIdType;
+import org.hl7.fhir.r4.model.Bundle;
+import org.hl7.fhir.r4.model.MetadataResource;
+import org.opencds.cqf.cql.evaluator.fhir.dal.FhirDal;
+
+public class MockFhirDal implements FhirDal {
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java:27]: Technically it's FakeFhirDal

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java [hunk 8]
```diff
@@ -0,0 +1,91 @@
+/*
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java:1]: Please convert it to Kotlin, it will help saving some boilerplate

File: workflow/src/test/java/com/google/android/fhir/workflow/plandefinition/PlanDefinitionProcessorJavaTests.kt [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+import com.google.android.fhir.workflow.testing.plandefinition.PlanDefinitionProcessorTestBase
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.RobolectricTestRunner
+
+@RunWith(RobolectricTestRunner::class)
+class PlanDefinitionProcessorJavaTests : PlanDefinitionProcessorTestBase() {
+  @Test
+  fun testChildRoutineVisit() {
+    test(
```
Comment (ktarasenko) [inline workflow/src/test/java/com/google/android/fhir/workflow/plandefinition/PlanDefinitionProcessorJavaTests.kt:28]: Wow, this is hard to read, by now I already forgot what test() function does .  I also don't like that the whole structure of the test (init-act-assert) is hidden inside the function.  
What if we: 
- turn `test` to `generateCarePlan` and explicitly name parameters there 
- turn the assertion into kotlin extension function for example `CarePlan.assertEquals(json)` 


The same comments apply for CqlBuilderTestBase

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java [hunk 10]
```diff
@@ -0,0 +1,198 @@
...
+                bundleToSend, null, dataEndpoint, endpoint, endpoint);
+
+        String expectedJson = jsonParser.encodeResourceToString(expected);
+        String actualJson = jsonParser.encodeResourceToString(actual);
+
+        try {
+            JSONAssert.assertEquals(expectedJson, actualJson, false);
+        } catch (JSONException e) {
+            e.printStackTrace();
+            fail("Unable to compare jsons: " + e.getMessage());
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java:195]: can fail accept an exception?

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java [hunk 11]
```diff
@@ -0,0 +1,198 @@
...
+import org.opencds.cqf.cql.evaluator.library.LibraryProcessor;
+import org.opencds.cqf.cql.evaluator.plandefinition.r4.OperationParametersParser;
+import org.opencds.cqf.cql.evaluator.plandefinition.r4.PlanDefinitionProcessor;
+import org.skyscreamer.jsonassert.JSONAssert;
+
+import ca.uhn.fhir.context.FhirContext;
+import ca.uhn.fhir.context.FhirVersionEnum;
+import ca.uhn.fhir.parser.IParser;
+
+public class PlanDefinitionProcessorTestBase {
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java:70]: Inheritance in the tests is kind of discouraged. 

Do you think converting it to a TestRule will be a lot of effort?

**Review by ktarasenko — CHANGES_REQUESTED** [review]
Amazing! Thanks for the update!

File: buildSrc/build.gradle.kts [hunk 12]
```diff
@@ -17,8 +17,8 @@ dependencies {
 
   implementation("com.spotify.ruler:ruler-gradle-plugin:1.2.1")
 
-  implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:5.4.0")
+  implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.0.1")
```
[the remark this answers is not in the document]
Comment (vitorpamplona) [reply buildSrc/build.gradle.kts:20]: There is a buildSrc/../codegen/GenerateSourcesTask class that uses FhirContext and FhirVersionEnum. This is called by the :engine's generateSourcesTask

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java (hunk 10 above)
Comment (vitorpamplona) [reply workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java:195]: No :(

File: workflow/src/test/java/com/google/android/fhir/workflow/plandefinition/PlanDefinitionProcessorJavaTests.kt (hunk 9 above)
Comment (vitorpamplona) [reply workflow/src/test/java/com/google/android/fhir/workflow/plandefinition/PlanDefinitionProcessorJavaTests.kt:28]: We can try to make a fluid interface for these Test Utils 

What about something like: 
```kotlin
CqlBuilderAssert
  .that("/cql-compiler/FHIRHelpers-4.0.1.cql")
  .compiles()
  .generatesJsonEqualsTo("/cql-compiler/FHIRHelpers-4.0.1.elm.json")
  .generatesXmlEqualsTo("/cql-compiler/FHIRHelpers-4.0.1.elm.xml")
  .generatesFhirLibraryEqualsTo("/cql-compiler/FHIRHelpers-4.0.1.fhir.json")
```

And PlanDefinition to: 
```kotlin
PlanDefinitionAssert
  .thatGeneratedCarePlan(
    "ChildRoutineVisit-PlanDefinition-1.0.0", 
    "Patient/ChildRoutine-Reportable", 
    null
  )
  .withData("/plan-definition-apply/child-routine-visit/child_routine_visit_patient.json")
  .withLibrary("/plan-definition-apply/child-routine-visit/child_routine_visit_plan_definition.json")
  .isEqualTo("/plan-definition-apply/child-routine-visit/child_routine_visit_careplan.json")
```

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java (hunk 11 above)
Comment (vitorpamplona) [reply workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java:70]: these are copy/paste classes from the `evaluator.plandefinition` module. I left them as is to simplify adding new test cases from changes on  the `evaluator.plandefinition`. If we rewrite them in Kotlin, we could also make use of the FhirOperator instead of recreating the evaluator for these test cases.

File: workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilder.kt [hunk 13]
```diff
@@ -0,0 +1,236 @@
...
+
+    // Helper makes sure the test CQL compiles. Reports an error if it doesn't
+    if (translator.errors.isNotEmpty()) {
+      val errors =
+        translator
+          .errors
+          .map { "${it.locator?.toLocator() ?: "[n/a]"}: ${it.message}" }
+          .joinToString("\n")
+
+      org.junit.Assert.fail("Could not compile CQL File. Errors:\n$errors")
```
Comment (ktarasenko) [inline workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilder.kt:81]: static import

**Review by ktarasenko — APPROVED** [review]
Love the fluent interface for the testing lib!

**Comment by vitorpamplona** [comment]
@jingtang10 this PR is now running engine and sdc in 24 and workflow on 26, ready for review.

File: workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt [hunk 14]
```diff
@@ -46,33 +59,203 @@ class FhirEngineRetrieveProvider(private val fhirEngine: FhirEngine) :
...
+  ) {
+    if (context == null || contextPath == null || contextValue == null) return
+    // Finds the SearchParamDefinition annotation that matches the incoming contextPath
+    val ann = findSearchParamDefinition(dataType, contextPath)
+
+    if (ann != null) {
+      // If found, uses the applyFilterParam
+      if (ann.type == Enumerations.SearchParamType.REFERENCE) {
+        search.filter(
+          ReferenceClientParam(ann.name),
```
Comment (maimoonak) [inline workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: Fro reference the reference depends on the type of referenced entity. Plz chekc an example in this PR. https://github.com/google/android-fhir/pull/1624/files#diff-6f6f5e0316d326e6597666ce4608dce8607c00e2172e2f0facddf4fdc408c3aeR75

The Task needs special handling for our CQL.
Task sends `requestor` as contextPath (automatically driven from somewhere in cql-evaluator), and the context and contextValue is Patient and its `id`. This does not filter Tasks correctly as `requestor` is Practitioner most of the times and we need Tasks of a Patient by `for` field.

Comment (vitorpamplona) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: do we know why this behaviour exists? I don't see the same map `requested` -> `for` in other retrieve implementations. This could be a bug in the evaluator. Do we have a specific plan definition that generates this type of retrieve call?

Comment (vitorpamplona) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: This test case does work, but it has to use "for" 

```kotlin
    val result =
      retrieveProvider.retrieve(
        context = "Patient",
        contextPath = "for",
        contextValue = "P2",
        dataType = "Task",
        templateId = null,
        codePath = null,
        codes = null,
        valueSet = null,
        datePath = null,
        dateLowPath = null,
        dateHighPath = null,
        dateRange = null
      )
        .map { it as Task }
```

Comment (vitorpamplona) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: Got it! The issue should be resolved in the modelInfo, not at the RetrieveProvider https://github.com/DBCG/cql_engine/issues/621

Comment (maimoonak) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: @vitorpamplona do we have any timeline the modelInfo issue. Can we add a temporary fix for Task with a TODO until the actual issues resolves. 
cc: @f-odhiambo can comment better on the priority of measure report indicators we are using (so basically our indicators using Task as denomintor/numerator would return 0 until we have the issue fixed)

Comment (vitorpamplona) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: Can we make a unit test with the complete measure-evaluate in question? We need to ensure the solution addresses your use case because there are other ways to get a `requester` and not a `for` on $apply definitions and expression evaluations. I just don't know how exactly you are getting that retrieve.

Comment (vitorpamplona) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:209]: The issue of hardcoding this in the engine is that somebody else might be using the `requester` instead of the `for`. It would break for them to make this use case work.

**Comment by pld** [comment]
@Tarun-Bhardwaj can you give an update on this? since this is approved, and the failures seem to be network related, is it possible to go ahead and merge?

File: workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt (hunk 14 above)
Comment (vitorpamplona) [reply workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt:206]: Resolved on: https://github.com/DBCG/cql_engine/pull/624

**Comment by vitorpamplona** [comment]
We also need more memory for the GitHub Actions machines. Either that or we need to stop running things in parallel with shared gradle deamon.

**Comment by vitorpamplona** [comment]
@jingtang10 now without the changes in the test environment (P->O), as requested.

File: contrib/barcode/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt [hunk 15]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright 2021 Google LLC
```
Comment (jingtang10) [inline contrib/barcode/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt:2]: can you please revert these files that only have a license header change?

**Review by jingtang10 — APPROVED** [review]

File: workflow-testing/build.gradle.kts [hunk 16]
```diff
@@ -0,0 +1,36 @@
+plugins {
```
Comment (jingtang10) [inline workflow-testing/build.gradle.kts:1]: is there anyway to do this without creating another top-level gradle module?

**Review by jingtang10 — APPROVED** [review]

File: contrib/barcode/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt (hunk 15 above)
Comment (vitorpamplona) [reply contrib/barcode/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt]: copyright changes reverted.
