### PR TITLE
engine/ Improve Readability and Maintainability of Data Purge Function (purge())

### LINKED ISSUE #2528: Improve Readability and Maintainability of Data Purge Function (purge())
**Describe the Issue**

This issue proposes a refactoring of the `purge` function within the engine module for improved code readability and maintainability. The current implementation checks for resource presence, local changes, and force purge flag within nested conditional statements, potentially leading to less readable and maintainable code.

**Suggested Changes:**

The proposed refactor aims to achieve the same functionality with improved clarity by:

* **Combined check for local changes and force purge:** Combine the checks for local changes (`localChanges.isNotEmpty()`) and the `forcePurge` flag within a single condition.
* **Concise comments:** Add concise comments to explain the logic behind each step.
* **Reduced redundancy:** 

**Benefits:**

* Improved code readability by separating concerns and using clear logic flow.
* Enhanced maintainability by simplifying conditional checks and reducing nesting.
* Potentially clearer code for future developers working on this functionality.

**Attached Code Snippets:**

Include the current and proposed code snippets within the issue description for easy reference:

**Current Code:**

```kotlin
override suspend fun purge(type: ResourceType, ids: Set<String>, forcePurge: Boolean) {
    db.withTransaction {
      ids.forEach { id ->
        // To check resource is present in DB else throw ResourceNotFoundException()
        selectEntity(type, id)
        val localChangeEntityList = localChangeDao.getLocalChanges(type, id)
        // If local change is not available simply delete resource
        if (localChangeEntityList.isEmpty()) {
          resourceDao.deleteResource(resourceId = id, resourceType = type)
        } else {
          // local change is available with FORCE_PURGE the delete resource and discard changes from
          // localChangeEntity table
          if (forcePurge) {
            resourceDao.deleteResource(resourceId = id, resourceType = type)
            localChangeDao.discardLocalChanges(
              token = LocalChangeToken(localChangeEntityList.map { it.id }),
            )
          } else {
            // local change is available but FORCE_PURGE = false then throw exception
            throw IllegalStateException(
              "Resource with type $type and id $id has local changes, either sync with server or FORCE_PURGE required",
            )
          }
        }
      }
    }
}
```

**Proposed Code:**

```kotlin
  override suspend fun purge(type: ResourceType, ids: Set<String>, forcePurge: Boolean) {
    db.withTransaction {
      ids.forEach { id ->
        // 1. Verify resource presence:
        selectEntity(type, id)

        // 2. Check for local changes and handle accordingly:
        val localChanges = localChangeDao.getLocalChanges(type, id)
        if (localChanges.isNotEmpty() && !forcePurge) {
          throw IllegalStateException(
            "Resource with type $type and id $id has local changes, either sync with server or FORCE_PURGE required"
          )
        }

        // 3. Delete resource and discard local changes (if applicable):
        resourceDao.deleteResource(id, type)
        if (localChanges.isNotEmpty()) {
          localChangeDao.discardLocalChanges(id, type)
        }
      }
    }
  }
```

This approach provides a clear and concise issue description for the Android FHIR repository, promoting collaboration and potential code improvement.

**Would you like to work on the issue?**
Yes 🚀

### PR DESCRIPTION
**Pull request by itstanany**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2528

**Description**
## Refactor purge() function for improved readability and maintainability

This pull request refactors the `purge` function to enhance code clarity and maintainability. The current implementation utilizes nested conditionals for resource presence, local changes, and force purge checks. This refactoring separates these concerns for improved readability.

**Changes:**

* **Combined Local Changes and Force Purge Check:** Combines the checks for local changes (`localChanges.isNotEmpty()`) and the `forcePurge` flag within a single condition.
* **Concise Comments:** Adds concise comments to explain the logic behind each step.
* **Reduced Redundancy:**

These improvements promote better code understanding and maintainability for future developers.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by MJ1998 — APPROVED** [review]
LGTM

**Review by aditya-07 — APPROVED** [review]

File: engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt [hunk 1]
```diff
@@ -386,26 +386,21 @@ internal class DatabaseImpl(
...
-              token = LocalChangeToken(localChangeEntityList.map { it.id }),
-            )
-          } else {
-            // local change is available but FORCE_PURGE = false then throw exception
-            throw IllegalStateException(
-              "Resource with type $type and id $id has local changes, either sync with server or FORCE_PURGE required",
-            )
-          }
+
+        // 2. Check for local changes and handle accordingly:
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt:392]:
```suggestion
        // 2. Check for local changes (which can only be cleared without syncing in FORCE_PURGE mode):
```

**Review by jingtang10 — APPROVED** [review]
