### PR TITLE
Wire up slider control.

### LINKED ISSUE #828: Slider Widget is not working
**Describe the bug**
Slider Widget is not working and does not render integer type as slider control

**Component**
SDC library

**To Reproduce**
See example [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_slider.json#L46) which should show the widget as slider control but it does not

**Expected behavior**
An integer type should show slider with extension ([FHIR Reference](http://build.fhir.org/ig/HL7/sdc/examples.html#using-sliderstepvalue))

**Additional context**
The class src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt initialize and bind different widgets but no reference of QuestionnaireItemSliderViewHolderFactory was found in this class or anywhere else except in a unit test

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #828 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**
Note : this screenshot was only for testing purpose.
Screen Shot 2021-11-19 at 4 46 53 PM

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt [hunk 1]
```diff
@@ -282,6 +282,38 @@ class QuestionnaireItemAdapterTest {
...
+          questionnaireItem,
+          QuestionnaireResponse.QuestionnaireResponseItemComponent()
+        ) {}
+      )
+    )
+
+    assertThat(questionnaireItemAdapter.getItemViewType(0))
+      .isEqualTo(QuestionnaireItemViewHolderType.SLIDER.value)
+  }
+
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt:316]: move this up to be after the first test case for integer item type (to roughly line 158)

**Review by jingtang10 — APPROVED** [review]
Thanks @santosh-pingle!
