### PR TITLE
Restore Granular Upload Progress Updates and Database Consolidation

### LINKED ISSUE #2355: No intermediate progress for uploads
**Describe the bug**
SyncUploadProgress is emitted on successful batch upload only. By batch upload I mean one iteration of upload [here](https://github.com/google/android-fhir/blob/65d7c1f681129052ed75021a27ef1cb5007ed3aa/engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt#L142)). 
We don't get progress updates for individual uploads in a batch as opposed to earlier.

**Component**
Library: Engine

**To Reproduce**

**Expected behavior**
We should be able to collect intermediate progresses as well.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**
SyncUploadProgress is not enough to reflect intermediate uploads. Currently we just maintain an initialTotal which is not enough.
1. We should store a `total` which is updated every batch. 
2. We should update `remaining` on successful intermediate uploads => This means the upload lambda should return a Flow<X> where X = Some kind of upload results (eg, as earlier it was Pair<LocalChangeToken, Resource>)

**Would you like to work on the issue?**
YES. Can start working on this after 7 days.

### PR DESCRIPTION
**Pull request by MJ1998**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2355 #2408 

**Description**
syncUpload's upload lambda changed from 
`upload: (suspend (List<LocalChange>) -> UploadSyncResult)` TO
`upload: (suspend (List<LocalChange>) -> Flow<UploadRequestResult>)`

Removed `UploadSyncResult` as its not needed anymore.
Uploader.upload returns a Flow<UploadRequestResult>
Modified UploadRequestResult.Failure to have information about localChanges.
Added bundleSize as a config parameter to `UploadRequestGeneratorMode.BundleRequest` to test with bundleSize = 1
Added test case to check flow of multiple results being returned.

**Alternative(s) considered**
Alternative was to solve for #2408 only by returning partial successes also in the consolidated `UploadSyncResult` in case there is a failure. This is developer-convenient as it does not require much change but does not solve both the issues. Also, we anticipate changing this API (in fact potentially moving this API completely) and minimal change could be preferred. However, with a little developer pain we can solve both the issues. Discussed with @aditya-07. 

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt [hunk 1]
```diff
@@ -45,6 +45,7 @@ internal sealed class UploadRequestGeneratorMode {
   data class BundleRequest(
     val httpVerbToUseForCreate: Bundle.HTTPVerb,
     val httpVerbToUseForUpdate: Bundle.HTTPVerb,
+    val bundleSize: Int = 500,
```
Comment (aditya-07) [inline engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt:48]: This is good. I remembered the idea was to allow application developers to specify the Bundle size as outline in this [comment](https://github.com/google/android-fhir/issues/1483#issuecomment-1239545803).

Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt:48]: Yeah so now developers can provide their own bundle size once we accept UploadRequestGeneratorMode as a config param right ?

Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt:48]: It can be passed as part of `UploadStrategy` via `FhirSyncWorker.getUploadStrategy`. We might have to come up with some helper / factory functions to easy creation of configurable Bundle based UploadStrategy

Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt:48]: Yeah. We can take that up in some other PR ?

File: engine/src/test/java/com/google/android/fhir/sync/upload/UploaderTest.kt [hunk 2]
```diff
@@ -116,86 +77,52 @@ class UploaderTest {
...
+
+      // With BundleUploadRequestGenerator, all patches will be squashed into 1 request (default
+      // bundleSize = 500). So only 1 result will be observed.
+      assertThat(result).hasSize(1)
+      assertThat(result.first()).isInstanceOf(UploadRequestResult.Success::class.java)
+      with((result.first() as UploadRequestResult.Success).successfulUploadResponseMappings) {
+        assertThat(this).hasSize(2)
+        with(this.first()) {
+          assertThat(this).isInstanceOf(ResourceUploadResponseMapping::class.java)
+          assertThat(localChanges).hasSize(2)
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/upload/UploaderTest.kt:91]: This seems to be incorrect. It should have been `BundleComponentUploadResponseMapping` given that we are doing a Bundle Upload and not a per resource one.

Taking a deeper look reveals that the issue lies in the old code [Uploader#L93](https://github.com/MJ1998/android-fhir/blob/upload2/engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt#L93). 

I don't think this is causing any side effects right now, but nevertheless, the Uploader code should be fixed to provide correct ResponseMapping in a later PR.

**Review by aditya-07 — COMMENTED** [review]
Excellent work @MJ1998 !! Have a few suggestions and added some comment related to the existing issues that I found in the code. The existing code issues are mostly harmless and can be fixed in later PR's by the team.

File: engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt [hunk 3]
```diff
@@ -134,27 +132,22 @@ internal class Uploader(
...
-  ) : UploadSyncResult()
+    val successfulUploadResponseMappings: List<SuccessfulUploadResponseMapping>,
+  ) : UploadRequestResult()
 
-  data class Failure(val syncError: ResourceSyncException, val localChangeToken: LocalChangeToken) :
-    UploadSyncResult()
+  data class Failure(
+    val localChanges: List<LocalChange>,
+    val uploadError: ResourceSyncException,
+  ) : UploadRequestResult()
```
[the remark this answers is not in the document]
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt:150]: Yeah I was doing that only. 2 child classes of UploadResponseMapping
And then wanted the function handleRequest(UploadRequestMapping): UploadResponseMapping which makes more sense to me. And then upload() could return a Flow
But then we would have to expose the UploadResponseMapping since its internal.
OR map it to the similar data model UploadRequestResult.

This is again a small issue in the context of separation of concerns with the sync APIs in FhirEngine interface! So I thought we can solve this later when we move to FhirSyncDbInteractor.

But do you think we should modify this first before completely moving to the sync APIs ?

File: engine/src/test/java/com/google/android/fhir/sync/upload/UploaderTest.kt (hunk 2 above)
Comment (MJ1998) [reply engine/src/test/java/com/google/android/fhir/sync/upload/UploaderTest.kt:91]: I'll have to dig deeper to understand this. Can you raise an issue explaining this? Will be helpful. Thanks.
The team can address it in a new PR.

File: demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt [hunk 4]
```diff
@@ -33,7 +33,7 @@ class DemoFhirSyncWorker(appContext: Context, workerParams: WorkerParameters) :
 
   override fun getConflictResolver() = AcceptLocalConflictResolver
 
-  override fun getUploadStrategy(): UploadStrategy = UploadStrategy.AllChangesSquashedBundlePut
+  override fun getUploadStrategy(): UploadStrategy = UploadStrategy.AllChangesBundlePut
```
[the remark this answers is not in the document]
Comment (MJ1998) [reply demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt]: Done.

File: engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt [hunk 5]
```diff
@@ -141,23 +143,27 @@ internal class FhirEngineImpl(private val database: Database, private val contex
...
+        with(localChangeFetcher.getProgress()) {
+          emit(
+            SyncUploadProgress(
+              remaining = remaining,
+              initialTotal = initialTotal,
+              uploadError = uploadRequestResult.uploadError,
+            ),
+          )
         }
+        break
```
[the remark this answers is not in the document]
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt]: Thanks to you I figured out even cleaner code. Cheers.

File: engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt [hunk 6]
```diff
@@ -48,27 +49,22 @@ internal class Uploader(
...
       }
-    }
-    return UploadSyncResult.Success(successfulMappedResponses)
-  }
 
   private fun handleUploadResponse(
     mappedUploadRequest: UploadRequestMapping,
     response: Resource,
-  ): UploadRequestResult {
+  ): UploadRequestResult.Success {
```
[the remark this answers is not in the document]
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt]: Done.

File: engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt (hunk 3 above)
[the remark this answers is not in the document]
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt:150]: Raised #2421

File: engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt (hunk 1 above)
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/sync/upload/request/UploadRequestGenerator.kt:48]: Raised #2422

**Review by aditya-07 — APPROVED** [review]
LGTM 👍

File: demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt:1]: this file should have been reverted

File: engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt [hunk 7]
```diff
@@ -141,23 +143,22 @@ internal class FhirEngineImpl(private val database: Database, private val contex
...
-                uploadError = uploadSyncResult.syncError,
-              ),
-            )
+      val uploadRequestResult =
+        upload(localChanges)
+          .onEach { result ->
+            resourceConsolidator.consolidate(result)
+            val newProgress =
+              when (result) {
+                is UploadRequestResult.Success -> localChangeFetcher.getProgress()
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt:152]: this looks like if we're uploading multiple batches, this will emit the same result for each batch.

File: demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
Comment (jingtang10) [reply demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt:1]: not sure. don't think this is worth doing now. just for future reference. don't worry about this.

File: engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt (hunk 7 above)
Comment (MJ1998) [reply engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt:152]: The progress takes the UploadRequestResult into count indirectly.
The consolidation step updates the LocalChnages count which is then fetched by the getProgress API.

File: demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
Comment (MJ1998) [reply demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt:1]: Ok.
