### PR TITLE
Datacapture, refactoring single choice options code to apply custom style.

### LINKED ISSUE #1007: Datacapture, app custom style does not get applied to the single choice options.
**Describe the bug**

Custom style does not get applied to the single choice options when it is customised at application side.

Datacapture has class `QuestionnaireItemRadioGroupViewHolderFactory` which shows single choice options, but it does not use xml file to inflate the radio button options, it uses platform default RadioButton class to add options.

There are 2 approaches to fix this issue.
- Just use MaterialRadioButton instead of RadioButton while adding options in `QuestionnaireItemRadioGroupViewHolderFactory` at run time.
- Use .xml layout file with RadioButton, so that it will be inflated by MaterialLayoutInflater at run time as datacapture theme is material theme.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1007 

**Description**
Use .xml layout file with RadioButton to create radio button options. So that it will be inflated by MaterialLayoutInflater at run time as material theme is declared as datacapture ttheme.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by santosh-pingle** [comment]
Screen Shot 2022-02-15 at 11 24 57 AM

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt [hunk 1]
```diff
@@ -60,18 +60,14 @@ internal object QuestionnaireItemRadioGroupViewHolderFactory :
...
-              isChecked = it.valueCoding.equalsDeep(answer)
-            }
-          )
+          val radioButtonItem =
+            LayoutInflater.from(radioGroup.context)
+              .inflate(R.layout.questionnaire_item_radio_button, null)
+          val radioButton = radioButtonItem.findViewById<RadioButton>(R.id.radio_button)
+          radioButton.isChecked = it.valueCoding.equalsDeep(answer)
+          radioButton.text = it.displayString
+          radioButton.id = index++
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt:69]: i don't know if this id is used to clear the radio button selection. but it would be better to use android api to generate the id rather than using the index value.

```suggestion
          radioButton.id = View.generateViewId()
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Review by jingtang10 — APPROVED** [review]
thanks @santosh-pingle!
