### PR TITLE
replace quantity.unit with quantity.code

### LINKED ISSUE #700: java.lang.NullPointerException: quantity.unit must not be null
**Describe the bug**
This crash was seen recently on latest codebase.

java.lang.NullPointerException: quantity.unit must not be null
 at com.google.android.fhir.index.ResourceIndexer.quantityIndex(ResourceIndexer.kt:277)
        at com.google.android.fhir.index.ResourceIndexer.extractIndexValues(ResourceIndexer.kt:99)
        at com.google.android.fhir.index.ResourceIndexer.index(ResourceIndexer.kt:69)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertResource(ResourceDao.kt:202)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll$suspendImpl(ResourceDao.kt:74)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll(Unknown Source:4)
        at com.google.android.fhir.db.impl.DatabaseImpl$insert$2.invokeSuspend(DatabaseImpl.kt:66)
        at com.google.android.fhir.db.impl.DatabaseImpl$insert$2.invoke(Unknown Source:14)
        at androidx.room.RoomDatabaseKt$withTransaction$2.invokeSuspend(RoomDatabase.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

Resources 
```
{"resourceType":"Observation","id":"633cfdc9-061e-4462-97d3-6f13fa967e6d","code":{"coding":[{"system":"http://loinc.org","code":"8310-5","display":"Temperature"}]},"subject":{"reference":"Patient/2126234"},"valueQuantity":{"value":36.0,"system":"http://unitsofmeasure.org","code":"C"}}


{"resourceType":"Observation","id":"42d0314e-1948-454e-9ef8-5a08041a8d17","code":{"coding":[{"system":"http://loinc.org","code":"8867-4","display":"Heart rate"}]},"subject":{"reference":"Patient/2126234"},"valueQuantity":{"value":76.0,"system":"http://unitsofmeasure.org","code":"/min"}}

{"resourceType":"Observation","id":"5e44c47a-2b52-4b56-8abc-9937eac7ee62","code":{"coding":[{"system":"http://loinc.org","code":"59408-5","display":"Oxygen Saturation"}]},"subject":{"reference":"Patient/2126234"},"valueQuantity":{"value":99.0,"system":"http://unitsofmeasure.org","code":"%"}}

```
https://hl7.org/fhir/R4/bodytemp.html#profile

https://hl7.org/fhir/R4/oxygensat.html

https://hl7.org/fhir/R4/heartrate.html

**Component**
reference app, engine.

**To Reproduce**
Click on Patient on Patient search page -> Click on + (screener encounter) -> take survey -> submit the survey.
While saving extracted resources, crash happens at ResourceIndexer.
It expects unit non null.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by epicadk**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #700

**Description**
Clear and concise code change description. 
replace quantity.unit with quantity.code and modify some search logic to be consistent with the fhir spec

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by epicadk** [comment]
@santosh-pingle done.

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt [hunk 1]
```diff
@@ -1834,7 +1836,7 @@ class SearchTest {
         AND a.resourceId IN (
         SELECT resourceId FROM QuantityIndexEntity
         WHERE resourceType= ? AND index_name = ?
-        AND index_system = ? AND (index_unit = ? AND index_value >= ? AND index_value < ? OR index_canonicalUnit = ? AND index_canonicalValue >= ? AND index_canonicalValue < ?)
+        AND index_system = ? AND (index_code = ? AND index_value >= ? AND index_value < ? OR index_canonicalCode = ? AND index_canonicalValue >= ? AND index_canonicalValue < ?)
         )
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:1840]: i think you might also need to fix the queries here because a code itself doesn't make sense without a system. see the rule qty-3 here: https://www.hl7.org/fhir/datatypes.html#Quantity.

so whenever you search for canonical code, you must also match the system. does this make sense?

happy for you to do this in a follow-up.

**Review by jingtang10 — APPROVED** [review]

**Comment by jingtang10** [comment]
also left a comment in https://github.com/google/android-fhir/pull/682#issuecomment-900237346 that is related (but this change can be merged independently)

let's also follow up there.

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt [hunk 2]
```diff
@@ -367,12 +372,12 @@ private fun getConditionParamPair(
 
   if (system == ucumUrl && unit != null) {
```
Comment (epicadk) [inline engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:373]: @jingtang10 as of now the canonical condition is only checked when the system is `UCUM` so it would match the system every time it attempts to find a canonical match.

File: engine/src/test/java/com/google/android/fhir/search/SearchTest.kt (hunk 1 above)
Comment (epicadk) [reply engine/src/test/java/com/google/android/fhir/search/SearchTest.kt:1840]: Can you check https://github.com/google/android-fhir/pull/705/files#r690341281?

File: engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt (hunk 2 above)
Comment (jingtang10) [reply engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt:373]: the system of the search parameter value right? not the system in the database. at this point you don't know what is stored in the db and we're relying on the knowledge that when we indexed the resources we only stored canonicalised ucum units.
