### PR TITLE
Fix SDC population in non-group questions nesting

### LINKED ISSUE #918: Population for questions nested in non-group questions not working
**Describe the bug**
`sdc-questionnaire-initialExpression` does not work when used in Questionnaire items nested inside non-group questions, questions that are not of type `group`.

**Component**
SDC library

**To Reproduce**
1. Author a form with a text question. Add a nested text question inside it  and set `initialExpression` extension with a relevant expression based on a relevant population resource. The expected value is not shown on the device when the questionnaire is openned

**Expected behavior**
Display the population value when the questionnaire is openned

**Screenshots**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ekigamba**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #918

**Description**
Add support for SDC population in questions nested inside non-group questions

**Alternative(s) considered**
No.

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by ekigamba** [comment]
@jingtang10 Kindly review and get back in case of anything

**Comment by jingtang10** [comment]
@joiskash can you take a look at this please?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt [hunk 1]
```diff
@@ -203,6 +203,8 @@ object ResourceMapper {
             )
         }
       }
+
+      populateInitialValues(question.item, *resources)
```
Comment (joiskash) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt:207]: Looks like this has to be done irrespective of the if condition. Maybe we can rewrite the condition to make this more explicit / readable? Also instead of calling the variable question we should call it questionnaireItem to keep it consistent with the rest of the library.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt [hunk 2]
```diff
@@ -1189,6 +1189,80 @@ class ResourceMapperTest {
...
+    val patientId = UUID.randomUUID().toString()
+    val patient =
+      Patient().apply {
+        gender = Enumerations.AdministrativeGender.FEMALE
+        id = "Patient/$patientId/_history/2"
+      }
+    val questionnaireResponse: QuestionnaireResponse
+    runBlocking { questionnaireResponse = ResourceMapper.populate(questionnaire, patient) }
+
+    assertThat((questionnaireResponse.item[0].answer[0].value as Coding).code).isEqualTo("female")
```
Comment (joiskash) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt:1257]: Should we just use AdministrativeGender.FEMALE.toCode() instead of "female" ?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt (hunk 1 above)
Comment (ekigamba) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt:207]: Thanks. This has been updated

File: datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt (hunk 2 above)
Comment (ekigamba) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt:1257]: yes

**Review by joiskash — APPROVED** [review]
Looks good to  me. Just a small nit, I think it maybe better to have the parameter name as questionnaireItem instead of question. Thats how it is everywhere else in the library too.

**Comment by ekigamba** [comment]
> Looks good to me. Just a small nit, I think it maybe better to have the parameter name as questionnaireItem instead of question. Thats how it is everywhere else in the library too.

Sorry, I missed that
