### PR TITLE
Validate current page items before entering review page

### LINKED ISSUE #1682: Review button doesn't validate the last page of a paginated questionnaire
**Describe the bug**
In a paginated questionnaire that uses the entryMode [extension](http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-entryMode) set to `prior-edit`, the active page needs to be valid before moving to the next page. When used in conjunction with the review [functionality](https://github.com/google/android-fhir/pull/1310), the next button turns into a review button on the final page of the paginated questionnaire. And when this review button is tapped, no validation takes place on this page. An example of this is shown in the video below.

**Component**
SDC Library

**To Reproduce**
N/A

**Expected behavior**
I expect the review button to validate the last page before allowing the user to proceed to the review page.

**Screenshots**
In the video below, the user is first tapping the next button on each page to show the validation erros before entering the required information. Once this is done, the next button is tapped to proceed to the next page. But on the final page (with the heading CHW Assignment), on tapping the review button, no validation is done.

https://user-images.githubusercontent.com/90775548/196958350-565fba78-db0c-4035-b7bd-6cd9803116f5.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
Here is the [questionnaire](https://github.com/google/android-fhir/files/10174766/sample-questionnaire-review-button-not-validating.txt) being used in the video:

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1682 

**Description**
- Create a new function `validateCurrentPageItems` that validates all items on the current page and invoke a function depending on the validation result
- Invoke `validateCurrentPageItems` after review button is pressed
- Rewrite the handler for next button to call `validateCurrentPageItems`
- Reorder some other functions in `QuestionnaireViewModel.kt`

**Alternative(s) considered**
NA

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by jingtang10** [comment]
@omarismail94 this is ready for review

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 1]
```diff
@@ -372,7 +357,19 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
...
+        EntryMode.SEQUENTIAL, -> {
+          validateCurrentPageItems { isInReviewModeFlow.value = true }
+        }
+        EntryMode.RANDOM -> {
+          isInReviewModeFlow.value = true
+        }
+      }
+    } else {
+      isInReviewModeFlow.value = false
+    }
```
Comment (santosh-pingle) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:372]: nit:
```suggestion
    if (reviewModeFlag) {
      when (entryMode) {
        EntryMode.PRIOR_EDIT,
        EntryMode.SEQUENTIAL -> {
          validateCurrentPageItems { isInReviewModeFlow.value = reviewModeFlag }
        }
        EntryMode.RANDOM -> {
          isInReviewModeFlow.value = reviewModeFlag
        }
      }
    } else {
      isInReviewModeFlow.value = reviewModeFlag
    }
```

File: datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt [hunk 2]
```diff
@@ -1259,6 +1260,36 @@ class MoreQuestionnaireItemComponentsTest {
...
+
+  @Test
+  fun `isHidden should return false`() {
+    assertThat(
+        Questionnaire.QuestionnaireItemComponent()
+          .apply { addExtension(EXTENSION_HIDDEN_URL, BooleanType(true)) }
+          .isHidden
+      )
+      .isTrue()
+  }
```
[the remark this answers is not in the document]
Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt (hunk 1 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt:372]: actually i had the code this way 😅 but anroid studio gives a suggestion to say that `reviewFlag` is always `true` or always `false`.

i think this is actually reasonable and the result is probably a bit more readable/explicit.

**Comment by jingtang10** [comment]
thanks both.

**Review by omarismail94 — APPROVED** [review]
Just two comments

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 3]
```diff
@@ -63,7 +63,6 @@ import org.hl7.fhir.r4.model.DateType
 import org.hl7.fhir.r4.model.Expression
```
Comment (omarismail94) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:63]: Since this file has many sections, can we have a summary of all the sections at top of the test?

Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:63]: discussed with @omarismail94, won't do this as it will just get out of sync.

**Review by omarismail94 — APPROVED** [review]
Sweet!
