### PR TITLE
[1135] Sync time is not updating in hamburger menu after manual sync

### LINKED ISSUE #1135: Sync time is not updating in hamburger menu after manual sync with server and toast message shows older time
**Describe the bug**
There are 2 related issues after manual sync with server
1. Sync time is not updating in hamburger menu after manual sync with server. 
2. Also the toast message is shows old last updated time 

**Component**
reference app

**To Reproduce**
1. Install Demo Application on Android phone
2. Launch App
3. wait for some time
4. open hamburger menu
5. Notice last Sync time
6. Now click on Sync button below
7. Now Observer behavior -  
       1. Sync time is not updated in hamburger menu. 
       2. toast message with older time 

**Expected behavior**
1.Sync time should be updated in hamburger menu after manual sync with server 
2.toast message should also show the 

**Screenshots**
SyncTimeInHamburgerMenu
LatestTimeInToast

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 11
 - Build number: 00WW_2_410_SP01

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1135

**Description**
Sync time is not updating in hamburger menu after manual sync with server and toast message also shows older time

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by jingtang10 — APPROVED** [review]
@PallaviGanorkar Great fix! 👍

**Review by jingtang10 — COMMENTED** [review]
Is there anyway to add a test case to catch this?

**Comment by jingtang10** [comment]
any progress on the tests?

**Comment by PallaviGanorkar** [comment]
> any progress on the tests?

Test added

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 1]
```diff
@@ -198,4 +199,53 @@ class SyncJobTest {
...
+    val curentTimeStamp: OffsetDateTime = OffsetDateTime.now()
+    workManager
+      .enqueueUniquePeriodicWork(
+        SyncWorkType.DOWNLOAD_UPLOAD.workerName,
+        ExistingPeriodicWorkPolicy.REPLACE,
+        worker1
+      )
+      .result
+      .get()
+    Thread.sleep(5000)
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:224]: do you have to sleep?
and if you do, does this have to be 5 seconds?

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 2]
```diff
@@ -198,4 +199,53 @@ class SyncJobTest {
...
+    val firstSyncResult = (stateList1[stateList1.size - 1] as State.Finished).result
+    assert(firstSyncResult.timestamp.compareTo(curentTimeStamp) > 0)
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:226]: use `com.google.common.truth.Truth.assertThat` to do assertion in tests. it's a nice library that has a fluent api: https://truth.dev/

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 3]
```diff
@@ -198,4 +199,53 @@ class SyncJobTest {
 
     job.cancel()
   }
+
+  @Test
+  fun `sync time should update on every sync call`() = runBlockingTest {
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:204]:
```suggestion
  fun `Sync time should update on every sync call`() = runBlockingTest {
```

and if you can fix the rest of the test cases in this file it'd be great.

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 4]
```diff
@@ -198,4 +199,53 @@ class SyncJobTest {
...
+    val worker1 = PeriodicWorkRequestBuilder<TestSyncWorker>(15, TimeUnit.MINUTES).build()
+
+    // get flows return by work manager wrapper
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:207]:
```suggestion
    // Get flows return by work manager wrapper
```

and for other comments too.

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 5]
```diff
@@ -198,4 +199,53 @@ class SyncJobTest {
...
+        SyncWorkType.DOWNLOAD_UPLOAD.workerName,
+        ExistingPeriodicWorkPolicy.REPLACE,
+        worker1
+      )
+      .result
+      .get()
+    Thread.sleep(5000)
+    val firstSyncResult = (stateList1[stateList1.size - 1] as State.Finished).result
+    assert(firstSyncResult.timestamp.compareTo(curentTimeStamp) > 0)
+    datastoreUtil.readLastSyncTimestamp()?.let { assert((it).compareTo(curentTimeStamp) > 0) }
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:227]: because this is testing a scenario, we don't really need to do `?.`. if anything we can just be more aggressive and use `!!`

```suggestion
    val timestamp = datastoreUtil.readLastSyncTimestamp()!!
    assertThat(timestamp).isEqualTo(...)
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]
thanks!

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 2 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:226]: Done

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 3 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:204]: Done

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 4 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:207]: Done

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 5 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:227]: Done

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 1 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:224]: Done

Comment (aditya-07) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:235]: @PallaviGanorkar Can you please elaborate on the change?

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 6]
```diff
@@ -233,7 +235,9 @@ class SyncJobTest {
       .result
       .get()
     Thread.sleep(5000)
+    println("After enqueue")
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:238]: Please remove the logs.

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 7]
```diff
@@ -233,7 +235,9 @@ class SyncJobTest {
...
     val firstSyncResult = (stateList1[stateList1.size - 1] as State.Finished).result
+    println("After stateList1 size :"+stateList1)
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:240]: Please remove log statements.

Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt]: Those logs are added for testing purpose as test cases are passing locally on my machine but same are failing in CI. So, for debugging logs are added.  I will update once its fixd

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 1 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt]: Sleep time is reduced to 300 milliseconds

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt [hunk 8]
```diff
@@ -210,6 +212,53 @@ class SyncJobTest {
...
+        worker2
+      )
+      .result
+      .get()
+    Thread.sleep(300)
+    val secondSyncResult = (stateList2[stateList2.size - 1] as State.Finished).result
+    assertThat(secondSyncResult.timestamp).isGreaterThan(firstSyncResult.timestamp)
+    assertThat(datastoreUtil.readLastSyncTimestamp()!!).isGreaterThan(firstSyncResult.timestamp)
+    job2.cancel()
+  }
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:260]:
```suggestion
  fun `Sync time should update on every sync call`() = runBlockingTest {
    val worker1 = PeriodicWorkRequestBuilder<TestSyncWorker>(15, TimeUnit.MINUTES).build()
    val stateFlow1 = syncJob.stateFlow()
    val stateList1 = mutableListOf<State>()
    val job1 = launch { stateFlow1.toList(stateList1) }
    val currentTimeStamp: OffsetDateTime = OffsetDateTime.now()
    workManager
      .enqueueUniquePeriodicWork(
        SyncWorkType.DOWNLOAD_UPLOAD.workerName,
        ExistingPeriodicWorkPolicy.REPLACE,
        worker1
      )
      .result
      .get()
    Thread.sleep(300)
    
    val firstSyncResult = (stateList1[stateList1.size - 1] as State.Finished).result
    assertThat(firstSyncResult.timestamp).isGreaterThan(currentTimeStamp)
    assertThat(datastoreUtil.readLastSyncTimestamp()!!).isGreaterThan(currentTimeStamp)
    job1.cancel()

    // Run sync for second time
    val worker2 = PeriodicWorkRequestBuilder<TestSyncWorker>(15, TimeUnit.MINUTES).build()
    val stateFlow2 = syncJob.stateFlow()
    val stateList2 = mutableListOf<State>()
    val job2 = launch { stateFlow2.toList(stateList2) }
    workManager
      .enqueueUniquePeriodicWork(
        SyncWorkType.DOWNLOAD_UPLOAD.workerName,
        ExistingPeriodicWorkPolicy.REPLACE,
        worker2
      )
      .result
      .get()
    Thread.sleep(300)
    
    val secondSyncResult = (stateList2[stateList2.size - 1] as State.Finished).result
    assertThat(secondSyncResult.timestamp).isGreaterThan(firstSyncResult.timestamp)
    assertThat(datastoreUtil.readLastSyncTimestamp()!!).isGreaterThan(firstSyncResult.timestamp)
    job2.cancel()
  }
```

**Review by aditya-07 — APPROVED** [review]
Just one small suggestion for better formatting. Otherwise, LGTM.!

File: engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt (hunk 3 above)
Comment (PallaviGanorkar) [reply engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt:216]: @jingtang10 As discussed reverted this change

**Review by jingtang10 — APPROVED** [review]

**Comment by jingtang10** [comment]
@PallaviGanorkar this seems to be a legitimate test failure:

```
com.google.android.fhir.sync.SyncJobTest > sync time should update on every sync call FAILED
    java.lang.IndexOutOfBoundsException at SyncJobTest.kt:215
```
