### PR TITLE
Only copy nested items to childless answers

### LINKED ISSUE #2590: Repeated Group: Anomalous behaviour of enableWhen expressions in a repeated group
**Describe the bug**
The `enableWhen` expression condition cascades to other group items below or above the trigger group item. 

**Component**
SDC library

**To Reproduce**
Steps to reproduce the behaviour:
1. Define a repeated group with several items e.g. choice and date fields. 
2. Add an enableWhen expression for showing/hiding a field based on a choice selection (condition). 
3. When the app runs, add items in the UI and click the option(s) tied to the enableWhen expression. 
4. See that multiple fields are affected by the choice selection.

**Expected behaviour**
For an enableWhen expression condition that affects a single field should not cascade to other fields. 

**Screenshots**

https://github.com/google/android-fhir/assets/16164649/cef11fa5-2769-4207-b875-53e62e129fe8

**Smartphone (please complete the following information):**

 
**Additional context**
In the video shared above, there are two fields, a choice option, and a date field. 
The date field only shows if the choice is option A. 
Selecting option A shows all date fields and selecting any other option hides it.  

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2590

**Description**
At the moment we are copying nested items to answers with nested items. This would wipe out any existing answers to nested questions.

This PR makes sure we only copy nested items to new answers. It also improves documentation significantly and adds tests.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt [hunk 1]
```diff
@@ -67,4 +71,100 @@ class MoreQuestionnaireResponseItemComponentsTest {
...
+            addItem(
+              QuestionnaireResponseItemComponent().apply {
+                linkId = "nested-question-2"
+                addAnswer(
+                  QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
+                    value = DecimalType(1.0)
+                  },
+                )
+              },
+            )
```
Comment (MJ1998) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt:155]: How should this behave when only one of the nested items is answered. 
Should it copy the other item with no answer ?

Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt:155]: Thanks for the comment. So this has nothing to do with if the nested items are answered or not. The nested items come from the questionnaire item and are just questions without answers.

It's just to do with if the answer has any children already.

Is this clear? Do you think we need to clarify any of this in the docs?

Jing

Comment (MJ1998) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt:155]: Oh I get it now. Basically you are duplicating the nested structure when user clicks "repeat".
How about we rename the function `copyNestedItemsToChildlessAnswers`  to `copyNestedStructureForNewAnswers` ?

Comment (jingtang10) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt:155]: Thanks Jajoo. I think childless is more accurate than new because childless is a fact and new is an assumption. I also like the term item because it means something in questionnaire and we never use the word structure. I think there's really not much in there though.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt [hunk 2]
```diff
@@ -329,7 +329,22 @@ internal object DiffCallbacks {
...
             newItem is QuestionnaireAdapterItem.RepeatedGroupHeader &&
-              oldItem.responses == newItem.responses
+              // The `onDeleteClicked` function is a function closure generated in the questionnaire
+              // viewmodel with a reference to the parent questionnaire view item. When it is
+              // invoked, it deletes the current repeated group instance from the parent
+              // questionnaire view item by removing it from the list of children in the parent
+              // questionnaire view.
+              // In other words, although the `onDeleteClicked` function is not a data field, it is
+              // a function closure with references to data structures. Because
+              // `RepeatedGroupHeader` does not include any other data fields besides the index, it
```
Comment (MJ1998) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt:339]: Why can't index be used ?

File: datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt [hunk 3]
```diff
@@ -67,4 +71,100 @@ class MoreQuestionnaireResponseItemComponentsTest {
...
+    questionnaireResponseItem.copyNestedItemsToChildlessAnswers(questionnaireItem)
+
+    val nestedItems = questionnaireResponseItem.answer.single().item
+    assertThat(nestedItems).hasSize(2)
+    assertThat(nestedItems.map { it.linkId })
+      .containsExactly("nested-question-1", "nested-question-2")
+    assertThat(nestedItems.first().answer.single().valueIntegerType.value).isEqualTo(1)
+    assertThat(nestedItems.last().answer.single().valueDecimalType.value.toString())
+      .isEqualTo("1.0")
+  }
```
Comment (MJ1998) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt:169]: Can you add a test where the item is repeated non-group item ?

Comment (MJ1998) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt:169]: Actually this is straight forward now that I understand it better.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt (hunk 2 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt:340]: start from this:

```
repeated-group
      |
repeated-group-1
```

and now you add a new repeated group:

```
         repeated-group
                /\
repeated-group-1 repeated-group-2
```

repeated-group-1 has index 0 in both cases. but if the second header is not updated the recycler view might not rebind it and you'll end up with it with a callback trying to delete itself from an old list of children.

Comment (MJ1998) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt:340]: Yep so basically when one of the sibling RepeatedGroupHeader (say index = 0) is deleted, the other's index (say index = 1) would not be sufficient to tell if the contents are same.

**Review by MJ1998 — APPROVED** [review]
LGTM
