### PR TITLE
Review screen ux changes like font style, error icon, not answered text color etc. 

### LINKED ISSUE #1716: Reduce font size of question title in the review mode.
**Describe the bug**
Font size of question title is need to be changed as per ux design request.
It need to be updated to title medium.

**Component**
SDC library

**Expected behavior**
Title medium font should be applied to question title in the review mode.

**Screenshots**

Screen Shot 2022-11-14 at 3 28 36 PM

**Smartphone (please complete the following information):**
 - Device: pixel xl emulator
 - Android version: api 30
 - Build number: na
 - Version na

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1716 

**Description**
Issue : Question text font style of edit mode get applied to the question text in review mode.
Fix : Created separate header item view for review mode so that title medium text style can be applied. 

Do not show the help button in the review mode. 
Show an error icon and not answered text in the error color if question is not answered, refer ux design.
Move common functions of header view item to new file.
Apply style to item divider in review mode.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
@shelaghm 
Screen Shot 2022-11-29 at 5 51 21 PM

**Comment by santosh-pingle** [comment]
@shelaghm 
Screen Shot 2022-11-30 at 6 17 03 PM

**Comment by shelaghm** [comment]
@santosh-pingle Great! Can you check the red text color? It looks too light, it should be `#B3261E`

**Comment by santosh-pingle** [comment]
Screen Shot 2022-12-02 at 3 08 09 PM

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    LayoutInflater.from(context)
+      .inflate(R.layout.questionnaire_item_header_in_review_mode, this, true)
+  }
+
+  fun bind(questionnaireItem: Questionnaire.QuestionnaireItemComponent) {
+    val prefix = findViewById<TextView>(R.id.prefix)
+    val question = findViewById<TextView>(R.id.question)
+    val hint = findViewById<TextView>(R.id.hint)
+    prefix.updateTextAndVisibility(questionnaireItem.localizedPrefixSpanned)
+    updateQuestionText(question, questionnaireItem)
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt:42]: the functions we call here are in the `QuestionnaireItemHeaderView` class. How about we move the common functions we have between classes into a new file?

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt [hunk 2]
```diff
@@ -152,7 +153,8 @@ class DemoQuestionnaireFragment : Fragment() {
             args =
               bundleOf(
                 QuestionnaireFragment.EXTRA_QUESTIONNAIRE_JSON_STRING to
-                  viewModel.getQuestionnaireJson()
+                  viewModel.getQuestionnaireJson(),
+                EXTRA_ENABLE_REVIEW_PAGE to true
```
Comment (omarismail94) [inline catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:157]: did you add this to enable a review page at the end of each questionnaire?

Reading the kdoc for `EXTRA_ENABLE_REVIEW_PAGE` it says:

```
 A [Boolean] extra to control if a review page is shown. By default it will be shown at the end of the questionnaire.
```

which seems to indicate that by default, this flag is true. However, when looking at the QuestionnaireViewMode, it sets it by default to `false`:

```
  private val shouldEnableReviewPage =
    state[QuestionnaireFragment.EXTRA_ENABLE_REVIEW_PAGE] ?: false
```

either update the kdoc to say by default the flag is false, or update the default value to `true` and remove the need to set `EXTRA_ENABLE_REVIEW_PAGE` here

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+import android.util.AttributeSet
+import android.view.LayoutInflater
+import android.widget.LinearLayout
+import android.widget.TextView
+import com.google.android.fhir.datacapture.R
+import com.google.android.fhir.datacapture.localizedInstructionsSpanned
+import com.google.android.fhir.datacapture.localizedPrefixSpanned
+import org.hl7.fhir.r4.model.Questionnaire
+
+internal class QuestionnaireItemHeaderViewInReviewMode(context: Context, attrs: AttributeSet?) :
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt:29]: yes, I can create separate pr to rename  `QuestionnaireItemHeaderView ` to `QuestionnaireItemHeaderViewInEditMode`, as this change will affect many files.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt [hunk 4]
```diff
@@ -34,9 +35,10 @@ internal object QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory :
   QuestionnaireItemViewHolderFactory(R.layout.questionnaire_item_simple_question_answer_view) {
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:35]: done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt:42]: done.

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt (hunk 2 above)
Comment (santosh-pingle) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:157]: I am updating kdoc for `EXTRA_ENABLE_REVIEW_PAGE` with default value is false.

Comment (jingtang10) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt:157]: yeah the kdoc needed to be udpated.

File: datacapture/src/main/res/layout/questionnaire_item_header_in_review_mode.xml [hunk 5]
```diff
@@ -0,0 +1,39 @@
+<?xml version="1.0" encoding="utf-8" ?>
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/res/layout/questionnaire_item_header_in_review_mode.xml]: done.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewModeTest.kt [hunk 6]
```diff
@@ -0,0 +1,196 @@
...
+@RunWith(RobolectricTestRunner::class)
+class QuestionnaireItemHeaderViewInReviewModeTest {
+  private val parent =
+    FrameLayout(
+      RuntimeEnvironment.getApplication().apply { setTheme(R.style.Theme_Material3_DayNight) }
+    )
+  private val view = QuestionnaireItemHeaderViewInReviewMode(parent.context, null)
+
+  @Test
+  fun shouldShowPrefix() {
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewModeTest.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt [hunk 7]
```diff
@@ -20,6 +20,7 @@ import android.view.View
 import android.view.View.GONE
 import android.view.View.VISIBLE
 import android.widget.TextView
+import androidx.core.graphics.ColorUtils
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:24]: yes, its required here `ColorUtils.setAlphaComponent(...`

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 8]
```diff
@@ -0,0 +1,122 @@
...
+    return VISIBLE
+  }
+  return GONE
+}
+
+internal fun initHelpButton(
+  view: View,
+  questionnaireItem: Questionnaire.QuestionnaireItemComponent
+) {
+  val helpButton = view.findViewById<Button>(R.id.helpButton)
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:82]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 9]
```diff
@@ -278,8 +278,8 @@ open class QuestionnaireFragment : Fragment() {
     const val EXTRA_QUESTIONNAIRE_RESPONSE_JSON_URI = "questionnaire-response-uri"
 
     /**
-     * A [Boolean] extra to control if a review page is shown. By default it will be shown at the
-     * end of the questionnaire.
+     * A [Boolean] extra to control if a review page is shown. By default value is false, it will be
+     * shown at the end of the questionnaire if value is true.
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:282]:
```suggestion
     * A [Boolean] extra to enable the review page. Default to false.
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 10]
```diff
@@ -0,0 +1,147 @@
...
+      helpCardView.visibility = VISIBLE
+    }
+  }
+
+  view
+    .findViewById<TextView>(R.id.helpText)
+    .updateTextAndVisibility(questionnaireItem.localizedHelpSpanned)
+}
+
+internal fun initHelpButton(
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:106]:
```suggestion
internal fun initHelpViews(
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt [hunk 11]
```diff
@@ -58,7 +43,12 @@ internal class QuestionnaireItemHeaderView(context: Context, attrs: AttributeSet
     prefix.updateTextAndVisibility(questionnaireItem.localizedPrefixSpanned)
     updateQuestionText(question, questionnaireItem)
     hint.updateTextAndVisibility(questionnaireItem.localizedInstructionsSpanned)
-    initHelpButton(this, questionnaireItem)
+    initHelpButton(
+      findViewById(R.id.helpButton),
+      findViewById(R.id.helpCardView),
+      findViewById(R.id.helpText),
+      questionnaireItem
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt:50]:
```suggestion
    initHelpButton(
      helpButton = findViewById(R.id.helpButton),
      helpCardView = findViewById(R.id.helpCardView),
      helpText = findViewById(R.id.helpText),
      questionnaireItem
```

and in the later call sites.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+  helpButton: Button,
+  helpCardView: MaterialCardView,
+  helpText: TextView,
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:109]:
```suggestion
  helpTextView: TextView,
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 13]
```diff
@@ -0,0 +1,147 @@
...
+internal fun updateQuestionText(
+  questionTextView: TextView,
+  questionnaireItem: Questionnaire.QuestionnaireItemComponent,
+) {
+  val builder = SpannableStringBuilder()
+  questionnaireItem.localizedTextSpanned?.let { builder.append(it) }
+  if (questionnaireItem.required) {
+    builder.appendWithSpan(
+      questionTextView.context.applicationContext.getString(R.string.space_asterisk),
+      questionTextView.context.getColorFromAttr(R.attr.colorError)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:54]: please update this as per reply to https://github.com/google/android-fhir/issues/544#issuecomment-1372143034 

and the kdoc above.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 14]
```diff
@@ -0,0 +1,147 @@
...
+  visibility =
+    if (localizedText.isNullOrEmpty()) {
+      GONE
+    } else {
+      VISIBLE
+    }
+}
+
+/** Returns [VISIBLE] if any of the [view] is visible, else returns [GONE]. */
+internal fun getViewGroupVisibility(vararg view: TextView): Int {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:71]: header view visibility

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 15]
```diff
@@ -0,0 +1,147 @@
...
+) {
+  val helpButton = view.findViewById<Button>(R.id.helpButton)
+  helpButton.visibility =
+    if (questionnaireItem.hasHelpButton) {
+      VISIBLE
+    } else {
+      GONE
+    }
+  val helpCardView = view.findViewById<MaterialCardView>(R.id.helpCardView)
+  var isHelpCardViewVisible = false
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:90]: instead of using this variable, can you just check if the card view is visible and then toggle it?

i think we had an issue with function closure in the library before.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt [hunk 16]
```diff
@@ -0,0 +1,147 @@
...
+
+/** Returns [VISIBLE] if any of the [view] is visible, else returns [GONE]. */
+internal fun getViewGroupVisibility(vararg view: TextView): Int {
+  if (view.any { it.visibility == VISIBLE }) {
+    return VISIBLE
+  }
+  return GONE
+}
+
+internal fun initHelpButton(
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt:78]: delete this function

File: datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml [hunk 17]
```diff
@@ -22,26 +22,77 @@
...
         android:layout_height="wrap_content"
         android:layout_marginTop="@dimen/item_margin_vertical"
-    />
+        android:orientation="horizontal"
+        android:gravity="center_vertical"
+    >
+    <TextView
+            android:id="@+id/error_icon_in_review_mode"
+            android:layout_width="20dp"
+            android:layout_height="20dp"
```
Comment (jingtang10) [inline datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml:82]: put these in dimens.xml

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt [hunk 18]
```diff
@@ -20,35 +20,56 @@ import android.view.View
...
+      private lateinit var hint: TextView
+      private lateinit var header: ConstraintLayout
       override lateinit var questionnaireItemViewItem: QuestionnaireItemViewItem
 
       override fun init(itemView: View) {
         header = itemView.findViewById(R.id.header)
         flyOverTextView = itemView.findViewById(R.id.flyover_text_view)
         answerTextView = itemView.findViewById(R.id.answer_text_view)
         divider = itemView.findViewById(R.id.text_divider)
+        errorIcon = itemView.findViewById(R.id.error_icon_in_review_mode)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:57]: errorTextView

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt (hunk 18 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:57]: @jingtang10 

As per ux design, we are showing an error icon at left and `not answered ` text in a red color which is just normal text and not an error text(which get shown just below the main view).

Now, as per comment, if we do use error property/attribute of TextView to show the 'Not answered' text in red color and error icon to the left, then there will be mismatch in output and ux design. Because with error attribute/property of textView it shows 'not answered' in the pop up when focus even happens on it and error icon to the right of the view.

Please refer below link for more info.
https://developer.android.com/reference/android/widget/TextView#setError(java.lang.CharSequence)
Screenshot 2023-01-09 at 12 17 12 PM


So, we need to keep existing approach where two views are used to show error icon at left and `not answered` text in red color separately, but those will not be referenced individually in kotlin code, instead of it only layout container of the views will be referenced.

Thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt [hunk 19]
```diff
@@ -150,6 +150,9 @@ data class QuestionnaireItemViewItem(
     return questionnaireResponseItem.answer.joinToString { it.value.displayString(context) }
   }
 
+  internal val hasAnswerString: Boolean
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt [hunk 20]
```diff
@@ -85,5 +122,16 @@ internal object QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory :
...
+
+      private fun TextView.setTextColorAsPerAnswer() =
+        if (questionnaireItemViewItem.hasAnswerString) {
+          val color = context.getColorFromAttr(android.R.attr.textColor)
+          setTextColor(ColorUtils.setAlphaComponent(color, TEXT_COLOR_ALPHA))
+        } else {
+          val color = context.getColorFromAttr(R.attr.colorError)
+          setTextColor(color)
+        }
     }
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt]: done.

File: datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml (hunk 17 above)
Comment (santosh-pingle) [reply datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt (hunk 16 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt (hunk 12 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt (hunk 11 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt (hunk 9 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt (hunk 10 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt (hunk 14 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt (hunk 15 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt]: done.

File: datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml [hunk 21]
```diff
@@ -22,29 +22,85 @@
...
+    </androidx.constraintlayout.widget.ConstraintLayout>
     <TextView
         android:id="@+id/flyover_text_view"
         style="?attr/questionnaireSubtitleTextStyle"
         android:layout_width="match_parent"
         android:layout_height="wrap_content"
     />
+    <LinearLayout
+        xmlns:android="http://schemas.android.com/apk/res/android"
+        android:id="@+id/not_answered_view"
```
Comment (jingtang10) [inline datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml:72]:
```suggestion
        android:id="@+id/error_view"
```

Comment (jingtang10) [reply datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml:72]: move this to below the answer view

File: datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml [hunk 22]
```diff
@@ -22,29 +22,85 @@
...
+        <TextView
+            android:id="@+id/error_text_view"
+            style="?attr/questionnaireReviewModeNotAnsweredTextStyle"
+            android:textColor="?attr/colorError"
+            android:layout_width="wrap_content"
+            android:layout_height="wrap_content"
+        />
+    </LinearLayout>
     <TextView
         android:id="@+id/answer_text_view"
```
Comment (jingtang10) [inline datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml:96]: make sure to set this text to be either the answer text, or the no answer string.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt [hunk 23]
```diff
@@ -61,27 +81,46 @@ internal object QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory :
...
+            answerView.visibility = GONE
+          }
+          else -> {
+            if (questionnaireItemViewItem.hasAnswer) {
+              showAnswerView(questionnaireItemViewItem)
+            } else {
+              showNotAnsweredView(questionnaireItemViewItem)
             }
-          text = questionnaireItemViewItem.answerString(context)
+          }
```
[the remark this answers is not in the document]
Comment (shelaghm) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:96]: To clarify `"Specifically, if the question is required, but there's no answer. we should show no answer in normal color."`  Do you mean that if a question is `not` required to show `no answer` in normal/grey color instead of red? If that's the case, then that makes sense to me and I can update my designs.

I agree with showing the same error messages as it is displayed in the edit view. So in that case we'd likely not show "no answer", but rather `missing answer for required question` (depending on what the error message actually is.)

**Comment by santosh-pingle** [comment]
Addressing review comments, thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt (hunk 23 above)
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:96]: @jingtang10 
With this suggested logic, if the user does not interact with questionnaire items, all questionnaire items will be marked as NOT_VALIDATED, and there will be no error messages indicating that some of them have errors (e.g. when 'required' is set to true). Furthermore, questionnaire item types such as Group and Display do not have answers as they serve as labels only, but their validation result will also be NOT_VALIDATED. The decision on whether the answer item view should be displayed or not remains unclear in this scenario.

[the remark this answers is not in the document]
Comment (shelaghm) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt:96]: Discussion w/ Jing:
- Show validation result/error message
- Show no answer and validation result "answer missing for required question"

If a user did not interact with the form --> should fix this so the run the validation @santosh-pingle to figure this out

@shelaghm AI: need another field to display validation errors.

[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt]: @shelaghm 
There is a small error in the mock that needs to be corrected for question "Highest level of education", The expected behavior is as follows:
If a question is mandatory and not answered, then it should show 'Not Answered' and just below it an error message indicating that the answer is missing for the required field. The 'Not Answered' option will be displayed in the same normal gray color that is used in other parts of the mock.

File: datacapture/src/main/res/layout/review_view.xml [hunk 24]
```diff
@@ -22,11 +22,45 @@
     android:layout_marginTop="@dimen/item_margin_vertical"
     android:orientation="vertical"
 >
-    <com.google.android.fhir.datacapture.views.HeaderView
```
Comment (jingtang10) [inline datacapture/src/main/res/layout/review_view.xml:25]: so you're not using the same view any more - can you explain a bit more the rationale?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt [hunk 25]
```diff
@@ -312,6 +314,7 @@ internal class QuestionnaireViewModel(application: Application, state: SavedStat
       .also { result ->
         if (result.values.flatten().filterIsInstance<Invalid>().isNotEmpty()) {
           hasPressedSubmitButton = true
+          hasPressedReviewButton = true
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt [hunk 26]
```diff
@@ -0,0 +1,67 @@
...
+
+/** Returns [VISIBLE] if any of the [view] is visible, else returns [GONE]. */
+internal fun headerViewVisibility(vararg view: TextView): Int {
+  if (view.any { it.visibility == VISIBLE }) {
+    return VISIBLE
+  }
+  return GONE
+}
+
+internal fun initHelpViews(
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:52]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt [hunk 27]
```diff
@@ -0,0 +1,67 @@
...
+  text = localizedText
+  visibility =
+    if (localizedText.isNullOrEmpty()) {
+      GONE
+    } else {
+      VISIBLE
+    }
+}
+
+/** Returns [VISIBLE] if any of the [view] is visible, else returns [GONE]. */
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt [hunk 28]
```diff
@@ -0,0 +1,67 @@
...
+internal fun headerViewVisibility(vararg view: TextView): Int {
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt]: done.

File: datacapture/src/main/res/layout/review_view.xml (hunk 24 above)
Comment (santosh-pingle) [reply datacapture/src/main/res/layout/review_view.xml:25]: Basically, the style for the header view in the review summary page is set separately, because there is no api to set the style by attribute name in Kotlin code therefore existing headerView is not used here. As a result, we have created a separate view that is inlined in review_view.xml.

File: datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml (hunk 22 above)
Comment (santosh-pingle) [reply datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml]: done.

File: datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml (hunk 21 above)
Comment (santosh-pingle) [reply datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt (hunk 23 above)
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt [hunk 29]
```diff
@@ -20,35 +20,55 @@ import android.view.View
...
 
       override fun init(itemView: View) {
         header = itemView.findViewById(R.id.header)
         flyOverTextView = itemView.findViewById(R.id.flyover_text_view)
-        answerTextView = itemView.findViewById(R.id.answer_text_view)
         divider = itemView.findViewById(R.id.text_divider)
+        prefix = itemView.findViewById(R.id.prefix)
+        question = itemView.findViewById(R.id.question)
+        hint = itemView.findViewById(R.id.hint)
+        notAnsweredView = itemView.findViewById(R.id.not_answered_view)
```
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt (hunk 18 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt]: done.

File: catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt (hunk 2 above)
Comment (santosh-pingle) [reply catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt (hunk 3 above)
[the remark this answers is not in the document]
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt]: file does not exist anymore.

File: datacapture/src/main/res/layout/review_view.xml (hunk 24 above)
Comment (jingtang10) [reply datacapture/src/main/res/layout/review_view.xml:25]: would something like this work? https://stackoverflow.com/questions/17277618/get-color-value-programmatically-when-its-a-reference-theme

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt [hunk 30]
```diff
@@ -126,7 +126,10 @@ class QuestionnaireFragment : Fragment() {
 
     val reviewModeButton =
       view.findViewById<View>(R.id.review_mode_button).apply {
-        setOnClickListener { viewModel.setReviewMode(true) }
+        setOnClickListener {
+          viewModel.setReviewMode(true)
+          viewModel.validateQuestionnaireAndUpdateUI()
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt:131]: why do you need this line? i think the questionnaire view model would take care of this (line 610 in this PR)?

File: datacapture/src/main/res/layout/review_view.xml (hunk 24 above)
Comment (jingtang10) [reply datacapture/src/main/res/layout/review_view.xml:25]: actually i think i get what you mean - you have to set multiple styles within the view.. it's kinda tricky. i'm happy with this given that in the future the view might diverge anyway from what we show in edit mode.

**Review by jingtang10 — CHANGES_REQUESTED** [review]
thanks @santosh-pingle just one question below

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt (hunk 23 above)
[the remark this answers is not in the document]
Comment (shelaghm) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt]: @santosh-pingle Yes, that's right. This is what we agreed on and my mocks are out of date. Thank you for writing this up so clearly, I've updated my design mocks to match this pattern.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt (hunk 30 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt]: It is not required, I removed it. 
done.

**Review by jingtang10 — APPROVED** [review]
