### PR TITLE
Set questionnaireResponse.questionnaire to questionnaire.url and not questionnaire.id

### LINKED ISSUE #1028: Mismatch between setting questionnaireResponse.questionnaire and validating it
**Describe the bug**
In QuestionnaireResponseValidator.kt we check if questionnaire.url == questionnaireResponse.questionnaire whereas in the QuestionnaireViewModel we set  questionnaireResponse.questionnaire to questionnaire.id

**Component**
 SDC library

**To Reproduce**
1. Answer a questionnaire which has a different id and url
2. Save the questionnaire response
3. Pass both the questionnaire and the response to the fragment

url - Canonical identifier for this questionnaire, represented as a URI (globally unique)
id - Each resource has an id element which contains the "logical id" of the resource assigned by the server responsible for storing it. The location of a resource instance is an absolute URI constructed from the server base address at which the instance is found, the resource type and the Logical ID, such as http://test.fhir.org/rest/Patient/123 (where 123 is the Logical Id of a Patient resource).

### PR DESCRIPTION
**Pull request by joiskash**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1028 

**Description**
Set questionnaireResponse.questionnaire to questionnaire.url and not questionnaire.id

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by jingtang10 — CHANGES_REQUESTED** [review]
can you add a test case please?

**Comment by joiskash** [comment]
I have modified an existing test case. Set the url to "http://www.sample-org/FHIR/Resources/Questionnaire/questionnaire-1"

**Review by jingtang10 — CHANGES_REQUESTED** [review]
Please add test for questionnaire view model

**Comment by joiskash** [comment]
> Please add test for questionnaire view model

Oops my bad. I have fixed the breaking UTs and also added two new tests.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 1]
```diff
@@ -84,10 +84,7 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
     val questionnaire = Questionnaire().apply { id = "a-questionnaire" }
     val viewModel = createQuestionnaireViewModel(questionnaire)
 
-    assertResourceEquals(
-      viewModel.getQuestionnaireResponse(),
-      QuestionnaireResponse().apply { setQuestionnaire("Questionnaire/a-questionnaire") }
-    )
+    assertResourceEquals(viewModel.getQuestionnaireResponse(), QuestionnaireResponse())
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:87]: rename this test case to `stateHasNoQuestionnaireResponse_shouldCopyQuestionnaireUrl`

and instead of changing the assertion, you should change line 84 to set the url rather than the id.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 2]
```diff
@@ -308,6 +303,81 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
     createQuestionnaireViewModel(questionnaire, questionnaireResponse)
   }
 
+  @Test
+  fun stateHasQuestionnaireResponse_correctQuestionnaireReferenceInQuestionnaireResponse_shouldNotThrowError() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:307]:
```suggestion
  fun stateHasQuestionnaireResponse_questionnaireUrlMatches_shouldNotThrowError() {
```

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 3]
```diff
@@ -308,6 +303,81 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
...
+      Questionnaire().apply {
+        id = "a-questionnaire"
+        url = "http://www.sample-org/FHIR/Resources/Questionnaire/a-questionnaire"
+        addItem(
+          Questionnaire.QuestionnaireItemComponent().apply {
+            linkId = "a-link-id"
+            text = "Basic question"
+            type = Questionnaire.QuestionnaireItemType.BOOLEAN
+          }
+        )
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:318]: in the spirit of having minimum tests, remove the item

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 4]
```diff
@@ -308,6 +303,81 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
...
+        addItem(
+          QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
+            linkId = "a-link-id"
+            addAnswer(
+              QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
+                value = BooleanType(true)
+              }
+            )
+          }
+        )
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:333]: remove

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 5]
```diff
@@ -308,6 +303,81 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
...
+      Questionnaire().apply {
+        id = "a-questionnaire"
+        url = "http://www.sample-org/FHIR/Resources/Questionnaire/questionnaire-1"
+        addItem(
+          Questionnaire.QuestionnaireItemComponent().apply {
+            linkId = "a-link-id"
+            text = "Basic question"
+            type = Questionnaire.QuestionnaireItemType.BOOLEAN
+          }
+        )
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:351]: remove

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 6]
```diff
@@ -308,6 +303,81 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
...
+        addItem(
+          QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
+            linkId = "a-link-id"
+            addAnswer(
+              QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
+                value = BooleanType(true)
+              }
+            )
+          }
+        )
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:366]: remove

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt [hunk 7]
```diff
@@ -308,6 +303,81 @@ class QuestionnaireViewModelTest(private val questionnaireSource: QuestionnaireS
...
+      }
+
+    createQuestionnaireViewModel(questionnaire, questionnaireResponse)
+  }
+
+  @Test
+  fun stateHasQuestionnaireResponse_wrongQuestionnaireReferenceInQuestionnaireResponse_shouldThrowError() {
```
Comment (jingtang10) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt:340]:
```suggestion
  fun stateHasQuestionnaireResponse_questionnaireUrlDoesNotMatch_shouldThrowError() {
```

**Review by jingtang10 — CHANGES_REQUESTED** [review]
just a few small comments!

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 6 above)
Comment (joiskash) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 5 above)
Comment (joiskash) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 4 above)
Comment (joiskash) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 3 above)
Comment (joiskash) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done

File: datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt (hunk 1 above)
Comment (joiskash) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt]: done

**Review by jingtang10 — APPROVED** [review]
Thanks @joiskash!
