### PR TITLE
[832] Patient data is not reflecting on Registered Patient List Bug Fixed

### LINKED ISSUE #832: Patient data is not reflecting on "Registered Patient" List when user add patient details with city as "nairobi" and country as "Ke" (Lowercase),
**Describe the bug**
Patient data is not reflecting on "Registered Patient" List when user add patient details with city as "nairobi" and country as "Ke" (Lowercase), 

**Component**
Core library, reference app

**To Reproduce**
1. Go to 'Reference app'
2. Click on '+' icon 
3. Enter patient details: First name, full name, date of birth,Gender
4. Enter city as 'nairobi'
5. Enter country as 'ke'
6. Click on submit button
7. Search patient in "Registered patient" list
8. Observe behavior

**Expected behavior**
It should show newly added patient details in Registered patient list

**Smartphone (please complete the following information):**
 - Device: Redmi note 7 pro
 - Android version: 10
 - Build number: [e.g. Settings -> About phone -> Build number]

@jingtang10 @Tarun-Bhardwaj @aditya-07

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
Fixes #832

**Description**
Patient data is not reflecting on Registered Patient List due to case sensitive city name filter - Bug Fixed

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Review by jingtang10 — APPROVED** [review]

File: demo/src/main/java/com/google/android/fhir/demo/PatientListViewModel.kt [hunk 1]
```diff
@@ -118,7 +118,7 @@ class PatientListViewModel(application: Application, private val fhirEngine: Fhi
     search.filter(
       Patient.ADDRESS_CITY,
       {
-        modifier = StringFilterModifier.MATCHES_EXACTLY
+        modifier = StringFilterModifier.STARTS_WITH
```
Comment (jingtang10) [inline demo/src/main/java/com/google/android/fhir/demo/PatientListViewModel.kt:121]: Have you tried just remove the modifier?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Review by jingtang10 — APPROVED** [review]
