### PR TITLE
Ensures hiding help card view on every initialization

### LINKED ISSUE #2054: Help card showing on other pages
**Describe the bug**
In one page, when a help icon is clicked, it shows a help card. When moving to other pages, the help card keeps showing on other pages.

**Component**
SDC library

**To Reproduce**
1. Click help icon on page 1
2. Help card shows on page 1
3. Move to other page
4. Help card keeps showing

**Expected behavior**
The help card should not show on other pages.

**Screenshots**
 

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**
N/A

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2054

**Description**
Ensures setting the help card visibility to GONE on every initialization.
The XML of help card is also by default set to GONE, so it should be ok to programmatically set the visibility to GONE as well.

**Alternative(s) considered**
N/A

**Type**
Bug fix

**Demo**
With the fix, play below (help card consistently hidden on other pages):

[device-2023-06-30-160918.webm](https://github.com/google/android-fhir/assets/62053304/8ac4ea17-a6ad-4259-8d25-57bcee5ae46b)

Without the fix, play below (help card showing up randomly on other pages):

[device-2023-06-30-160612.webm](https://github.com/google/android-fhir/assets/62053304/168723b8-5420-45c8-bf1f-68b6341b07e1)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by FikriMilano** [comment]
@santosh-pingle @aditya-07 
kindly have a look.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt [hunk 1]
```diff
@@ -57,6 +57,7 @@ internal fun initHelpViews(
   helpTextView: TextView,
   questionnaireItem: Questionnaire.QuestionnaireItemComponent
 ) {
+  helpCardView.visibility = GONE
```
Comment (omarismail94) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:60]: as you mentioned, the XML sets this to GONE. Can you clarify why then we need to re-initialise? Is it due to the lines below?

```
  helpButton.setOnClickListener {
    helpCardView.visibility =
      when (helpCardView.visibility) {
        VISIBLE -> GONE
        else -> VISIBLE
      }
  }
```

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:60]: @omarismail94 nope, it's to prevent other questionnaire.items to randomly show help card when it's not supposed to.

You can check the 2 videos in the PR description for more details.

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:60]: It might be because recycler view recycles old view that shows a help card, and that is used on the next several view. So we need to really ensure it's hidden on initialization.

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:60]: @omarismail94 does that makes sense?

Comment (omarismail94) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt:60]: Yep, sorry for the late response!

**Review by omarismail94 — APPROVED** [review]

**Comment by omarismail94** [comment]
@FikriMilano please merge the master branch so this can be merged!

**Comment by FikriMilano** [comment]
@omarismail94 done :D
