### PR TITLE
Repeated Group: Fix Definition based extraction for multiple answers

### LINKED ISSUE #1794: Definition based extraction for repeated groups extracts only one set of resources
**Describe the bug**
Definition based extraction not working as expected for repeated groups. eg: If each repeated group answer extracts 3 observations then the expectation for 2 repeated groups is 6 observations, but only one gets extracted

**Component**
 SDC library

**To Reproduce**
Use [test-questionnaire.txt](https://github.com/google/android-fhir/files/10284902/test-questionnaire.txt) as questionnaire json and run 

`val fhirBundle = ResourceMapper.extract(questionnaireResource, questionnaireResponse)`

The resulting fhirBundle will not have all the expected extracted resources.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by nsabale7**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1794 

**Description**
Iterating only questionnaire response items and finding the corresponding questionnaire item, as repeated groups answers create multiple response items with same linkId.

**Alternative(s) considered**
Another alternative can be to create a `mapOf<linkId, QuestionnaireItemComponent>`  so that it can be used to find by `linkId`.
`val currentQuestionnaireItem =
        questionnaireItemList.find { it.linkId == currentQuestionnaireResponseItem.linkId }`  can be replaced by map.

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by joiskash — COMMENTED** [review]
We discussed this solution offline, it makes sense to iterate over the response and then fetch the corresponding questionnaire item since initially this was written assuming that there will be no repeated items. I was just wondering if it may help in performance if we have a map linkId to questionnaireItem instead of doing a find to get the item.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt [hunk 1]
```diff
@@ -1164,6 +1143,119 @@ class ResourceMapperTest {
...
+    val uriTestQuestionnaire =
+      iParser.parseResource(Questionnaire::class.java, questionnaireJson) as Questionnaire
+
+    val uriTestQuestionnaireResponse =
+      iParser.parseResource(QuestionnaireResponse::class.java, questionnaireResponseJson)
+        as QuestionnaireResponse
+
+    val bundle = ResourceMapper.extract(uriTestQuestionnaire, uriTestQuestionnaireResponse)
+
+    val observation1 = bundle.entry[0].resource as Observation
```
Comment (santosh-pingle) [inline datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt:1248]: optional:
```suggestion
    val observation1 = bundle.entry.first().resource as Observation
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt [hunk 2]
```diff
@@ -310,28 +310,21 @@ object ResourceMapper {
     extractionResult: MutableList<Resource>,
     profileLoader: ProfileLoader
   ) {
-    val questionnaireItemListIterator = questionnaireItemList.iterator()
     val questionnaireResponseItemListIterator = questionnaireResponseItemList.iterator()
-    while (questionnaireItemListIterator.hasNext() &&
-      questionnaireResponseItemListIterator.hasNext()) {
+    while (questionnaireResponseItemListIterator.hasNext()) {
```
Comment (santosh-pingle) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt:314]: Optional : 
"RepeatedGroup can have multiple questionnaire response item components for the same questionnaire item linkId. Therefore, it must traverse the structure based on the linkId present in the response item component to avoid missing any remaining response items with the same linkId." please feel to modify it.

**Comment by santosh-pingle** [comment]
Thanks @nsabale7. 
It looks good to me.

File: datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt (hunk 1 above)
Comment (nsabale7) [reply datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt]: Done

File: datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt (hunk 2 above)
Comment (nsabale7) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt:311]: Done, I have modified it a bit.

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt:311]: A few things:

1. if we're doing it this way, please do what you suggested in the description of the PR: https://github.com/google/android-fhir/pull/1911#issue-1622864616 and make this more performant by adding the map.
2. take a look at this function: https://github.com/google/android-fhir/blob/25bd683b82865d32bbf248c989350bcc20ae6a13/datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt#L449 i think you should reuse this function, but you will need to modify the logic so it returns all questionnaire response items for each questionnaire
3. take a look at this: https://github.com/google/android-fhir/blob/25bd683b82865d32bbf248c989350bcc20ae6a13/datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt#L40. so another possible way to handle this is to actually try to modify the questionnaire response before validating it by calling this function. can you have a think about if this would work?

@joiskash fyi

**Review by jingtang10 — COMMENTED** [review]
thanks so much for this PR 👍🙏

please see my comment below.

**Comment by nsabale7** [comment]
@jingtang10 @santosh-pingle Sorry for the delay.

I have done the changes according to the comments given by Jing. I have modified the zipByLinkId and reused as per the point 2. Please review and let me know if any changes.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt [hunk 3]
```diff
@@ -782,9 +782,15 @@ internal inline fun <T> List<Questionnaire.QuestionnaireItemComponent>.zipByLink
       QuestionnaireResponse.QuestionnaireResponseItemComponent,
     ) -> T,
 ): List<T> {
-  val linkIdToQuestionnaireResponseItemMap = questionnaireResponseItemList.associateBy { it.linkId }
-  return mapNotNull { questionnaireItem ->
-    linkIdToQuestionnaireResponseItemMap[questionnaireItem.linkId]?.let { questionnaireResponseItem,
+  val linkIdToQuestionnaireItemMap = associateBy { it.linkId }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt:785]: i would still prefer for you to iterate through the questionnaire items first... the reason being this: if for some reason the questionnaire items and questionnaire response items are out of order, i would rather that our result follows the order of the questionnaire items.

so what you have to change here from the original code, is actually just changing the `associateBy` to `groupBy`.

Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt:785]: can you update the documentation to explain what happens if there're repeated items?

Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt:785]: can you also add test cases to cover repeated items and perhaps items out of order?

**Review by jingtang10 — DISMISSED** [review]

**Comment by nsabale7** [comment]
@omarismail94 No, it needs final review.

**Comment by nsabale7** [comment]
@omarismail94 I have resolved the conflicts. Please review.

**Comment by omarismail94** [comment]
nice change @nsabale7 to clean up the code!
