### PR TITLE
Attachment widget clear preview if no answer

### LINKED ISSUE #1821: Multiple Attachment views in a single form, uploading file in one item also shows in other item.
**Describe the bug**
Questionnaire json file contains multiple attachment widgets.
When user start uploading file to respective attachment item, it also uploads same file to other attachment view.
When user delete file from other attachment view, application exits.

Referred questionnaire
[component_attachment.txt](https://github.com/google/android-fhir/files/10485995/component_attachment.txt)

Captured video

https://user-images.githubusercontent.com/86107848/214203803-e0d13024-2271-46ac-8512-d1c75602449e.mov

**Component**
SDC library

**Expected behavior**
Uploaded file should be shown in the respective attachment widget.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 12

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1821

**Description**
Clear preview if no answer

**Alternative(s) considered**
N/A

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

[device-2023-01-25-152610.webm](https://user-images.githubusercontent.com/62053304/214514994-3d009bb0-3067-4baf-a066-b2ef0ef301d9.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt [hunk 1]
```diff
@@ -124,14 +124,28 @@ internal object QuestionnaireItemAttachmentViewHolderFactory :
...
+        // preview but with no appended answer. So we should always clear the preview when there is
+        // no answer.
+        // This happens because RecyclerView is recycling a widget that already displays the
+        // preview.
+        if (answer == null) {
+          clearPhotoPreview()
+          clearFilePreview()
+          hideDeleteButton()
+        }
       }
```
Comment (santosh-pingle) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:149]:
```suggestion
      private fun displayInitialPreviewOrClear() {
        val answer = questionnaireItemViewItem.answers.firstOrNull()

        // When there are several Attachment widgets, this prevents a bug when the user uploads a
        // file then shows a preview on the first widget, the last widget will also have the same
        // preview but with no appended answer. So we should always clear the preview when there is
        // no answer.
        // This happens because RecyclerView is recycling a widget that already displays the
        // preview.
        if (answer == null) {
          clearPhotoPreview()
          clearFilePreview()
          hideDeleteButton()
          return
        }
        
        answer.valueAttachment?.let { attachment ->
          displayPreview(
            attachmentType = attachment.contentType.type,
            attachmentTitle = attachment.title,
            attachmentByteArray = attachment.data
          )
        }
      }
```

**Review by santosh-pingle — COMMENTED** [review]
Can you please also write unit or android tests if possible?
thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt (hunk 1 above)
Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:149]: Done

**Comment by FikriMilano** [comment]
Sure. doing test

**Comment by FikriMilano** [comment]
@santosh-pingle kindly do another review

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt [hunk 2]
```diff
@@ -124,8 +124,23 @@ internal object QuestionnaireItemAttachmentViewHolderFactory :
         deleteButton.isEnabled = !isReadOnly
       }
 
-      private fun displayInitialPreview() {
-        questionnaireItemViewItem.answers.firstOrNull()?.valueAttachment?.let { attachment ->
+      private fun displayInitialPreviewOrClear() {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:127]: this sounds better:

```suggestion
      private fun displayOrClearInitialPreview() {
```

or actually the original function name seemed fine to me.

up to you

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt [hunk 3]
```diff
@@ -124,8 +124,23 @@ internal object QuestionnaireItemAttachmentViewHolderFactory :
...
+        val answer = questionnaireItemViewItem.answers.firstOrNull()
+
+        // When there are several Attachment widgets, this prevents a bug when the user uploads a
+        // file then shows a preview on the first widget, the last widget will also have the same
+        // preview but with no appended answer. So we should always clear the preview when there is
+        // no answer.
+        // This happens because RecyclerView is recycling a widget that already displays the
+        // preview.
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:135]: I think this is a bit too verbose. also, this bug isn't to do with "first" or "last", it's just the fact that some views are recycled.

I'd suggest simply:

```suggestion
        // Clear preview if there is no answer to prevent showing old previews in views that have been recycled.
```

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt [hunk 4]
```diff
@@ -376,6 +376,37 @@ class QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest {
       .isEqualTo("Document File")
   }
 
+  @Test
+  fun shouldNotDisplayPreviewFromNullAnswer() {
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:380]: does this actually test the case? don't you have to bind the widget to an item with answer first, and then bind the widget to an item without answer and check the preview is cleared?

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt (hunk 4 above)
Comment (FikriMilano) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:380]: my bad, let me do that

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt (hunk 3 above)
Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:135]: sure

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt (hunk 2 above)
Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:127]: i actually like this one

Comment (FikriMilano) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt:127]: the new name i mean

**Comment by FikriMilano** [comment]
@jingtang10 this is ready for another review

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt [hunk 5]
```diff
@@ -376,6 +376,105 @@ class QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest {
...
+
+    assertThat(viewHolder.itemView.findViewById<LinearLayout>(R.id.file_preview).visibility)
+      .isEqualTo(View.GONE)
+
+    assertThat(viewHolder.itemView.findViewById<Button>(R.id.delete).visibility)
+      .isEqualTo(View.GONE)
+  }
+
+  @Test
+  fun shouldNotDisplayPreviewFromNullAnswerAfterPreviouslyBindingNonNullAnswer() {
```
Comment (santosh-pingle) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:411]: optional : may be we can name something like
```suggestion
  fun doNotShowPreviewOfPreviousAnswerAttachmentForCurrentAnswerItem() {
```

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt [hunk 6]
```diff
@@ -376,6 +376,105 @@ class QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest {
       .isEqualTo("Document File")
   }
 
+  @Test
+  fun shouldNotDisplayPreviewFromNullAnswer() {
```
Comment (santosh-pingle) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:380]: optional : can we name something like
```suggestion
  fun doNotShowPreviewIfAnswerDoesNotHaveAttachment() {
```

**Review by santosh-pingle — COMMENTED** [review]
thanks! @FikriMilano,  it looks ok to me, others can please review it.

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt (hunk 5 above)
Comment (FikriMilano) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:411]: sure

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt (hunk 6 above)
Comment (FikriMilano) [reply datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:380]: sure

**Review by jingtang10 — APPROVED** [review]
Thanks @FikriMilano for fixing and thanks @santosh-pingle for taking a look!
