### PR TITLE
Fix for swapped or cleared answers in Open choice/Drop Down View.

### LINKED ISSUE #1537: Open choice/Drop Down view issue
**Describe the bug**
When multiple open choice/drop down questions are present in single page, answers get mismatched.

**Component**
SDC library

**To Reproduce**
1. Use below questionnaire
[patient-registration.zip](https://github.com/google/android-fhir/files/9260187/patient-registration.zip)

**Screenshots**
https://user-images.githubusercontent.com/82660329/182856609-65f5e784-f865-4bb8-a07a-0f14a81de664.mp4

### PR DESCRIPTION
**Pull request by aditya-07**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1537 

**Description**
1.  During the binding of ViewHolder, `collect` is called for the particular `SelectedOptionsFlow` based on the questionnaire item's linkid and every `ViewHolder.bind` call results in an additional `collect job `assigned in the viewholder. 
2. This causes issue as the old View holder may be recycled and assigned to a different  questionnaire item altogether and value change in single Item may trigger collect call in multiple view holders (technically every viewholder this particular item was rendered previously).
3. Since `collect` is called inside the `coroutine scope,` the fix is to `cancel` previous `collect job`. 

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**
[open_choice.webm](https://user-images.githubusercontent.com/18224849/185596951-70580170-b7c0-4a1e-827e-b710f48d22d1.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by jingtang10 — APPROVED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt [hunk 1]
```diff
@@ -48,12 +49,14 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
     object : QuestionnaireItemViewHolderDelegate {
       private lateinit var holder: DialogSelectViewHolder
       override lateinit var questionnaireItemViewItem: QuestionnaireItemViewItem
+      private var selectedOptionsJob: Job? = null
```
Comment (santosh-pingle) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt:52]: Is it possible to use `activity.lifecycleScope.coroutineContext.cancelChildren()` instead of storing the reference

Comment (aditya-07) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt:52]: We want to cancel targeted jobs like in a case where in the full screen just one row is updated, or during scrolling and not everything in one go.
