### PR TITLE
Do not call updateAnswers initially if initial value is not present in the modal.

### LINKED ISSUE #1514: Validation : Initially modal and open choice view shows error message if answer is empty.
**Describe the bug**
Modal and open choice view shows error message initially if answer is empty

**Component**
SDC library.

**To Reproduce**

1. Open catalog app.
2. Click on the Modal view.
3. Click on the gear icon, it opens the bottom sheet.
4. Click on the “Show error state”

**Expected behavior**
Initially, it does not show validation error message.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1514 

**Description**

Although the initial value was not selected, the 'update answer' function was called the first time the bind API was used. As a result, it validated the required field with an invalid result. Now, a check has been added to verify whether the bind API has been called for the first time and whether an initial answer option has been selected. If there is no initial answer option selected, then the answer will not be updated.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
https://user-images.githubusercontent.com/86107848/224241563-1cfc3c2b-c7fe-4022-9ff4-5ae46b3f5e02.mov

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt [hunk 1]
```diff
@@ -86,7 +87,12 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
             // Listen for changes to selected options to update summary + FHIR data model
             viewModel.getSelectedOptionsFlow(item.linkId).collect { selectedOptions ->
               holder.summary.text = selectedOptions.selectedSummary
-              updateAnswers(selectedOptions)
+              when {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:90]: i think a better (and possibly cleaner) fix is to change the call on line 82 to `updateSelectedOptions` so that when you initialize the answer options for the dialog, you don't trigger an update of the view model.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

**Comment by santosh-pingle** [comment]
looking into review comments.

**Comment by santosh-pingle** [comment]
I will update my analysis regarding the review comment soon, so that it can be reviewed, thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt (hunk 1 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:90]: Basically, the implementation of the SDC modal view involves three classes: 1. QuestionnaireItemDialogSelectViewHolderFactory, 2. QuestionnaireItemDialogSelectViewModel, and 3. OptionSelectDialogFragment. The QuestionnaireItemDialogSelectViewHolderFactory and OptionSelectDialogFragment classes reference the QuestionnaireItemDialogSelectViewModel to access a MutableSharedFlow, which triggers the answerOptions list and collects it as well.

Initially, when an API call is made to bind data, the QuestionnaireItemDialogSelectViewHolderFactory class serves as the data source for the answer options list. It triggers the sharedFlow through `viewmodel.updateSelectedOptions` so that the answer options list can be collected by the OptionSelectDialogFragment and displayed in the dialog box when the box is clicked. If an option item is selected or deselected, this triggers an updated answer options list that can be listened to by the QuestionnaireItemDialogSelectViewHolderFactory class to update the answer in the questionnaire response item.

Therefore, the `updateSelectedOptions` call on the `viewmodel` cannot be eliminated, as it is required for this functionality to work correctly.

**Comment by santosh-pingle** [comment]
@omarismail94 @aditya-07 I replied to the comment. Can you please review once?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt (hunk 1 above)
Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:90]: i think the flow in `QuestionnaireItemDialogSelectViewModel` is unfortunately used for two different purposes: 1) setting up the UI in the dialog fragment (the dialog fragment listens to this for UI change) 2) update the selection which is then propagated to the qustionnaire view model by `updateAnswers` function.

let's separate these two different tasks - and i think the problem will be solved.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt [hunk 2]
```diff
@@ -150,6 +148,11 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
         }
         questionnaireViewItem.setAnswer(*answers)
       }
+
+      private fun onSelectedOptions(selectedOptions: SelectedOptions) {
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:152]:
```suggestion
      private fun onOptionsSelected(selectedOptions: SelectedOptions) {
```

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt [hunk 3]
```diff
@@ -75,18 +75,16 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
         holder.header.bind(questionnaireViewItem)
 
         val questionnaireItem = questionnaireViewItem.questionnaireItem
+        val selectedOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
+        viewModel.updateSelectedOptions(selectedOptions)
+        if (selectedOptions.options.any { it.selected }) {
+          onSelectedOptions(selectedOptions)
+        }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:82]: why does this block need to be here?

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt [hunk 4]
```diff
@@ -150,6 +148,11 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
         }
         questionnaireViewItem.setAnswer(*answers)
       }
+
+      private fun onSelectedOptions(selectedOptions: SelectedOptions) {
+        holder.summary.text = selectedOptions.selectedSummary
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:153]: this line should be removed from here.

and this line should probably be added in the bind() function.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt (hunk 3 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:82]: Yes, you are right, this code snippet is not required here.
Basically, updateAnswers() function should not be called in the bind() function.
It just requires to update header summary text.
thanks!

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt (hunk 4 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt [hunk 5]
```diff
@@ -75,14 +75,11 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
         holder.header.bind(questionnaireViewItem)
 
         val questionnaireItem = questionnaireViewItem.questionnaireItem
+        val selectedOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:78]:
```suggestion
        val initialOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
```

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:78]: i think this can be passed directly to the dialog on line 94.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt [hunk 6]
```diff
@@ -162,6 +159,13 @@ internal object QuestionnaireItemDialogSelectViewHolderFactory :
 internal class QuestionnaireItemDialogSelectViewModel : ViewModel() {
   private val linkIdsToSelectedOptionsFlow =
     mutableMapOf<String, MutableSharedFlow<SelectedOptions>>()
+  private lateinit var selectedOptions: SelectedOptions
+
+  fun updateSelectedOptions(selectedOptions: SelectedOptions) {
+    this.selectedOptions = selectedOptions
+  }
+
+  fun getSelectedOptions() = selectedOptions
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:168]: i think this change can be reverted if you're passing the initial options directly to the dialog and skip the view model.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt (hunk 5 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt:78]: done.

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt (hunk 6 above)
Comment (santosh-pingle) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt]: done.

**Review by jingtang10 — APPROVED** [review]
