### PR TITLE
Handle Indexing of canonical types and uri types in referenced resources

### LINKED ISSUE #694: Canonical Types are not being handled yet in fhir sdk
**Describe the bug**
Any resource containing canonical references is not storing in the database. Reason is Class ResourceIndexer line 249 where it tries to cast canonical type into reference entity, which is throwing class cast exception. So far resources checked for this problem are Activity Definition, Observation, Library and Plan Definition.
Standard url for hl7 is https://www.hl7.org/fhir/plandefinition-example.json.html, (See Library Property)

**Component**
Syncing

**To Reproduce**
In attached screenshot Library is valid url as per the documentation, but it will fail to store this resource in the database during syncing when it will try to convert this canonical url into reference entity type, similarly it can be seen for any such url.

**Expected behavior**
Canonical type should remain as canonical type instead of casting as reference entity

**Screenshots**
Screenshot Added
Screenshot from 2021-07-29 15-00-38

**Smartphone (please complete the following information):**

**Additional context**

**Would you like to work on the issue?**
No
Screenshot from 2021-07-29 14-43-34

### PR DESCRIPTION
**Pull request by maimoonak**
Fixes #694 

**Description**
Resource properties which are in SearchParam reference but are of type Canonical/Uri are now handled and do not throw ClassCastException

**Alternative(s) considered**
No alternates. Ideally the resolved type and the SearchParam definition should have been of different type, but Reference, Canonical and Uri and closely related and handled in same way by hapi-fhir library. So we need to handle the resolved type properly

**Type**
Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt [hunk 1]
```diff
@@ -543,6 +546,61 @@ class ResourceIndexerTest {
       .isFalse()
   }
 
+  @Test
+  fun index_reference_canonical_type() {
+    val libraries = mutableListOf("Library/someLibrary1", "Library/someLibrary2")
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt:551]: optional: I don't feel it's adding much to have 2 libraries. can you just test one and get rid of this local variable?

File: engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt [hunk 2]
```diff
@@ -543,6 +546,61 @@ class ResourceIndexerTest {
       .isFalse()
   }
 
+  @Test
+  fun index_reference_canonical_type() {
```
Comment (jingtang10) [inline engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt:550]: can you please reorder the tests so we have:

- `index_reference_referenceType`
- `index_reference_canonicalType`
- `index_reference_uriType`
- `index_reference_null`
- `index_reference_empty`

**Review by jingtang10 — APPROVED** [review]
Thanks @maimoonak!
