### PR TITLE
Fix catalog application crashes when time is set using time picker…

### LINKED ISSUE #1194: Catalog application crashes when time is set using time picker widget
**Describe the bug**
Catalog app is crashes when time is selected using time picker dialog

**Component**
 SDC library

**To Reproduce**
1. Install and launch Catalog app
2. Click on 'Layouts' option from bottom navigation bar
2. Click on 'Default' layout
3. Scroll down to 'last i.e. 10th question' 
4. See here date and time input widget
5. click on 'Clock' icon to input time
6. now Time Picker Popup is opened
7. Select any time and click on 'OK' button
8. See error : App Crashes

**Expected behavior**
App should not crash and allow user to select time from Time Picker Widget

**Smartphone (please complete the following information):**
 - Device: Noika 3.4
 - Android version: 11
 - Build number: 00WW_2_410_SP01

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
… widget - Bug Fixed

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1194

**Description**
Clear and concise code change description. 

**Type**
Choose one: Bug fix
 

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt [hunk 1]
```diff
@@ -75,21 +77,33 @@ internal object QuestionnaireItemDateTimePickerViewHolderFactory :
...
+            } else {
+              questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.let {
+                localDateTime =
+                  LocalDateTime.of(year, month + 1, dayOfMonth, it.hour, it.minute, it.second)
+              }
+              localDateTime?.let {
+                updateDateTimeInput(it)
+                updateDateTimeAnswer(it)
+              }
+            }
```
Comment (jingtang10) [inline datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:104]: is there anyway you can create a single private function that sets the answer from local date and local time?

so that this part of code and the listener for the time input can share the same code path.

**Review by jingtang10 — CHANGES_REQUESTED** [review]

File: datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt (hunk 1 above)
Comment (PallaviGanorkar) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:104]: I have already thought it but could not find way because need to private function for one line of code i.e.
 localDateTime = LocalDateTime.of(year, month + 1, dayOfMonth, it.hour, it.minute, it.second)

and LocalDateTime constructor has input from different local variables

Comment (jingtang10) [reply datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt:104]: got it. thanks for the explanation. i think i actually came across a similar problem before.

**Review by jingtang10 — APPROVED** [review]

File: datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+  fun shouldSetFirstDateInputThenTimeInput() {
+    val questionnaireItemView =
+      QuestionnaireItemViewItem(
+        Questionnaire.QuestionnaireItemComponent().apply { text = "Question?" },
+        QuestionnaireResponse.QuestionnaireResponseItemComponent()
+      ) {}
+
+    runOnUI { viewHolder.bind(questionnaireItemView) }
+
+    Truth.assertThat(
```
Comment (jingtang10) [inline datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt:66]:
```
import Truth.assertThat
```

**Review by jingtang10 — APPROVED** [review]

**Comment by jingtang10** [comment]
Looks good. Thanks for updating the test cases pallavi. Just one request: have you checked (locally is fine) that without the code change your new test cases would fail? I.e. the new test case does test that the fix works.

**Comment by PallaviGanorkar** [comment]
> Looks good. Thanks for updating the test cases pallavi. Just one request: have you checked (locally is fine) that without the code change your new test cases would fail? I.e. the new test case does test that the fix works.

Yes Jing, I have tested locally on emulator with API level 24, 27 & 30 before code changes test cases were failing on API level 24 and 27 . Now after fix its working on all 3 API level
