### PR TITLE
Hotfix sync exceptions for failing server

### LINKED ISSUE #707: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
**Describe the bug**
Reference app crashed.
java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
        at androidx.work.Data.toByteArrayInternal(Data.java:417)
        at androidx.work.Data$Builder.build(Data.java:846)
        at com.google.android.fhir.sync.FhirSyncWorker.buildWorkData(FhirSyncWorker.kt:122)
        at com.google.android.fhir.sync.FhirSyncWorker.access$buildWorkData(FhirSyncWorker.kt:39)
        at com.google.android.fhir.sync.FhirSyncWorker$doWork$job$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:135)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Component**
engine

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by maimoonak**
Fixes #707 

**Description**
Serialization of State exclude the exceptions now. The WorkManager does not allow emitting data more than 10240 bytes

**Alternative(s) considered**
No alternates. This is WorkManager constraint

**Type**
Choose one: (Bug fix)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

File: engine/src/main/java/com/google/android/fhir/Util.kt [hunk 1]
```diff
@@ -69,5 +71,17 @@ class OffsetDateTimeTypeAdapter : TypeAdapter<OffsetDateTime>() {
   override fun read(input: JsonReader): OffsetDateTime = OffsetDateTime.parse(input.nextString())
 }
 
+class StateExclusionStrategy : ExclusionStrategy {
```
Comment (aditya-07) [inline engine/src/main/java/com/google/android/fhir/Util.kt:74]: Mark it internal.

Comment (aditya-07) [reply engine/src/main/java/com/google/android/fhir/Util.kt:74]: Also, please write a kdoc explaining its need.

File: engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt [hunk 2]
```diff
@@ -143,7 +143,9 @@ class TestingUtils constructor(private val iParser: IParser) {
 
   object TestCorruptDatasource : DataSource {
     override suspend fun loadData(path: String): Bundle {
-      throw Exception("Loading failed...")
+      val allowedChars = ('A'..'Z') + ('a'..'z') + ('0'..'9')
+      val hugeStackTraceMessage = (1..10242).map { allowedChars.random() }.joinToString("")
```
Comment (aditya-07) [inline engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt:147]: Please mention the reason for this size. You can link `Data.MAX_DATA_BYTES` here.

File: engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt [hunk 3]
```diff
@@ -143,7 +143,9 @@ class TestingUtils constructor(private val iParser: IParser) {
 
   object TestCorruptDatasource : DataSource {
```
Comment (aditya-07) [inline engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt:144]: Do you think FailingDataSource would be a better suited name? IMHO corrupt data source can still return bad data.

File: engine/src/test/java/com/google/android/fhir/sync/TestCorruptSyncWorker.kt [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+ */
+
+package com.google.android.fhir.sync
+
+import android.content.Context
+import androidx.work.WorkerParameters
+import com.google.android.fhir.resource.TestingUtils
+import org.hl7.fhir.r4.model.ResourceType
+
+class TestCorruptSyncWorker(appContext: Context, workerParams: WorkerParameters) :
```
Comment (aditya-07) [inline engine/src/test/java/com/google/android/fhir/sync/TestCorruptSyncWorker.kt:24]: Same name change here?

**Review by aditya-07 — CHANGES_REQUESTED** [review]

File: engine/src/main/java/com/google/android/fhir/Util.kt [hunk 5]
```diff
@@ -69,5 +71,21 @@ class OffsetDateTimeTypeAdapter : TypeAdapter<OffsetDateTime>() {
   override fun read(input: JsonReader): OffsetDateTime = OffsetDateTime.parse(input.nextString())
 }
 
+/**
+ * Exclusion strategy for [Gson] that handles field exclusions for [State] returned by
+ * FhirSynchronizer. It should skip serializing the exceptions to avoid WorkManager WorkData limit
```
Comment (jingtang10) [inline engine/src/main/java/com/google/android/fhir/Util.kt:76]:
```suggestion
 * Exclusion strategy for [Gson] that handles field exclusions for [State] returned by
 * FhirSynchronizer. It should skip serializing the exceptions to avoid exceeding WorkManager WorkData limit.
```

add link to issue. e.g.

`See https://github.com/google/android-fhir/issues/707.`

**Review by jingtang10 — APPROVED** [review]

**Review by aditya-07 — APPROVED** [review]
